<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Version>19.9.4</Version>
    <TargetFramework>netstandard2.0</TargetFramework>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <LangVersion>latest</LangVersion>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageIcon>spiderly-logo.png</PackageIcon>
    <Authors>Filip Trivan</Authors>
    <Description>Spiderly.SourceGenerators generates a lot of features for both .NET and Angular apps by using attributes on EF Core entities. Its goal is to let developers focus solely on writing specific logic, without worrying about boilerplate code.</Description>
    <PackageTags>spiderly;spiderly-source-gen;spiderly-source-generator;code-generation;crud-generator;angular-generator</PackageTags>
    <Company>Spiderly</Company>
    <ProjectUrl>https://www.spiderly.dev</ProjectUrl>
    <RepositoryUrl>https://github.com/filiptrivan/spiderly</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Spiderly.SourceGenerators.Tests" />
    <InternalsVisibleTo Include="Spiderly.ZooGenerator" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CodegenCS.Core" />
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" PrivateAssets="all" />
    <PackageReference Include="System.Text.Json" PrivateAssets="all" GeneratePathProperty="true" />
    <PackageReference Include="System.IO.Pipelines" PrivateAssets="all" GeneratePathProperty="true" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="" />
    <None Include="spiderly-logo.png" Pack="true" PackagePath="" />
  </ItemGroup>

    <!-- START HACK: https://youtu.be/wp-dxZXRkJ4?si=Q6ByOOf461XRYzBU -->
    <PropertyGroup>
	    <GetTargetPathDependsOn>$(GetTargetPathDependsOn);GetDependencyTargetPaths</GetTargetPathDependsOn>
    </PropertyGroup>
    <Target Name="GetDependencyTargetPaths">
	    <ItemGroup>
		    <TargetPathWithTargetPlatformMoniker Include="$(PKGSystem_Text_Json)\lib\netstandard2.0\System.Text.Json.dll" IncludeRuntimeDependency="false">
		    </TargetPathWithTargetPlatformMoniker>
		    <TargetPathWithTargetPlatformMoniker Include="$(PKGSystem_IO_Pipelines)\lib\netstandard2.0\System.IO.Pipelines.dll" IncludeRuntimeDependency="false">
		    </TargetPathWithTargetPlatformMoniker>
		    <None Include="$(OutputPath)\$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false">
		    </None>
		    <None Include="$(PKGSystem_Text_Json)\lib\netstandard2.0\*.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false">
		    </None>
		    <None Include="$(PKGSystem_IO_Pipelines)\lib\netstandard2.0\*.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false">
		    </None>
	    </ItemGroup>
    </Target>
    <!-- END HACK -->

</Project>