using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace Spiderly.SourceGenerators.Shared
{
    /// <summary>
    /// The single emission seam for generated C# files. Every C#-emitting generator adds its output
    /// through <see cref="AddSpiderlyCSharpSource"/> so each file explicitly declares its nullable
    /// context instead of inheriting the consumer project's: <c>#nullable disable</c> keeps today's
    /// nullable-oblivious output compiling warning-free inside an NRT-enabled consumer, and
    /// <c>#nullable enable</c> is emitted once the generators propagate annotations for that consumer.
    /// The <c>&lt;auto-generated/&gt;</c> marker additionally keeps style analyzers out of generated code.
    /// </summary>
    public static class SpiderlySourceEmission
    {
        public static void AddSpiderlyCSharpSource(this SourceProductionContext context, string hintName, string body, NullableContextOptions nullableContext)
        {
            // Roslyn's own AnnotationsEnabled() is the test: annotations (not warnings) are what make '?'
            // legal, so 'enable'/'annotations' get annotated output and 'disable'/'warnings' get oblivious.
            string header = $"// <auto-generated/>\n#nullable {(nullableContext.AnnotationsEnabled() ? "enable" : "disable")}\n\n";

            context.AddSource(hintName, SourceText.From(header + body, Encoding.UTF8));
        }
    }
}
