//HintName: ProductMediaService.generated.cs
// <auto-generated/>
#nullable disable

using TestApp.Business.ValidationRules;
using TestApp.Business.DataMappers;
using TestApp.Business.DTO;
using TestApp.Business.Entities;
using TestApp.Business.Enums;
using TestApp.Business.ExcelProperties;
using TestApp.Business.Filtering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Localization;
using System.Data;
using FluentValidation;
using Spiderly.Security.Services;
using Spiderly.Security.Interfaces;
using Spiderly.Shared.Excel;
using Spiderly.Shared.Interfaces;
using Spiderly.Shared.Services;
using Spiderly.Shared.Classes;
using Spiderly.Shared.DTO;
using Spiderly.Shared.Extensions;
using Spiderly.Shared.Exceptions;
using Spiderly.Shared.Helpers;
using Mapster;
using Microsoft.AspNetCore.Http;

namespace TestApp.Business.Services
{
    /// <summary>
    /// Generated service for the ProductMedia entity. Override lifecycle hooks
    /// by creating a <c>ProductMediaService</c> class that inherits from this class.
    /// </summary>
    public class ProductMediaServiceGenerated : ServiceBase
    {
        protected readonly EntityServiceDependencies _deps;
        private readonly S3PublicStorageService _s3PublicStorageService;


        public ProductMediaServiceGenerated(EntityServiceDependencies deps) : base(deps.Context, deps.Localizer)
        {
            _deps = deps;
            _s3PublicStorageService = deps.ServiceProvider.GetRequiredService<S3PublicStorageService>();

        }

        #region Read

        /// <summary>
        /// Retrieves the complete MainUIFormDTO for ProductMedia, including the entity DTO and all related collections (one-to-many, many-to-many).
        /// </summary>
        /// <param name="id">The ID of the ProductMedia entity</param>
        /// <returns>ProductMediaMainUIFormDTO containing the entity DTO and related data</returns>
        public async virtual Task<ProductMediaMainUIFormDTO> GetProductMediaMainUIFormDTO(long id)
        {
            return await _deps.Context.WithTransactionAsync(async () =>
            {
                var result = new ProductMediaMainUIFormDTO
                {
                    ProductMediaDTO = await GetProductMediaDTO(id),
                };

                await OnAfterGetProductMediaMainUIFormDTO(result);

                return result;
            });
        }

        /// <summary>
        /// Lifecycle hook called after retrieving ProductMedia MainUIFormDTO.
        /// Override this method to enrich the MainUIFormDTO with additional data (e.g., computed fields, extra queries).
        /// This method runs inside a database transaction.
        /// </summary>
        /// <example>
        /// protected override async Task OnAfterGetProductMediaMainUIFormDTO(ProductMediaMainUIFormDTO mainUIFormDTO)
        /// {
        ///     mainUIFormDTO.CustomProperty = await _deps.Context.DbSet&lt;OtherEntity&gt;().Where(x => x.ProductMediaId == mainUIFormDTO.ProductMediaDTO.Id).CountAsync();
        /// }
        /// </example>
        /// <param name="mainUIFormDTO">The MainUIFormDTO that was just constructed with entity and related data</param>
        protected virtual Task OnAfterGetProductMediaMainUIFormDTO(ProductMediaMainUIFormDTO mainUIFormDTO) => Task.CompletedTask;

        /// <summary>
        /// Retrieves a single ProductMedia entity as a DTO with blob data populated.
        /// </summary>
        /// <param name="id">The ID of the ProductMedia entity</param>
        /// <returns>ProductMediaDTO with all blob properties populated</returns>
        public async virtual Task<ProductMediaDTO> GetProductMediaDTO(long id)
        {
            return await _deps.Context.WithTransactionAsync(async () =>
            {
                var dto = await _deps.Context.DbSet<ProductMedia>()
                    .AsNoTracking()
                    .Where(x => x.Id == id).ProjectToType<ProductMediaDTO>(Mapper.ProductMediaProjectToConfig())
                    .SingleOrDefaultAsync();

                if (dto == null)
                    throw new BusinessException(_deps.Localizer["EntityDoesNotExistInDatabase"]);

                    if (!string.IsNullOrEmpty(dto.Url))
                    {
                        dto.UrlData = dto.Url;
                    }
                    if (!string.IsNullOrEmpty(dto.ThumbnailUrl))
                    {
                        dto.ThumbnailUrlData = dto.ThumbnailUrl;
                    }
                    if (!string.IsNullOrEmpty(dto.HtmlDescription))
                    {
                        dto.HtmlDescriptionData = dto.HtmlDescription;
                    }

                return dto;
            });
        }

        /// <summary>
        /// Retrieves a paginated list of ProductMedia entities.
        /// </summary>
        /// <param name="filterDTO">Filter and pagination parameters</param>
        /// <param name="query">The base query to paginate</param>
        /// <returns>PaginatedResult containing the query and total record count</returns>
        public async virtual Task<PaginatedResult<ProductMedia>> GetPaginatedProductMediaResult(FilterDTO filterDTO, IQueryable<ProductMedia> query)
        {
            return await _deps.Context.WithTransactionAsync(async () =>
            {
                return await PaginatedResultGenerator.Build(query.AsNoTracking(), filterDTO);
            });
        }

        /// <summary>
        /// Retrieves a paginated list of ProductMedia DTOs with blob data populated.
        /// </summary>
        /// <param name="filterDTO">Filter and pagination parameters</param>
        /// <param name="query">The base query to paginate</param>
        /// <returns>PaginatedResultDTO containing ProductMediaDTO list and total record count</returns>
        public async virtual Task<PaginatedResultDTO<ProductMediaDTO>> GetPaginatedProductMediaList(FilterDTO filterDTO, IQueryable<ProductMedia> query)
        {
            PaginatedResult<ProductMedia> paginationResult = new();
            List<ProductMediaDTO> dtoList = null!;

            await _deps.Context.WithTransactionAsync(async () =>
            {
                paginationResult = await GetPaginatedProductMediaResult(filterDTO, query);

                dtoList = await paginationResult.Query
                    .Skip(filterDTO.First)
                    .Take(filterDTO.Rows)
                    .ProjectToType<ProductMediaDTO>(Mapper.ProductMediaProjectToConfig())
                    .ToListAsync();

                foreach (var dto in dtoList)
                {
                    if (!string.IsNullOrEmpty(dto.Url))
                    {
                        dto.UrlData = dto.Url;
                    }
                    if (!string.IsNullOrEmpty(dto.ThumbnailUrl))
                    {
                        dto.ThumbnailUrlData = dto.ThumbnailUrl;
                    }
                    if (!string.IsNullOrEmpty(dto.HtmlDescription))
                    {
                        dto.HtmlDescriptionData = dto.HtmlDescription;
                    }
                }
            });

            return new PaginatedResultDTO<ProductMediaDTO> { Data = dtoList, TotalRecords = paginationResult.TotalRecords };
        }

        /// <summary>
        /// Exports a filtered list of ProductMedia entities to Excel format.
        /// </summary>
        /// <param name="filterDTO">Filter parameters for the export</param>
        /// <param name="query">The base query to export</param>
        /// <param name="cancellationToken">Cancellation token</param>
        /// <returns>Excel file as byte array</returns>
        public async virtual Task<byte[]> ExportProductMediaListToExcel(FilterDTO filterDTO, IQueryable<ProductMedia> query, CancellationToken cancellationToken = default)
        {
            IQueryable<ProductMediaDTO> exportQuery = null!;

            await _deps.Context.WithTransactionAsync(async () =>
            {
                PaginatedResult<ProductMedia> paginationResult = await GetPaginatedProductMediaResult(filterDTO, query);
                int maxRows = _deps.ExcelSettings.ExcelExportMaxRows;
                exportQuery = paginationResult.Query
                    .OrderBy(x => x.Id)
                    .Take(maxRows)
                    .ProjectToType<ProductMediaDTO>(Mapper.ProductMediaExcelProjectToConfig());
            });

            string[] excelPropertiesToExclude = ExcelPropertiesToExclude.GetHeadersToExclude(new ProductMediaDTO());
            return await _deps.ExcelService.FillReportTemplateAsync(
                exportQuery.AsAsyncEnumerable(),
                excelPropertiesToExclude,
                _deps.Localizer,
                cancellationToken);
        }

        /// <summary>
        /// Retrieves a list of ProductMedia entities without pagination.
        /// </summary>
        /// <param name="query">The query to execute</param>
        /// <returns>List of ProductMedia entities</returns>
        public async virtual Task<List<ProductMedia>> GetProductMediaList(IQueryable<ProductMedia> query)
        {
            return await _deps.Context.WithTransactionAsync(async () =>
            {
                var result = await query
                    .ToListAsync();

                return result;
            });
        }

        /// <summary>
        /// Retrieves a list of ProductMedia DTOs without pagination, with blob data populated.
        /// </summary>
        /// <param name="query">The query to execute</param>
        /// <returns>List of ProductMediaDTO with blob properties populated</returns>
        public async virtual Task<List<ProductMediaDTO>> GetProductMediaDTOList(IQueryable<ProductMedia> query)
        {
            return await _deps.Context.WithTransactionAsync(async () =>
            {
                var dtoList = await query
                    .AsNoTracking()
                    .ProjectToType<ProductMediaDTO>(Mapper.ProductMediaToDTOConfig())
                    .ToListAsync();

                foreach (var dto in dtoList)
                {
                    if (!string.IsNullOrEmpty(dto.Url))
                    {
                        dto.UrlData = dto.Url;
                    }
                    if (!string.IsNullOrEmpty(dto.ThumbnailUrl))
                    {
                        dto.ThumbnailUrlData = dto.ThumbnailUrl;
                    }
                    if (!string.IsNullOrEmpty(dto.HtmlDescription))
                    {
                        dto.HtmlDescriptionData = dto.HtmlDescription;
                    }
                }

                return dtoList;
            });
        }



        #endregion

        #region Save

        /// <summary>
        /// Saves a ProductMedia entity and returns the complete MainUIFormDTO including all related collections.
        /// Handles insert/update logic, many-to-many relationships, and ordered one-to-many collections.
        /// </summary>
        /// <param name="saveBodyDTO">The SaveBodyDTO containing entity data and related selections</param>
        /// <param name="authorizeUpdate">Whether to perform authorization check for Update operation</param>
        /// <param name="authorizeInsert">Whether to perform authorization check for Insert operation</param>
        /// <returns>ProductMediaMainUIFormDTO with saved data and updated collections</returns>
        public virtual async Task<ProductMediaMainUIFormDTO> SaveProductMediaAndReturnMainUIFormDTO(ProductMediaSaveBodyDTO saveBodyDTO, bool authorizeUpdate, bool authorizeInsert)
        {
            new ProductMediaSaveBodyDTOValidationRules().ValidateAndThrow(saveBodyDTO);

            return await _deps.Context.WithTransactionAsync(async () =>
            {
                await OnBeforeSaveProductMediaAndReturnMainUIFormDTO(saveBodyDTO);

                var savedDTO = await SaveProductMediaAndReturnDTO(saveBodyDTO.ProductMediaDTO!, authorizeUpdate, authorizeInsert);






                var result = new ProductMediaMainUIFormDTO
                {
                    ProductMediaDTO = savedDTO,



                };

                await OnAfterSaveProductMediaAndReturnMainUIFormDTO(saveBodyDTO, result);

                return result;
            });
        }




        /// <summary>
        /// Lifecycle hook called before saving ProductMedia with MainUIFormDTO.
        /// Override this method to add custom validation or modify the SaveBodyDTO.
        /// This method runs inside a database transaction.
        /// </summary>
        /// <param name="saveBodyDTO">The SaveBodyDTO containing entity and related data</param>
        protected virtual Task OnBeforeSaveProductMediaAndReturnMainUIFormDTO(ProductMediaSaveBodyDTO saveBodyDTO) => Task.CompletedTask;

        /// <summary>
        /// Lifecycle hook called after saving ProductMedia and after updating related collections.
        /// Override this method to add custom business logic after the main entity is saved.
        /// This method runs inside a database transaction.
        /// </summary>
        /// <param name="saveBodyDTO">The original SaveBodyDTO</param>
        /// <param name="mainUIFormDTO">The save result and DTO sent to the UI</param>
        protected virtual Task OnAfterSaveProductMediaAndReturnMainUIFormDTO(ProductMediaSaveBodyDTO saveBodyDTO, ProductMediaMainUIFormDTO mainUIFormDTO) => Task.CompletedTask;

        /// <summary>
        /// Saves a ProductMedia entity and returns the DTO with blob data populated.
        /// </summary>
        /// <param name="saveDTO">The DTO containing entity data to save</param>
        /// <param name="authorizeUpdate">Whether to perform authorization check for Update operation</param>
        /// <param name="authorizeInsert">Whether to perform authorization check for Insert operation</param>
        /// <returns>Saved ProductMediaDTO with blob properties populated</returns>
        public async virtual Task<ProductMediaDTO> SaveProductMediaAndReturnDTO(ProductMediaDTO saveDTO, bool authorizeUpdate, bool authorizeInsert)
        {
            return await _deps.Context.WithTransactionAsync(async () =>
            {
                var poco = await SaveProductMedia(saveDTO, authorizeUpdate, authorizeInsert);

                var dto = poco.Adapt<ProductMediaDTO>(Mapper.ProductMediaToDTOConfig());

                    if (!string.IsNullOrEmpty(dto.Url))
                    {
                        dto.UrlData = dto.Url;
                    }
                    if (!string.IsNullOrEmpty(dto.ThumbnailUrl))
                    {
                        dto.ThumbnailUrlData = dto.ThumbnailUrl;
                    }
                    if (!string.IsNullOrEmpty(dto.HtmlDescription))
                    {
                        dto.HtmlDescriptionData = dto.HtmlDescription;
                    }

                return dto;
            });
        }

        /// <summary>
        /// Core save method that handles both insert and update operations for ProductMedia.
        /// Validates the DTO, maps to entity, handles many-to-one relationships, and manages blob deletion.
        /// </summary>
        /// <param name="dto">The DTO containing entity data to save</param>
        /// <param name="authorizeUpdate">Whether to perform authorization check for Update operation</param>
        /// <param name="authorizeInsert">Whether to perform authorization check for Insert operation</param>
        /// <returns>Saved ProductMedia entity</returns>
        public async virtual Task<ProductMedia> SaveProductMedia(ProductMediaDTO dto, bool authorizeUpdate, bool authorizeInsert)
        {
            ProductMediaDTOValidationRules validationRules = new ProductMediaDTOValidationRules();
            validationRules.ValidateAndThrow(dto);

            ProductMedia poco = null!;
            await _deps.Context.WithTransactionAsync(async () =>
            {
                await OnBeforeProductMediaIsMapped(dto);
                DbSet<ProductMedia> dbSet = _deps.Context.DbSet<ProductMedia>();

                if (dto.Id > 0)
                {
                    if (authorizeUpdate)
                    {
                        await _deps.AuthorizationService.AuthorizeProductMediaUpdateAndThrow(dto);
                    }

                    poco = await GetInstanceAsync<ProductMedia, long>(dto.Id, dto.Version);
                    await OnBeforeProductMediaUpdate(poco, dto);
                    dto.Adapt(poco, Mapper.ProductMediaDTOToEntityConfig());
                    dbSet.Update(poco);
                }
                else
                {
                    if (authorizeInsert)
                    {
                        await _deps.AuthorizationService.AuthorizeProductMediaInsertAndThrow(dto);
                    }

                    poco = dto.Adapt<ProductMedia>(Mapper.ProductMediaDTOToEntityConfig());
                    await OnBeforeProductMediaInsert(poco, dto);
                    await dbSet.AddAsync(poco);
                }



                await _deps.Context.SaveChangesAsync();

                bool anyBlobMoved = false;
                if (!string.IsNullOrEmpty(poco.Url))
                {
                    string movedUrl = await _s3PublicStorageService.MoveBlobToEntityPathAsync(poco.Url, "products", poco.Id.ToString(), () => GetBlobDescriptiveNameForUrlOfProductMedia(poco.Id));
                    if (movedUrl != poco.Url)
                    {
                        poco.Url = movedUrl;
                        dto.Url = movedUrl;
                        anyBlobMoved = true;
                    }
                }
                if (!string.IsNullOrEmpty(poco.ThumbnailUrl))
                {
                    string movedThumbnailUrl = await _s3PublicStorageService.MoveBlobToEntityPathAsync(poco.ThumbnailUrl, nameof(ProductMedia) + "/" + nameof(ProductMedia.ThumbnailUrl), poco.Id.ToString(), () => GetBlobDescriptiveNameForThumbnailUrlOfProductMedia(poco.Id));
                    if (movedThumbnailUrl != poco.ThumbnailUrl)
                    {
                        poco.ThumbnailUrl = movedThumbnailUrl;
                        dto.ThumbnailUrl = movedThumbnailUrl;
                        anyBlobMoved = true;
                    }
                }
                if (!string.IsNullOrEmpty(poco.HtmlDescription))
                {
                    string movedHtmlDescription = await _s3PublicStorageService.MoveBlobToEntityPathAsync(poco.HtmlDescription, nameof(ProductMedia) + "/" + nameof(ProductMedia.HtmlDescription), poco.Id.ToString(), () => GetBlobDescriptiveNameForHtmlDescriptionOfProductMedia(poco.Id));
                    if (movedHtmlDescription != poco.HtmlDescription)
                    {
                        poco.HtmlDescription = movedHtmlDescription;
                        dto.HtmlDescription = movedHtmlDescription;
                        anyBlobMoved = true;
                    }
                }
                if (anyBlobMoved) await _deps.Context.SaveChangesAsync();

                await _s3PublicStorageService.DeleteNonActiveBlobs(dto.Url, "products", poco.Id.ToString());
                await _s3PublicStorageService.DeleteNonActiveBlobs(dto.ThumbnailUrl, nameof(ProductMedia) + "/" + nameof(ProductMedia.ThumbnailUrl), poco.Id.ToString());
                await _s3PublicStorageService.DeleteNonActiveBlobs(dto.HtmlDescription, nameof(ProductMedia) + "/" + nameof(ProductMedia.HtmlDescription), poco.Id.ToString());

                List<string> activeHtmlDescriptionImageUrls = Helper.ExtractImageUrlsFromHtml(dto.HtmlDescription);
                await _s3PublicStorageService.DeleteNonActiveEditorImages(activeHtmlDescriptionImageUrls, "products-description", poco.Id.ToString());
            });

            return poco;
        }

        /// <summary>
        /// Lifecycle hook called before the ProductMediaDTO is mapped to the entity.
        /// Override this method to add custom validation or modify the DTO before mapping.
        /// This method runs inside a database transaction.
        /// </summary>
        /// <param name="productMediaDTO">The DTO about to be mapped</param>
        protected virtual Task OnBeforeProductMediaIsMapped(ProductMediaDTO productMediaDTO) => Task.CompletedTask;

        /// <summary>
        /// Lifecycle hook called before updating an existing ProductMedia entity.
        /// Override this method to add custom business logic during updates.
        /// This method runs inside a database transaction.
        /// </summary>
        /// <param name="productMedia">The existing entity being updated</param>
        /// <param name="productMediaDTO">The DTO containing new data</param>
        protected virtual Task OnBeforeProductMediaUpdate(ProductMedia productMedia, ProductMediaDTO productMediaDTO) => Task.CompletedTask;

        /// <summary>
        /// Lifecycle hook called before inserting a new ProductMedia entity.
        /// Override this method to add custom business logic during inserts.
        /// This method runs inside a database transaction.
        /// </summary>
        /// <param name="productMedia">The new entity being inserted</param>
        /// <param name="productMediaDTO">The DTO containing the data</param>
        protected virtual Task OnBeforeProductMediaInsert(ProductMedia productMedia, ProductMediaDTO productMediaDTO) => Task.CompletedTask;

        /// <summary>
        /// Uploads a blob/file for the Url property of ProductMedia.
        /// Automatically optimizes images before upload. The entity ID is extracted from the filename.
        /// </summary>
        /// <param name="file">The file to upload</param>
        /// <param name="authorizeUpdate">Whether to perform authorization check for Update operation</param>
        /// <param name="authorizeInsert">Whether to perform authorization check for Insert operation</param>
        /// <returns>The filename in storage</returns>
        public virtual async Task<string> UploadUrlForProductMedia(IFormFile file, bool authorizeUpdate, bool authorizeInsert)
        {
            long id = Helper.GetObjectIdFromFileName<long>(file.FileName);

            await OnBeforeUrlBlobForProductMediaUploadIsAuthorized(file, id);

            if (id > 0 && authorizeUpdate)
            {
                await _deps.AuthorizationService.AuthorizeUrlForProductMediaUpdateAndThrow(id);
            }
            else if (authorizeInsert)
            {
                await _deps.AuthorizationService.AuthorizeUrlForProductMediaInsertAndThrow();
            }

            Helper.ValidateFileSize(file.Length, 20000000, _deps.Localizer);

            using (Stream signatureStream = file.OpenReadStream())
            {
                await Helper.ValidateFileSignature(signatureStream, file.ContentType, new[] { "image/*" }, _deps.Localizer);
            }
            string fileName;
            string descriptiveName = id > 0 ? await GetBlobDescriptiveNameForUrlOfProductMedia(id) : string.Empty;

            using (Stream stream = file.OpenReadStream())
            {
                byte[] byteArray = await OnBeforeUrlBlobForProductMediaIsUploaded(stream, file, id);

                // The optimize hook may have transcoded the bytes (rasters -> WebP by default), and the
                // storage key's extension + Content-Type are derived from this name.
                string uploadFileName = Helper.AlignExtensionWithContent(file.FileName, byteArray);

                using (Stream updatedStream = new MemoryStream(byteArray))
                {
                    fileName = await _s3PublicStorageService.UploadFileAsync(uploadFileName, "products", id.ToString(), updatedStream, descriptiveName);
                }
            }

            return fileName;
        }

        /// <summary>
        /// Optional descriptive name for blobs uploaded to the Url property. When it returns a
        /// non-empty value, the value is slugified and becomes the human/SEO-readable part of the storage
        /// key (<c>{prefix}/{id}/{slug}-{suffix}.{ext}</c>); the default (empty) keeps the GUID-only key.
        /// Called with the owning entity's id on direct upload (id &gt; 0) and lazily at staged-blob
        /// promotion — typically overridden to return the entity's (or its parent's) slug or display name.
        /// </summary>
        /// <example>
        /// <code>
        /// public override async Task&lt;string&gt; GetBlobDescriptiveNameForUrlOfProductMedia(long id) =>
        ///     await _context.DbSet&lt;ProductMedia&gt;().Where(x => x.Id == id).Select(x => x.Name).SingleAsync();
        /// </code>
        /// </example>
        public virtual Task<string> GetBlobDescriptiveNameForUrlOfProductMedia(long id) => Task.FromResult(string.Empty);

        /// <summary>
        /// Lifecycle hook called before blob upload is authorized.
        /// Override this to add custom validation logic before authorization.
        /// </summary>
        /// <param name="file">The file being uploaded</param>
        /// <param name="id">The entity ID</param>
        public virtual Task OnBeforeUrlBlobForProductMediaUploadIsAuthorized (IFormFile file, long id) => Task.CompletedTask;

        /// <summary>
        /// Lifecycle hook called before blob is uploaded to storage.
        /// Default implementation validates and optimizes images. Override to customize file processing.
        /// </summary>
        /// <param name="stream">The file stream</param>
        /// <param name="file">The form file</param>
        /// <param name="id">The entity ID</param>
        /// <returns>Processed file bytes</returns>
        public virtual async Task<byte[]> OnBeforeUrlBlobForProductMediaIsUploaded (Stream stream, IFormFile file, long id)
        {
            if (Helper.IsOptimizableImage(file.ContentType)) // rasters only — SVG can't go through ImageSharp, it passes through raw
            {
                await ValidateImageForUrlOfProductMedia(stream, file, id);
                stream.Position = 0;
                return await OptimizeImageForUrlOfProductMedia(stream, file, id);
            }
            else
            {
                return await Helper.ReadAllBytesAsync(stream);
            }
        }

        /// <summary>
        /// Validates image dimensions and other constraints for the Url property.
        /// Override to customize validation logic (e.g., different dimension requirements, aspect ratio checks).
        /// </summary>
        /// <param name="stream">The image stream</param>
        /// <param name="file">The form file</param>
        /// <param name="id">The entity ID</param>
        public virtual Task ValidateImageForUrlOfProductMedia(Stream stream, IFormFile file, long id) => Task.CompletedTask;

        /// <summary>
        /// Optimizes the image for the Url property.
        /// Override to customize optimization (e.g., different quality, resizing, format conversion).
        /// </summary>
        /// <param name="stream">The image stream</param>
        /// <param name="file">The form file</param>
        /// <param name="id">The entity ID</param>
        /// <returns>Optimized image bytes</returns>
        public virtual async Task<byte[]> OptimizeImageForUrlOfProductMedia(Stream stream, IFormFile file, long id)
        {
            return await Helper.OptimizeImage(stream);
        }

        /// <summary>
        /// Uploads a blob/file for the ThumbnailUrl property of ProductMedia.
        /// Automatically optimizes images before upload. The entity ID is extracted from the filename.
        /// </summary>
        /// <param name="file">The file to upload</param>
        /// <param name="authorizeUpdate">Whether to perform authorization check for Update operation</param>
        /// <param name="authorizeInsert">Whether to perform authorization check for Insert operation</param>
        /// <returns>The filename in storage</returns>
        public virtual async Task<string> UploadThumbnailUrlForProductMedia(IFormFile file, bool authorizeUpdate, bool authorizeInsert)
        {
            long id = Helper.GetObjectIdFromFileName<long>(file.FileName);

            await OnBeforeThumbnailUrlBlobForProductMediaUploadIsAuthorized(file, id);

            if (id > 0 && authorizeUpdate)
            {
                await _deps.AuthorizationService.AuthorizeThumbnailUrlForProductMediaUpdateAndThrow(id);
            }
            else if (authorizeInsert)
            {
                await _deps.AuthorizationService.AuthorizeThumbnailUrlForProductMediaInsertAndThrow();
            }

            Helper.ValidateFileSize(file.Length, 20000000, _deps.Localizer);

            using (Stream signatureStream = file.OpenReadStream())
            {
                await Helper.ValidateFileSignature(signatureStream, file.ContentType, new[] { "image/*" }, _deps.Localizer);
            }
            string fileName;
            string descriptiveName = id > 0 ? await GetBlobDescriptiveNameForThumbnailUrlOfProductMedia(id) : string.Empty;

            using (Stream stream = file.OpenReadStream())
            {
                byte[] byteArray = await OnBeforeThumbnailUrlBlobForProductMediaIsUploaded(stream, file, id);

                // The optimize hook may have transcoded the bytes (rasters -> WebP by default), and the
                // storage key's extension + Content-Type are derived from this name.
                string uploadFileName = Helper.AlignExtensionWithContent(file.FileName, byteArray);

                using (Stream updatedStream = new MemoryStream(byteArray))
                {
                    fileName = await _s3PublicStorageService.UploadFileAsync(uploadFileName, nameof(ProductMedia) + "/" + nameof(ProductMedia.ThumbnailUrl), id.ToString(), updatedStream, descriptiveName);
                }
            }

            return fileName;
        }

        /// <summary>
        /// Optional descriptive name for blobs uploaded to the ThumbnailUrl property. When it returns a
        /// non-empty value, the value is slugified and becomes the human/SEO-readable part of the storage
        /// key (<c>{prefix}/{id}/{slug}-{suffix}.{ext}</c>); the default (empty) keeps the GUID-only key.
        /// Called with the owning entity's id on direct upload (id &gt; 0) and lazily at staged-blob
        /// promotion — typically overridden to return the entity's (or its parent's) slug or display name.
        /// </summary>
        /// <example>
        /// <code>
        /// public override async Task&lt;string&gt; GetBlobDescriptiveNameForThumbnailUrlOfProductMedia(long id) =>
        ///     await _context.DbSet&lt;ProductMedia&gt;().Where(x => x.Id == id).Select(x => x.Name).SingleAsync();
        /// </code>
        /// </example>
        public virtual Task<string> GetBlobDescriptiveNameForThumbnailUrlOfProductMedia(long id) => Task.FromResult(string.Empty);

        /// <summary>
        /// Lifecycle hook called before blob upload is authorized.
        /// Override this to add custom validation logic before authorization.
        /// </summary>
        /// <param name="file">The file being uploaded</param>
        /// <param name="id">The entity ID</param>
        public virtual Task OnBeforeThumbnailUrlBlobForProductMediaUploadIsAuthorized (IFormFile file, long id) => Task.CompletedTask;

        /// <summary>
        /// Lifecycle hook called before blob is uploaded to storage.
        /// Default implementation validates and optimizes images. Override to customize file processing.
        /// </summary>
        /// <param name="stream">The file stream</param>
        /// <param name="file">The form file</param>
        /// <param name="id">The entity ID</param>
        /// <returns>Processed file bytes</returns>
        public virtual async Task<byte[]> OnBeforeThumbnailUrlBlobForProductMediaIsUploaded (Stream stream, IFormFile file, long id)
        {
            if (Helper.IsOptimizableImage(file.ContentType)) // rasters only — SVG can't go through ImageSharp, it passes through raw
            {
                await ValidateImageForThumbnailUrlOfProductMedia(stream, file, id);
                stream.Position = 0;
                return await OptimizeImageForThumbnailUrlOfProductMedia(stream, file, id);
            }
            else
            {
                return await Helper.ReadAllBytesAsync(stream);
            }
        }

        /// <summary>
        /// Validates image dimensions and other constraints for the ThumbnailUrl property.
        /// Override to customize validation logic (e.g., different dimension requirements, aspect ratio checks).
        /// </summary>
        /// <param name="stream">The image stream</param>
        /// <param name="file">The form file</param>
        /// <param name="id">The entity ID</param>
        public virtual Task ValidateImageForThumbnailUrlOfProductMedia(Stream stream, IFormFile file, long id) => Task.CompletedTask;

        /// <summary>
        /// Optimizes the image for the ThumbnailUrl property.
        /// Override to customize optimization (e.g., different quality, resizing, format conversion).
        /// </summary>
        /// <param name="stream">The image stream</param>
        /// <param name="file">The form file</param>
        /// <param name="id">The entity ID</param>
        /// <returns>Optimized image bytes</returns>
        public virtual async Task<byte[]> OptimizeImageForThumbnailUrlOfProductMedia(Stream stream, IFormFile file, long id)
        {
            return await Helper.OptimizeImage(stream);
        }

        /// <summary>
        /// Uploads a blob/file for the HtmlDescription property of ProductMedia.
        /// Automatically optimizes images before upload. The entity ID is extracted from the filename.
        /// </summary>
        /// <param name="file">The file to upload</param>
        /// <param name="authorizeUpdate">Whether to perform authorization check for Update operation</param>
        /// <param name="authorizeInsert">Whether to perform authorization check for Insert operation</param>
        /// <returns>The filename in storage</returns>
        public virtual async Task<string> UploadHtmlDescriptionForProductMedia(IFormFile file, bool authorizeUpdate, bool authorizeInsert)
        {
            long id = Helper.GetObjectIdFromFileName<long>(file.FileName);

            await OnBeforeHtmlDescriptionBlobForProductMediaUploadIsAuthorized(file, id);

            if (id > 0 && authorizeUpdate)
            {
                await _deps.AuthorizationService.AuthorizeHtmlDescriptionForProductMediaUpdateAndThrow(id);
            }
            else if (authorizeInsert)
            {
                await _deps.AuthorizationService.AuthorizeHtmlDescriptionForProductMediaInsertAndThrow();
            }

            Helper.ValidateFileSize(file.Length, 20000000, _deps.Localizer);

            using (Stream signatureStream = file.OpenReadStream())
            {
                await Helper.ValidateFileSignature(signatureStream, file.ContentType, new[] { "image/*" }, _deps.Localizer);
            }
            string fileName;
            string descriptiveName = id > 0 ? await GetBlobDescriptiveNameForHtmlDescriptionOfProductMedia(id) : string.Empty;

            using (Stream stream = file.OpenReadStream())
            {
                byte[] byteArray = await OnBeforeHtmlDescriptionBlobForProductMediaIsUploaded(stream, file, id);

                // The optimize hook may have transcoded the bytes (rasters -> WebP by default), and the
                // storage key's extension + Content-Type are derived from this name.
                string uploadFileName = Helper.AlignExtensionWithContent(file.FileName, byteArray);

                using (Stream updatedStream = new MemoryStream(byteArray))
                {
                    fileName = await _s3PublicStorageService.UploadFileAsync(uploadFileName, nameof(ProductMedia) + "/" + nameof(ProductMedia.HtmlDescription), id.ToString(), updatedStream, descriptiveName);
                }
            }

            return fileName;
        }

        /// <summary>
        /// Optional descriptive name for blobs uploaded to the HtmlDescription property. When it returns a
        /// non-empty value, the value is slugified and becomes the human/SEO-readable part of the storage
        /// key (<c>{prefix}/{id}/{slug}-{suffix}.{ext}</c>); the default (empty) keeps the GUID-only key.
        /// Called with the owning entity's id on direct upload (id &gt; 0) and lazily at staged-blob
        /// promotion — typically overridden to return the entity's (or its parent's) slug or display name.
        /// </summary>
        /// <example>
        /// <code>
        /// public override async Task&lt;string&gt; GetBlobDescriptiveNameForHtmlDescriptionOfProductMedia(long id) =>
        ///     await _context.DbSet&lt;ProductMedia&gt;().Where(x => x.Id == id).Select(x => x.Name).SingleAsync();
        /// </code>
        /// </example>
        public virtual Task<string> GetBlobDescriptiveNameForHtmlDescriptionOfProductMedia(long id) => Task.FromResult(string.Empty);

        /// <summary>
        /// Lifecycle hook called before blob upload is authorized.
        /// Override this to add custom validation logic before authorization.
        /// </summary>
        /// <param name="file">The file being uploaded</param>
        /// <param name="id">The entity ID</param>
        public virtual Task OnBeforeHtmlDescriptionBlobForProductMediaUploadIsAuthorized (IFormFile file, long id) => Task.CompletedTask;

        /// <summary>
        /// Lifecycle hook called before blob is uploaded to storage.
        /// Default implementation validates and optimizes images. Override to customize file processing.
        /// </summary>
        /// <param name="stream">The file stream</param>
        /// <param name="file">The form file</param>
        /// <param name="id">The entity ID</param>
        /// <returns>Processed file bytes</returns>
        public virtual async Task<byte[]> OnBeforeHtmlDescriptionBlobForProductMediaIsUploaded (Stream stream, IFormFile file, long id)
        {
            if (Helper.IsOptimizableImage(file.ContentType)) // rasters only — SVG can't go through ImageSharp, it passes through raw
            {
                await ValidateImageForHtmlDescriptionOfProductMedia(stream, file, id);
                stream.Position = 0;
                return await OptimizeImageForHtmlDescriptionOfProductMedia(stream, file, id);
            }
            else
            {
                return await Helper.ReadAllBytesAsync(stream);
            }
        }

        /// <summary>
        /// Validates image dimensions and other constraints for the HtmlDescription property.
        /// Override to customize validation logic (e.g., different dimension requirements, aspect ratio checks).
        /// </summary>
        /// <param name="stream">The image stream</param>
        /// <param name="file">The form file</param>
        /// <param name="id">The entity ID</param>
        public virtual Task ValidateImageForHtmlDescriptionOfProductMedia(Stream stream, IFormFile file, long id) => Task.CompletedTask;

        /// <summary>
        /// Optimizes the image for the HtmlDescription property.
        /// Override to customize optimization (e.g., different quality, resizing, format conversion).
        /// </summary>
        /// <param name="stream">The image stream</param>
        /// <param name="file">The form file</param>
        /// <param name="id">The entity ID</param>
        /// <returns>Optimized image bytes</returns>
        public virtual async Task<byte[]> OptimizeImageForHtmlDescriptionOfProductMedia(Stream stream, IFormFile file, long id)
        {
            return await Helper.OptimizeImage(stream);
        }

        public virtual async Task<EditorImageUploadResultDTO> UploadHtmlDescriptionImageForProductMedia(IFormFile file, bool authorizeUpdate, bool authorizeInsert)
        {
            long id = Helper.GetObjectIdFromFileName<long>(file.FileName);

            if (id > 0 && authorizeUpdate)
            {
                await _deps.AuthorizationService.AuthorizeHtmlDescriptionImageForProductMediaUpdateAndThrow(id);
            }
            else if (authorizeInsert)
            {
                await _deps.AuthorizationService.AuthorizeHtmlDescriptionImageForProductMediaInsertAndThrow();
            }

            Helper.ValidateFileSize(file.Length, 20000000, _deps.Localizer);

            using (Stream signatureStream = file.OpenReadStream())
            {
                await Helper.ValidateFileSignature(signatureStream, file.ContentType, new[] { "image/*" }, _deps.Localizer);
            }
            string imageUrl;
            int imageWidth;
            int imageHeight;
            string descriptiveName = id > 0 ? await GetBlobDescriptiveNameForHtmlDescriptionOfProductMedia(id) : string.Empty;

            using (Stream stream = file.OpenReadStream())
            {
                byte[] byteArray;

                if (Helper.IsOptimizableImage(file.ContentType))
                {
                    (byteArray, imageWidth, imageHeight) = await Helper.OptimizeImageWithDimensions(stream);
                }
                else
                {
                    // SVG: no ImageSharp decode — upload as-is; intrinsic size best-effort (0,0 when unknown)
                    (imageWidth, imageHeight) = Helper.GetSvgDimensions(stream);
                    byteArray = await Helper.ReadAllBytesAsync(stream);
                }

                // Rasters were just transcoded to WebP — the key's extension + Content-Type follow the bytes.
                string uploadFileName = Helper.AlignExtensionWithContent(file.FileName, byteArray);

                using (Stream updatedStream = new MemoryStream(byteArray))
                {
                    imageUrl = await _s3PublicStorageService.UploadFileAsync(uploadFileName, "products-description", id.ToString(), updatedStream, descriptiveName);
                }
            }

            return new EditorImageUploadResultDTO
            {
                Url = imageUrl,
                Width = imageWidth,
                Height = imageHeight,
            };
        }

        #endregion

        #region Delete

        /// <summary>
        /// Per-id variant of the pre-delete hook. By default forwards to
        /// <see cref="OnBeforeProductMediaListDelete"/> with a one-element list, so override
        /// only the list hook unless single-id and batch flows genuinely diverge.
        /// </summary>
        /// <param name="id">The ID of the entity being deleted</param>
        public virtual Task OnBeforeProductMediaDelete(long id) =>
            OnBeforeProductMediaListDelete(id.StructToList());

        /// <summary>
        /// Per-id variant of the post-delete hook. By default forwards to
        /// <see cref="OnAfterProductMediaListDelete"/> with a one-element list, so override
        /// only the list hook unless single-id and batch flows genuinely diverge.
        /// </summary>
        /// <param name="id">The ID of the entity that was deleted</param>
        public virtual Task OnAfterProductMediaDelete(long id) =>
            OnAfterProductMediaListDelete(id.StructToList());

        /// <summary>
        /// Deletes a single ProductMedia entity with cascade delete handling for dependent entities.
        /// </summary>
        /// <param name="id">The ID of the entity to delete</param>
        public async virtual Task DeleteProductMedia(long id)
        {
            await _deps.Context.WithTransactionAsync(async () =>
            {
                await OnBeforeProductMediaDelete(id);

                // Persist writes the hook staged (e.g. IOutbox.Enqueue) as part of this
                // transaction; the next step (untracked cascade delete, or the commit) won't
                // flush them and WithTransactionAsync's clean-tracker guard would throw.
                if (_deps.Context.ChangeTracker.HasChanges())
                    await _deps.Context.SaveChangesAsync();

                List<long> listForDelete_1 = id.StructToList();



                await DeleteEntityAsync<ProductMedia, long>(id);

                await OnAfterProductMediaDelete(id);

                // Persist writes the hook staged (e.g. IOutbox.Enqueue) as part of this
                // transaction; the next step (untracked cascade delete, or the commit) won't
                // flush them and WithTransactionAsync's clean-tracker guard would throw.
                if (_deps.Context.ChangeTracker.HasChanges())
                    await _deps.Context.SaveChangesAsync();
            });
        }

        /// <summary>
        /// Lifecycle hook called before deleting a list of ProductMedia entities.
        /// Override this to add custom validation or business logic before batch deletion.
        /// </summary>
        /// <param name="listForDelete">The list of entity IDs being deleted</param>
        public virtual Task OnBeforeProductMediaListDelete(List<long> listForDelete) => Task.CompletedTask;

        /// <summary>
        /// Lifecycle hook called after deleting a list of ProductMedia entities (cascades included),
        /// still inside the delete transaction — queries observe the post-delete state, and anything
        /// written here commits or rolls back atomically with the delete.
        /// Override this to recompute denormalized aggregates or stage post-delete work.
        /// </summary>
        /// <param name="deletedIds">The list of entity IDs that were deleted</param>
        /// <example>
        /// public override async Task OnAfterProductMediaListDelete(List&lt;long&gt; deletedIds)
        /// {
        ///     await RecalculateAggregatesAsync(); // reads the post-delete state
        /// }
        /// </example>
        public virtual Task OnAfterProductMediaListDelete(List<long> deletedIds) => Task.CompletedTask;

        /// <summary>
        /// Deletes multiple ProductMedia entities with cascade delete handling for dependent entities.
        /// </summary>
        /// <param name="listForDelete_1">The list of entity IDs to delete</param>
        public async virtual Task DeleteProductMediaList(List<long> listForDelete_1)
        {
            await _deps.Context.WithTransactionAsync(async () =>
            {
                await OnBeforeProductMediaListDelete(listForDelete_1);

                // Persist writes the hook staged (e.g. IOutbox.Enqueue) as part of this
                // transaction; the next step (untracked cascade delete, or the commit) won't
                // flush them and WithTransactionAsync's clean-tracker guard would throw.
                if (_deps.Context.ChangeTracker.HasChanges())
                    await _deps.Context.SaveChangesAsync();



                await DeleteEntitiesAsync<ProductMedia, long>(listForDelete_1);

                await OnAfterProductMediaListDelete(listForDelete_1);

                // Persist writes the hook staged (e.g. IOutbox.Enqueue) as part of this
                // transaction; the next step (untracked cascade delete, or the commit) won't
                // flush them and WithTransactionAsync's clean-tracker guard would throw.
                if (_deps.Context.ChangeTracker.HasChanges())
                    await _deps.Context.SaveChangesAsync();
            });
        }

        #endregion

        #region One To Many



        #endregion

    }
}