//HintName: BannerService.generated.cs
// <auto-generated/>
#nullable disable

using TestApp.Business.ValidationRules;
using TestApp.Business.DataMappers;
using TestApp.Business.DTO;
using TestApp.Business.Entities;
using TestApp.Business.Enums;
using TestApp.Business.ExcelProperties;
using TestApp.Business.Filtering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Localization;
using System.Data;
using FluentValidation;
using Spiderly.Security.Services;
using Spiderly.Security.Interfaces;
using Spiderly.Shared.Excel;
using Spiderly.Shared.Interfaces;
using Spiderly.Shared.Services;
using Spiderly.Shared.Classes;
using Spiderly.Shared.DTO;
using Spiderly.Shared.Extensions;
using Spiderly.Shared.Exceptions;
using Spiderly.Shared.Helpers;
using Mapster;
using Microsoft.AspNetCore.Http;

namespace TestApp.Business.Services
{
    /// <summary>
    /// Generated service for the Banner entity. Override lifecycle hooks
    /// by creating a <c>BannerService</c> class that inherits from this class.
    /// </summary>
    public class BannerServiceGenerated : ServiceBase
    {
        protected readonly EntityServiceDependencies _deps;
        private readonly S3PublicStorageService _s3PublicStorageService;


        public BannerServiceGenerated(EntityServiceDependencies deps) : base(deps.Context, deps.Localizer)
        {
            _deps = deps;
            _s3PublicStorageService = deps.ServiceProvider.GetRequiredService<S3PublicStorageService>();

        }

        #region Read

        /// <summary>
        /// Retrieves the complete MainUIFormDTO for Banner, including the entity DTO and all related collections (one-to-many, many-to-many).
        /// </summary>
        /// <param name="id">The ID of the Banner entity</param>
        /// <returns>BannerMainUIFormDTO containing the entity DTO and related data</returns>
        public async virtual Task<BannerMainUIFormDTO> GetBannerMainUIFormDTO(long id)
        {
            return await _deps.Context.WithTransactionAsync(async () =>
            {
                var result = new BannerMainUIFormDTO
                {
                    BannerDTO = await GetBannerDTO(id),
                };

                await OnAfterGetBannerMainUIFormDTO(result);

                return result;
            });
        }

        /// <summary>
        /// Lifecycle hook called after retrieving Banner MainUIFormDTO.
        /// Override this method to enrich the MainUIFormDTO with additional data (e.g., computed fields, extra queries).
        /// This method runs inside a database transaction.
        /// </summary>
        /// <example>
        /// protected override async Task OnAfterGetBannerMainUIFormDTO(BannerMainUIFormDTO mainUIFormDTO)
        /// {
        ///     mainUIFormDTO.CustomProperty = await _deps.Context.DbSet&lt;OtherEntity&gt;().Where(x => x.BannerId == mainUIFormDTO.BannerDTO.Id).CountAsync();
        /// }
        /// </example>
        /// <param name="mainUIFormDTO">The MainUIFormDTO that was just constructed with entity and related data</param>
        protected virtual Task OnAfterGetBannerMainUIFormDTO(BannerMainUIFormDTO mainUIFormDTO) => Task.CompletedTask;

        /// <summary>
        /// Retrieves a single Banner entity as a DTO with blob data populated.
        /// </summary>
        /// <param name="id">The ID of the Banner entity</param>
        /// <returns>BannerDTO with all blob properties populated</returns>
        public async virtual Task<BannerDTO> GetBannerDTO(long id)
        {
            return await _deps.Context.WithTransactionAsync(async () =>
            {
                var dto = await _deps.Context.DbSet<Banner>()
                    .AsNoTracking()
                    .Where(x => x.Id == id).ProjectToType<BannerDTO>(Mapper.BannerProjectToConfig())
                    .SingleOrDefaultAsync();

                if (dto == null)
                    throw new BusinessException(_deps.Localizer["EntityDoesNotExistInDatabase"]);

                    if (!string.IsNullOrEmpty(dto.SnapshottedUrl))
                    {
                        dto.SnapshottedUrlData = dto.SnapshottedUrl;
                    }
                    if (!string.IsNullOrEmpty(dto.LogoUrl))
                    {
                        dto.LogoUrlData = dto.LogoUrl;
                    }

                return dto;
            });
        }

        /// <summary>
        /// Retrieves a paginated list of Banner entities.
        /// </summary>
        /// <param name="filterDTO">Filter and pagination parameters</param>
        /// <param name="query">The base query to paginate</param>
        /// <returns>PaginatedResult containing the query and total record count</returns>
        public async virtual Task<PaginatedResult<Banner>> GetPaginatedBannerResult(FilterDTO filterDTO, IQueryable<Banner> query)
        {
            return await _deps.Context.WithTransactionAsync(async () =>
            {
                return await PaginatedResultGenerator.Build(query.AsNoTracking(), filterDTO);
            });
        }

        /// <summary>
        /// Retrieves a paginated list of Banner DTOs with blob data populated.
        /// </summary>
        /// <param name="filterDTO">Filter and pagination parameters</param>
        /// <param name="query">The base query to paginate</param>
        /// <returns>PaginatedResultDTO containing BannerDTO list and total record count</returns>
        public async virtual Task<PaginatedResultDTO<BannerDTO>> GetPaginatedBannerList(FilterDTO filterDTO, IQueryable<Banner> query)
        {
            PaginatedResult<Banner> paginationResult = new();
            List<BannerDTO> dtoList = null!;

            await _deps.Context.WithTransactionAsync(async () =>
            {
                paginationResult = await GetPaginatedBannerResult(filterDTO, query);

                dtoList = await paginationResult.Query
                    .Skip(filterDTO.First)
                    .Take(filterDTO.Rows)
                    .ProjectToType<BannerDTO>(Mapper.BannerProjectToConfig())
                    .ToListAsync();

                foreach (var dto in dtoList)
                {
                    if (!string.IsNullOrEmpty(dto.SnapshottedUrl))
                    {
                        dto.SnapshottedUrlData = dto.SnapshottedUrl;
                    }
                    if (!string.IsNullOrEmpty(dto.LogoUrl))
                    {
                        dto.LogoUrlData = dto.LogoUrl;
                    }
                }
            });

            return new PaginatedResultDTO<BannerDTO> { Data = dtoList, TotalRecords = paginationResult.TotalRecords };
        }

        /// <summary>
        /// Exports a filtered list of Banner entities to Excel format.
        /// </summary>
        /// <param name="filterDTO">Filter parameters for the export</param>
        /// <param name="query">The base query to export</param>
        /// <param name="cancellationToken">Cancellation token</param>
        /// <returns>Excel file as byte array</returns>
        public async virtual Task<byte[]> ExportBannerListToExcel(FilterDTO filterDTO, IQueryable<Banner> query, CancellationToken cancellationToken = default)
        {
            IQueryable<BannerDTO> exportQuery = null!;

            await _deps.Context.WithTransactionAsync(async () =>
            {
                PaginatedResult<Banner> paginationResult = await GetPaginatedBannerResult(filterDTO, query);
                int maxRows = _deps.ExcelSettings.ExcelExportMaxRows;
                exportQuery = paginationResult.Query
                    .OrderBy(x => x.Id)
                    .Take(maxRows)
                    .ProjectToType<BannerDTO>(Mapper.BannerExcelProjectToConfig());
            });

            string[] excelPropertiesToExclude = ExcelPropertiesToExclude.GetHeadersToExclude(new BannerDTO());
            return await _deps.ExcelService.FillReportTemplateAsync(
                exportQuery.AsAsyncEnumerable(),
                excelPropertiesToExclude,
                _deps.Localizer,
                cancellationToken);
        }

        /// <summary>
        /// Retrieves a list of Banner entities without pagination.
        /// </summary>
        /// <param name="query">The query to execute</param>
        /// <returns>List of Banner entities</returns>
        public async virtual Task<List<Banner>> GetBannerList(IQueryable<Banner> query)
        {
            return await _deps.Context.WithTransactionAsync(async () =>
            {
                var result = await query
                    .ToListAsync();

                return result;
            });
        }

        /// <summary>
        /// Retrieves a list of Banner DTOs without pagination, with blob data populated.
        /// </summary>
        /// <param name="query">The query to execute</param>
        /// <returns>List of BannerDTO with blob properties populated</returns>
        public async virtual Task<List<BannerDTO>> GetBannerDTOList(IQueryable<Banner> query)
        {
            return await _deps.Context.WithTransactionAsync(async () =>
            {
                var dtoList = await query
                    .AsNoTracking()
                    .ProjectToType<BannerDTO>(Mapper.BannerToDTOConfig())
                    .ToListAsync();

                foreach (var dto in dtoList)
                {
                    if (!string.IsNullOrEmpty(dto.SnapshottedUrl))
                    {
                        dto.SnapshottedUrlData = dto.SnapshottedUrl;
                    }
                    if (!string.IsNullOrEmpty(dto.LogoUrl))
                    {
                        dto.LogoUrlData = dto.LogoUrl;
                    }
                }

                return dtoList;
            });
        }



        #endregion

        #region Save

        /// <summary>
        /// Saves a Banner entity and returns the complete MainUIFormDTO including all related collections.
        /// Handles insert/update logic, many-to-many relationships, and ordered one-to-many collections.
        /// </summary>
        /// <param name="saveBodyDTO">The SaveBodyDTO containing entity data and related selections</param>
        /// <param name="authorizeUpdate">Whether to perform authorization check for Update operation</param>
        /// <param name="authorizeInsert">Whether to perform authorization check for Insert operation</param>
        /// <returns>BannerMainUIFormDTO with saved data and updated collections</returns>
        public virtual async Task<BannerMainUIFormDTO> SaveBannerAndReturnMainUIFormDTO(BannerSaveBodyDTO saveBodyDTO, bool authorizeUpdate, bool authorizeInsert)
        {
            new BannerSaveBodyDTOValidationRules().ValidateAndThrow(saveBodyDTO);

            return await _deps.Context.WithTransactionAsync(async () =>
            {
                await OnBeforeSaveBannerAndReturnMainUIFormDTO(saveBodyDTO);

                var savedDTO = await SaveBannerAndReturnDTO(saveBodyDTO.BannerDTO!, authorizeUpdate, authorizeInsert);






                var result = new BannerMainUIFormDTO
                {
                    BannerDTO = savedDTO,



                };

                await OnAfterSaveBannerAndReturnMainUIFormDTO(saveBodyDTO, result);

                return result;
            });
        }




        /// <summary>
        /// Lifecycle hook called before saving Banner with MainUIFormDTO.
        /// Override this method to add custom validation or modify the SaveBodyDTO.
        /// This method runs inside a database transaction.
        /// </summary>
        /// <param name="saveBodyDTO">The SaveBodyDTO containing entity and related data</param>
        protected virtual Task OnBeforeSaveBannerAndReturnMainUIFormDTO(BannerSaveBodyDTO saveBodyDTO) => Task.CompletedTask;

        /// <summary>
        /// Lifecycle hook called after saving Banner and after updating related collections.
        /// Override this method to add custom business logic after the main entity is saved.
        /// This method runs inside a database transaction.
        /// </summary>
        /// <param name="saveBodyDTO">The original SaveBodyDTO</param>
        /// <param name="mainUIFormDTO">The save result and DTO sent to the UI</param>
        protected virtual Task OnAfterSaveBannerAndReturnMainUIFormDTO(BannerSaveBodyDTO saveBodyDTO, BannerMainUIFormDTO mainUIFormDTO) => Task.CompletedTask;

        /// <summary>
        /// Saves a Banner entity and returns the DTO with blob data populated.
        /// </summary>
        /// <param name="saveDTO">The DTO containing entity data to save</param>
        /// <param name="authorizeUpdate">Whether to perform authorization check for Update operation</param>
        /// <param name="authorizeInsert">Whether to perform authorization check for Insert operation</param>
        /// <returns>Saved BannerDTO with blob properties populated</returns>
        public async virtual Task<BannerDTO> SaveBannerAndReturnDTO(BannerDTO saveDTO, bool authorizeUpdate, bool authorizeInsert)
        {
            return await _deps.Context.WithTransactionAsync(async () =>
            {
                var poco = await SaveBanner(saveDTO, authorizeUpdate, authorizeInsert);

                var dto = poco.Adapt<BannerDTO>(Mapper.BannerToDTOConfig());

                    if (!string.IsNullOrEmpty(dto.SnapshottedUrl))
                    {
                        dto.SnapshottedUrlData = dto.SnapshottedUrl;
                    }
                    if (!string.IsNullOrEmpty(dto.LogoUrl))
                    {
                        dto.LogoUrlData = dto.LogoUrl;
                    }

                return dto;
            });
        }

        /// <summary>
        /// Core save method that handles both insert and update operations for Banner.
        /// Validates the DTO, maps to entity, handles many-to-one relationships, and manages blob deletion.
        /// </summary>
        /// <param name="dto">The DTO containing entity data to save</param>
        /// <param name="authorizeUpdate">Whether to perform authorization check for Update operation</param>
        /// <param name="authorizeInsert">Whether to perform authorization check for Insert operation</param>
        /// <returns>Saved Banner entity</returns>
        public async virtual Task<Banner> SaveBanner(BannerDTO dto, bool authorizeUpdate, bool authorizeInsert)
        {
            BannerDTOValidationRules validationRules = new BannerDTOValidationRules();
            validationRules.ValidateAndThrow(dto);

            Banner poco = null!;
            await _deps.Context.WithTransactionAsync(async () =>
            {
                await OnBeforeBannerIsMapped(dto);
                DbSet<Banner> dbSet = _deps.Context.DbSet<Banner>();

                if (dto.Id > 0)
                {
                    if (authorizeUpdate)
                    {
                        await _deps.AuthorizationService.AuthorizeBannerUpdateAndThrow(dto);
                    }

                    poco = await GetInstanceAsync<Banner, long>(dto.Id, dto.Version);
                    await OnBeforeBannerUpdate(poco, dto);
                    dto.Adapt(poco, Mapper.BannerDTOToEntityConfig());
                    dbSet.Update(poco);
                }
                else
                {
                    if (authorizeInsert)
                    {
                        await _deps.AuthorizationService.AuthorizeBannerInsertAndThrow(dto);
                    }

                    poco = dto.Adapt<Banner>(Mapper.BannerDTOToEntityConfig());
                    await OnBeforeBannerInsert(poco, dto);
                    await dbSet.AddAsync(poco);
                }



                await _deps.Context.SaveChangesAsync();

                bool anyBlobMoved = false;
                if (!string.IsNullOrEmpty(poco.SnapshottedUrl))
                {
                    string movedSnapshottedUrl = await _s3PublicStorageService.MoveBlobToEntityPathAsync(poco.SnapshottedUrl, nameof(Banner) + "/" + nameof(Banner.SnapshottedUrl), poco.Id.ToString(), () => GetBlobDescriptiveNameForSnapshottedUrlOfBanner(poco.Id));
                    if (movedSnapshottedUrl != poco.SnapshottedUrl)
                    {
                        poco.SnapshottedUrl = movedSnapshottedUrl;
                        dto.SnapshottedUrl = movedSnapshottedUrl;
                        anyBlobMoved = true;
                    }
                }
                if (!string.IsNullOrEmpty(poco.LogoUrl))
                {
                    string movedLogoUrl = await _s3PublicStorageService.MoveBlobToEntityPathAsync(poco.LogoUrl, nameof(Banner) + "/" + nameof(Banner.LogoUrl), poco.Id.ToString(), () => GetBlobDescriptiveNameForLogoUrlOfBanner(poco.Id));
                    if (movedLogoUrl != poco.LogoUrl)
                    {
                        poco.LogoUrl = movedLogoUrl;
                        dto.LogoUrl = movedLogoUrl;
                        anyBlobMoved = true;
                    }
                }
                if (anyBlobMoved) await _deps.Context.SaveChangesAsync();

                await _s3PublicStorageService.DeleteNonActiveBlobs(dto.LogoUrl, nameof(Banner) + "/" + nameof(Banner.LogoUrl), poco.Id.ToString());


            });

            return poco;
        }

        /// <summary>
        /// Lifecycle hook called before the BannerDTO is mapped to the entity.
        /// Override this method to add custom validation or modify the DTO before mapping.
        /// This method runs inside a database transaction.
        /// </summary>
        /// <param name="bannerDTO">The DTO about to be mapped</param>
        protected virtual Task OnBeforeBannerIsMapped(BannerDTO bannerDTO) => Task.CompletedTask;

        /// <summary>
        /// Lifecycle hook called before updating an existing Banner entity.
        /// Override this method to add custom business logic during updates.
        /// This method runs inside a database transaction.
        /// </summary>
        /// <param name="banner">The existing entity being updated</param>
        /// <param name="bannerDTO">The DTO containing new data</param>
        protected virtual Task OnBeforeBannerUpdate(Banner banner, BannerDTO bannerDTO) => Task.CompletedTask;

        /// <summary>
        /// Lifecycle hook called before inserting a new Banner entity.
        /// Override this method to add custom business logic during inserts.
        /// This method runs inside a database transaction.
        /// </summary>
        /// <param name="banner">The new entity being inserted</param>
        /// <param name="bannerDTO">The DTO containing the data</param>
        protected virtual Task OnBeforeBannerInsert(Banner banner, BannerDTO bannerDTO) => Task.CompletedTask;

        /// <summary>
        /// Uploads a blob/file for the SnapshottedUrl property of Banner.
        /// Automatically optimizes images before upload. The entity ID is extracted from the filename.
        /// </summary>
        /// <param name="file">The file to upload</param>
        /// <param name="authorizeUpdate">Whether to perform authorization check for Update operation</param>
        /// <param name="authorizeInsert">Whether to perform authorization check for Insert operation</param>
        /// <returns>The filename in storage</returns>
        public virtual async Task<string> UploadSnapshottedUrlForBanner(IFormFile file, bool authorizeUpdate, bool authorizeInsert)
        {
            long id = Helper.GetObjectIdFromFileName<long>(file.FileName);

            await OnBeforeSnapshottedUrlBlobForBannerUploadIsAuthorized(file, id);

            if (id > 0 && authorizeUpdate)
            {
                await _deps.AuthorizationService.AuthorizeSnapshottedUrlForBannerUpdateAndThrow(id);
            }
            else if (authorizeInsert)
            {
                await _deps.AuthorizationService.AuthorizeSnapshottedUrlForBannerInsertAndThrow();
            }

            Helper.ValidateFileSize(file.Length, 20000000, _deps.Localizer);

            using (Stream signatureStream = file.OpenReadStream())
            {
                await Helper.ValidateFileSignature(signatureStream, file.ContentType, new[] { "image/*" }, _deps.Localizer);
            }
            string fileName;
            string descriptiveName = id > 0 ? await GetBlobDescriptiveNameForSnapshottedUrlOfBanner(id) : string.Empty;

            using (Stream stream = file.OpenReadStream())
            {
                byte[] byteArray = await OnBeforeSnapshottedUrlBlobForBannerIsUploaded(stream, file, id);

                // The optimize hook may have transcoded the bytes (rasters -> WebP by default), and the
                // storage key's extension + Content-Type are derived from this name.
                string uploadFileName = Helper.AlignExtensionWithContent(file.FileName, byteArray, file.ContentType);

                using (Stream updatedStream = new MemoryStream(byteArray))
                {
                    fileName = await _s3PublicStorageService.UploadFileAsync(uploadFileName, nameof(Banner) + "/" + nameof(Banner.SnapshottedUrl), id.ToString(), updatedStream, descriptiveName);
                }
            }

            return fileName;
        }

        /// <summary>
        /// Optional descriptive name for blobs uploaded to the SnapshottedUrl property. When it returns a
        /// non-empty value, the value is slugified and becomes the human/SEO-readable part of the storage
        /// key (<c>{prefix}/{id}/{slug}-{suffix}.{ext}</c>); the default (empty) keeps the GUID-only key.
        /// Called with the owning entity's id on direct upload (id &gt; 0) and lazily at staged-blob
        /// promotion — typically overridden to return the entity's (or its parent's) slug or display name.
        /// </summary>
        /// <example>
        /// <code>
        /// public override async Task&lt;string&gt; GetBlobDescriptiveNameForSnapshottedUrlOfBanner(long id) =>
        ///     await _context.DbSet&lt;Banner&gt;().Where(x => x.Id == id).Select(x => x.Name).SingleAsync();
        /// </code>
        /// </example>
        public virtual Task<string> GetBlobDescriptiveNameForSnapshottedUrlOfBanner(long id) => Task.FromResult(string.Empty);

        /// <summary>
        /// Lifecycle hook called before blob upload is authorized.
        /// Override this to add custom validation logic before authorization.
        /// </summary>
        /// <param name="file">The file being uploaded</param>
        /// <param name="id">The entity ID</param>
        public virtual Task OnBeforeSnapshottedUrlBlobForBannerUploadIsAuthorized (IFormFile file, long id) => Task.CompletedTask;

        /// <summary>
        /// Lifecycle hook called before blob is uploaded to storage.
        /// Default implementation validates and optimizes images. Override to customize file processing.
        /// </summary>
        /// <param name="stream">The file stream</param>
        /// <param name="file">The form file</param>
        /// <param name="id">The entity ID</param>
        /// <returns>Processed file bytes</returns>
        public virtual async Task<byte[]> OnBeforeSnapshottedUrlBlobForBannerIsUploaded (Stream stream, IFormFile file, long id)
        {
            if (Helper.IsOptimizableImage(file.ContentType)) // rasters only — SVG can't go through ImageSharp, it passes through raw
            {
                await ValidateImageForSnapshottedUrlOfBanner(stream, file, id);
                stream.Position = 0;
                return await OptimizeImageForSnapshottedUrlOfBanner(stream, file, id);
            }
            else
            {
                return await Helper.ReadAllBytesAsync(stream);
            }
        }

        /// <summary>
        /// Validates image dimensions and other constraints for the SnapshottedUrl property.
        /// Override to customize validation logic (e.g., different dimension requirements, aspect ratio checks).
        /// </summary>
        /// <param name="stream">The image stream</param>
        /// <param name="file">The form file</param>
        /// <param name="id">The entity ID</param>
        public virtual Task ValidateImageForSnapshottedUrlOfBanner(Stream stream, IFormFile file, long id) => Task.CompletedTask;

        /// <summary>
        /// Optimizes the image for the SnapshottedUrl property.
        /// Override to customize optimization (e.g., different quality, resizing, format conversion).
        /// </summary>
        /// <param name="stream">The image stream</param>
        /// <param name="file">The form file</param>
        /// <param name="id">The entity ID</param>
        /// <returns>Optimized image bytes</returns>
        public virtual async Task<byte[]> OptimizeImageForSnapshottedUrlOfBanner(Stream stream, IFormFile file, long id)
        {
            return await Helper.OptimizeImage(stream);
        }

        /// <summary>
        /// Uploads a blob/file for the LogoUrl property of Banner.
        /// Automatically optimizes images before upload. The entity ID is extracted from the filename.
        /// </summary>
        /// <param name="file">The file to upload</param>
        /// <param name="authorizeUpdate">Whether to perform authorization check for Update operation</param>
        /// <param name="authorizeInsert">Whether to perform authorization check for Insert operation</param>
        /// <returns>The filename in storage</returns>
        public virtual async Task<string> UploadLogoUrlForBanner(IFormFile file, bool authorizeUpdate, bool authorizeInsert)
        {
            long id = Helper.GetObjectIdFromFileName<long>(file.FileName);

            await OnBeforeLogoUrlBlobForBannerUploadIsAuthorized(file, id);

            if (id > 0 && authorizeUpdate)
            {
                await _deps.AuthorizationService.AuthorizeLogoUrlForBannerUpdateAndThrow(id);
            }
            else if (authorizeInsert)
            {
                await _deps.AuthorizationService.AuthorizeLogoUrlForBannerInsertAndThrow();
            }

            Helper.ValidateFileSize(file.Length, 20000000, _deps.Localizer);

            using (Stream signatureStream = file.OpenReadStream())
            {
                await Helper.ValidateFileSignature(signatureStream, file.ContentType, new[] { "image/*" }, _deps.Localizer);
            }
            string fileName;
            string descriptiveName = id > 0 ? await GetBlobDescriptiveNameForLogoUrlOfBanner(id) : string.Empty;

            using (Stream stream = file.OpenReadStream())
            {
                byte[] byteArray = await OnBeforeLogoUrlBlobForBannerIsUploaded(stream, file, id);

                // The optimize hook may have transcoded the bytes (rasters -> WebP by default), and the
                // storage key's extension + Content-Type are derived from this name.
                string uploadFileName = Helper.AlignExtensionWithContent(file.FileName, byteArray, file.ContentType);

                using (Stream updatedStream = new MemoryStream(byteArray))
                {
                    fileName = await _s3PublicStorageService.UploadFileAsync(uploadFileName, nameof(Banner) + "/" + nameof(Banner.LogoUrl), id.ToString(), updatedStream, descriptiveName);
                }
            }

            return fileName;
        }

        /// <summary>
        /// Optional descriptive name for blobs uploaded to the LogoUrl property. When it returns a
        /// non-empty value, the value is slugified and becomes the human/SEO-readable part of the storage
        /// key (<c>{prefix}/{id}/{slug}-{suffix}.{ext}</c>); the default (empty) keeps the GUID-only key.
        /// Called with the owning entity's id on direct upload (id &gt; 0) and lazily at staged-blob
        /// promotion — typically overridden to return the entity's (or its parent's) slug or display name.
        /// </summary>
        /// <example>
        /// <code>
        /// public override async Task&lt;string&gt; GetBlobDescriptiveNameForLogoUrlOfBanner(long id) =>
        ///     await _context.DbSet&lt;Banner&gt;().Where(x => x.Id == id).Select(x => x.Name).SingleAsync();
        /// </code>
        /// </example>
        public virtual Task<string> GetBlobDescriptiveNameForLogoUrlOfBanner(long id) => Task.FromResult(string.Empty);

        /// <summary>
        /// Lifecycle hook called before blob upload is authorized.
        /// Override this to add custom validation logic before authorization.
        /// </summary>
        /// <param name="file">The file being uploaded</param>
        /// <param name="id">The entity ID</param>
        public virtual Task OnBeforeLogoUrlBlobForBannerUploadIsAuthorized (IFormFile file, long id) => Task.CompletedTask;

        /// <summary>
        /// Lifecycle hook called before blob is uploaded to storage.
        /// Default implementation validates and optimizes images. Override to customize file processing.
        /// </summary>
        /// <param name="stream">The file stream</param>
        /// <param name="file">The form file</param>
        /// <param name="id">The entity ID</param>
        /// <returns>Processed file bytes</returns>
        public virtual async Task<byte[]> OnBeforeLogoUrlBlobForBannerIsUploaded (Stream stream, IFormFile file, long id)
        {
            if (Helper.IsOptimizableImage(file.ContentType)) // rasters only — SVG can't go through ImageSharp, it passes through raw
            {
                await ValidateImageForLogoUrlOfBanner(stream, file, id);
                stream.Position = 0;
                return await OptimizeImageForLogoUrlOfBanner(stream, file, id);
            }
            else
            {
                return await Helper.ReadAllBytesAsync(stream);
            }
        }

        /// <summary>
        /// Validates image dimensions and other constraints for the LogoUrl property.
        /// Override to customize validation logic (e.g., different dimension requirements, aspect ratio checks).
        /// </summary>
        /// <param name="stream">The image stream</param>
        /// <param name="file">The form file</param>
        /// <param name="id">The entity ID</param>
        public virtual Task ValidateImageForLogoUrlOfBanner(Stream stream, IFormFile file, long id) => Task.CompletedTask;

        /// <summary>
        /// Optimizes the image for the LogoUrl property.
        /// Override to customize optimization (e.g., different quality, resizing, format conversion).
        /// </summary>
        /// <param name="stream">The image stream</param>
        /// <param name="file">The form file</param>
        /// <param name="id">The entity ID</param>
        /// <returns>Optimized image bytes</returns>
        public virtual async Task<byte[]> OptimizeImageForLogoUrlOfBanner(Stream stream, IFormFile file, long id)
        {
            return await Helper.OptimizeImage(stream);
        }



        #endregion

        #region Delete

        /// <summary>
        /// Per-id variant of the pre-delete hook. By default forwards to
        /// <see cref="OnBeforeBannerListDelete"/> with a one-element list, so override
        /// only the list hook unless single-id and batch flows genuinely diverge.
        /// </summary>
        /// <param name="id">The ID of the entity being deleted</param>
        public virtual Task OnBeforeBannerDelete(long id) =>
            OnBeforeBannerListDelete(id.StructToList());

        /// <summary>
        /// Per-id variant of the post-delete hook. By default forwards to
        /// <see cref="OnAfterBannerListDelete"/> with a one-element list, so override
        /// only the list hook unless single-id and batch flows genuinely diverge.
        /// </summary>
        /// <param name="id">The ID of the entity that was deleted</param>
        public virtual Task OnAfterBannerDelete(long id) =>
            OnAfterBannerListDelete(id.StructToList());

        /// <summary>
        /// Deletes a single Banner entity with cascade delete handling for dependent entities.
        /// </summary>
        /// <param name="id">The ID of the entity to delete</param>
        public async virtual Task DeleteBanner(long id)
        {
            await _deps.Context.WithTransactionAsync(async () =>
            {
                await OnBeforeBannerDelete(id);

                // Persist writes the hook staged (e.g. IOutbox.Enqueue) as part of this
                // transaction; the next step (untracked cascade delete, or the commit) won't
                // flush them and WithTransactionAsync's clean-tracker guard would throw.
                if (_deps.Context.ChangeTracker.HasChanges())
                    await _deps.Context.SaveChangesAsync();

                List<long> listForDelete_1 = id.StructToList();



                await DeleteEntityAsync<Banner, long>(id);

                await OnAfterBannerDelete(id);

                // Persist writes the hook staged (e.g. IOutbox.Enqueue) as part of this
                // transaction; the next step (untracked cascade delete, or the commit) won't
                // flush them and WithTransactionAsync's clean-tracker guard would throw.
                if (_deps.Context.ChangeTracker.HasChanges())
                    await _deps.Context.SaveChangesAsync();
            });
        }

        /// <summary>
        /// Lifecycle hook called before deleting a list of Banner entities.
        /// Override this to add custom validation or business logic before batch deletion.
        /// </summary>
        /// <param name="listForDelete">The list of entity IDs being deleted</param>
        public virtual Task OnBeforeBannerListDelete(List<long> listForDelete) => Task.CompletedTask;

        /// <summary>
        /// Lifecycle hook called after deleting a list of Banner entities (cascades included),
        /// still inside the delete transaction — queries observe the post-delete state, and anything
        /// written here commits or rolls back atomically with the delete.
        /// Override this to recompute denormalized aggregates or stage post-delete work.
        /// </summary>
        /// <param name="deletedIds">The list of entity IDs that were deleted</param>
        /// <example>
        /// public override async Task OnAfterBannerListDelete(List&lt;long&gt; deletedIds)
        /// {
        ///     await RecalculateAggregatesAsync(); // reads the post-delete state
        /// }
        /// </example>
        public virtual Task OnAfterBannerListDelete(List<long> deletedIds) => Task.CompletedTask;

        /// <summary>
        /// Deletes multiple Banner entities with cascade delete handling for dependent entities.
        /// </summary>
        /// <param name="listForDelete_1">The list of entity IDs to delete</param>
        public async virtual Task DeleteBannerList(List<long> listForDelete_1)
        {
            await _deps.Context.WithTransactionAsync(async () =>
            {
                await OnBeforeBannerListDelete(listForDelete_1);

                // Persist writes the hook staged (e.g. IOutbox.Enqueue) as part of this
                // transaction; the next step (untracked cascade delete, or the commit) won't
                // flush them and WithTransactionAsync's clean-tracker guard would throw.
                if (_deps.Context.ChangeTracker.HasChanges())
                    await _deps.Context.SaveChangesAsync();



                await DeleteEntitiesAsync<Banner, long>(listForDelete_1);

                await OnAfterBannerListDelete(listForDelete_1);

                // Persist writes the hook staged (e.g. IOutbox.Enqueue) as part of this
                // transaction; the next step (untracked cascade delete, or the commit) won't
                // flush them and WithTransactionAsync's clean-tracker guard would throw.
                if (_deps.Context.ChangeTracker.HasChanges())
                    await _deps.Context.SaveChangesAsync();
            });
        }

        #endregion

        #region One To Many



        #endregion

    }
}