//HintName: ItemService.generated.cs
// <auto-generated/>
#nullable disable

using TestApp.Business.ValidationRules;
using TestApp.Business.DataMappers;
using TestApp.Business.DTO;
using TestApp.Business.Entities;
using TestApp.Business.Enums;
using TestApp.Business.ExcelProperties;
using TestApp.Business.Filtering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Localization;
using System.Data;
using FluentValidation;
using Spiderly.Security.Services;
using Spiderly.Security.Interfaces;
using Spiderly.Shared.Excel;
using Spiderly.Shared.Interfaces;
using Spiderly.Shared.Services;
using Spiderly.Shared.Classes;
using Spiderly.Shared.DTO;
using Spiderly.Shared.Extensions;
using Spiderly.Shared.Exceptions;
using Spiderly.Shared.Helpers;
using Mapster;
using Microsoft.AspNetCore.Http;

namespace TestApp.Business.Services
{
    /// <summary>
    /// Generated service for the Item entity. Override lifecycle hooks
    /// by creating a <c>ItemService</c> class that inherits from this class.
    /// </summary>
    public class ItemServiceGenerated : ServiceBase
    {
        protected readonly EntityServiceDependencies _deps;


        public ItemServiceGenerated(EntityServiceDependencies deps) : base(deps.Context, deps.Localizer)
        {
            _deps = deps;

        }

        #region Read

        /// <summary>
        /// Retrieves the complete MainUIFormDTO for Item, including the entity DTO and all related collections (one-to-many, many-to-many).
        /// </summary>
        /// <param name="id">The ID of the Item entity</param>
        /// <returns>ItemMainUIFormDTO containing the entity DTO and related data</returns>
        public async virtual Task<ItemMainUIFormDTO> GetItemMainUIFormDTO(long id)
        {
            return await _deps.Context.WithTransactionAsync(async () =>
            {
                var result = new ItemMainUIFormDTO
                {
                    ItemDTO = await GetItemDTO(id),
                    ItemWarehouses = await GetItemWarehousesForItem(id),
                };

                await OnAfterGetItemMainUIFormDTO(result);

                return result;
            });
        }

        /// <summary>
        /// Lifecycle hook called after retrieving Item MainUIFormDTO.
        /// Override this method to enrich the MainUIFormDTO with additional data (e.g., computed fields, extra queries).
        /// This method runs inside a database transaction.
        /// </summary>
        /// <example>
        /// protected override async Task OnAfterGetItemMainUIFormDTO(ItemMainUIFormDTO mainUIFormDTO)
        /// {
        ///     mainUIFormDTO.CustomProperty = await _deps.Context.DbSet&lt;OtherEntity&gt;().Where(x => x.ItemId == mainUIFormDTO.ItemDTO.Id).CountAsync();
        /// }
        /// </example>
        /// <param name="mainUIFormDTO">The MainUIFormDTO that was just constructed with entity and related data</param>
        protected virtual async Task OnAfterGetItemMainUIFormDTO(ItemMainUIFormDTO mainUIFormDTO) { }

        /// <summary>
        /// Retrieves a single Item entity as a DTO with blob data populated.
        /// </summary>
        /// <param name="id">The ID of the Item entity</param>
        /// <returns>ItemDTO with all blob properties populated</returns>
        public async virtual Task<ItemDTO> GetItemDTO(long id)
        {
            return await _deps.Context.WithTransactionAsync(async () =>
            {
                var dto = await _deps.Context.DbSet<Item>()
                    .AsNoTracking()
                    .Where(x => x.Id == id).ProjectToType<ItemDTO>(Mapper.ItemProjectToConfig())
                    .SingleOrDefaultAsync();

                if (dto == null)
                    throw new BusinessException(_deps.Localizer["EntityDoesNotExistInDatabase"]);



                return dto;
            });
        }

        /// <summary>
        /// Retrieves a paginated list of Item entities.
        /// </summary>
        /// <param name="filterDTO">Filter and pagination parameters</param>
        /// <param name="query">The base query to paginate</param>
        /// <returns>PaginatedResult containing the query and total record count</returns>
        public async virtual Task<PaginatedResult<Item>> GetPaginatedItemResult(FilterDTO filterDTO, IQueryable<Item> query)
        {
            return await _deps.Context.WithTransactionAsync(async () =>
            {
                return await PaginatedResultGenerator.Build(query.AsNoTracking(), filterDTO);
            });
        }

        /// <summary>
        /// Retrieves a paginated list of Item DTOs with blob data populated.
        /// </summary>
        /// <param name="filterDTO">Filter and pagination parameters</param>
        /// <param name="query">The base query to paginate</param>
        /// <returns>PaginatedResultDTO containing ItemDTO list and total record count</returns>
        public async virtual Task<PaginatedResultDTO<ItemDTO>> GetPaginatedItemList(FilterDTO filterDTO, IQueryable<Item> query)
        {
            PaginatedResult<Item> paginationResult = new();
            List<ItemDTO> dtoList = null;

            await _deps.Context.WithTransactionAsync(async () =>
            {
                paginationResult = await GetPaginatedItemResult(filterDTO, query);

                dtoList = await paginationResult.Query
                    .Skip(filterDTO.First)
                    .Take(filterDTO.Rows)
                    .ProjectToType<ItemDTO>(Mapper.ItemProjectToConfig())
                    .ToListAsync();


            });

            return new PaginatedResultDTO<ItemDTO> { Data = dtoList, TotalRecords = paginationResult.TotalRecords };
        }

        /// <summary>
        /// Exports a filtered list of Item entities to Excel format.
        /// </summary>
        /// <param name="filterDTO">Filter parameters for the export</param>
        /// <param name="query">The base query to export</param>
        /// <param name="cancellationToken">Cancellation token</param>
        /// <returns>Excel file as byte array</returns>
        public async virtual Task<byte[]> ExportItemListToExcel(FilterDTO filterDTO, IQueryable<Item> query, CancellationToken cancellationToken = default)
        {
            IQueryable<ItemDTO> exportQuery = null;

            await _deps.Context.WithTransactionAsync(async () =>
            {
                PaginatedResult<Item> paginationResult = await GetPaginatedItemResult(filterDTO, query);
                int maxRows = _deps.ExcelSettings.ExcelExportMaxRows;
                exportQuery = paginationResult.Query
                    .OrderBy(x => x.Id)
                    .Take(maxRows)
                    .ProjectToType<ItemDTO>(Mapper.ItemExcelProjectToConfig());
            });

            string[] excelPropertiesToExclude = ExcelPropertiesToExclude.GetHeadersToExclude(new ItemDTO());
            return await _deps.ExcelService.FillReportTemplateAsync(
                exportQuery.AsAsyncEnumerable(),
                excelPropertiesToExclude,
                _deps.Localizer,
                cancellationToken);
        }

        /// <summary>
        /// Retrieves a list of Item entities without pagination.
        /// </summary>
        /// <param name="query">The query to execute</param>
        /// <returns>List of Item entities</returns>
        public async virtual Task<List<Item>> GetItemList(IQueryable<Item> query)
        {
            return await _deps.Context.WithTransactionAsync(async () =>
            {
                var result = await query
                    .ToListAsync();

                return result;
            });
        }

        /// <summary>
        /// Retrieves a list of Item DTOs without pagination, with blob data populated.
        /// </summary>
        /// <param name="query">The query to execute</param>
        /// <returns>List of ItemDTO with blob properties populated</returns>
        public async virtual Task<List<ItemDTO>> GetItemDTOList(IQueryable<Item> query)
        {
            return await _deps.Context.WithTransactionAsync(async () =>
            {
                var dtoList = await query
                    .AsNoTracking()
                    .ProjectToType<ItemDTO>(Mapper.ItemToDTOConfig())
                    .ToListAsync();



                return dtoList;
            });
        }



        #endregion

        #region Save

        /// <summary>
        /// Saves a Item entity and returns the complete MainUIFormDTO including all related collections.
        /// Handles insert/update logic, many-to-many relationships, and ordered one-to-many collections.
        /// </summary>
        /// <param name="saveBodyDTO">The SaveBodyDTO containing entity data and related selections</param>
        /// <param name="authorizeUpdate">Whether to perform authorization check for Update operation</param>
        /// <param name="authorizeInsert">Whether to perform authorization check for Insert operation</param>
        /// <returns>ItemMainUIFormDTO with saved data and updated collections</returns>
        public virtual async Task<ItemMainUIFormDTO> SaveItemAndReturnMainUIFormDTO(ItemSaveBodyDTO saveBodyDTO, bool authorizeUpdate, bool authorizeInsert)
        {
            new ItemSaveBodyDTOValidationRules().ValidateAndThrow(saveBodyDTO);

            return await _deps.Context.WithTransactionAsync(async () =>
            {
                await OnBeforeSaveItemAndReturnMainUIFormDTO(saveBodyDTO);

                var savedDTO = await SaveItemAndReturnDTO(saveBodyDTO.ItemDTO, authorizeUpdate, authorizeInsert);




                await UpdateItemWarehousesForItem(savedDTO.Id, saveBodyDTO.ItemWarehouses);

                var result = new ItemMainUIFormDTO
                {
                    ItemDTO = savedDTO,


                    ItemWarehouses = await GetItemWarehousesForItem(savedDTO.Id),
                };

                await OnAfterSaveItemAndReturnMainUIFormDTO(saveBodyDTO, result);

                return result;
            });
        }




        /// <summary>
        /// Lifecycle hook called before saving Item with MainUIFormDTO.
        /// Override this method to add custom validation or modify the SaveBodyDTO.
        /// This method runs inside a database transaction.
        /// </summary>
        /// <param name="saveBodyDTO">The SaveBodyDTO containing entity and related data</param>
        protected virtual async Task OnBeforeSaveItemAndReturnMainUIFormDTO(ItemSaveBodyDTO saveBodyDTO) { }

        /// <summary>
        /// Lifecycle hook called after saving Item and after updating related collections.
        /// Override this method to add custom business logic after the main entity is saved.
        /// This method runs inside a database transaction.
        /// </summary>
        /// <param name="saveBodyDTO">The original SaveBodyDTO</param>
        /// <param name="mainUIFormDTO">The save result and DTO sent to the UI</param>
        protected virtual async Task OnAfterSaveItemAndReturnMainUIFormDTO(ItemSaveBodyDTO saveBodyDTO, ItemMainUIFormDTO mainUIFormDTO) { }

        /// <summary>
        /// Saves a Item entity and returns the DTO with blob data populated.
        /// </summary>
        /// <param name="saveDTO">The DTO containing entity data to save</param>
        /// <param name="authorizeUpdate">Whether to perform authorization check for Update operation</param>
        /// <param name="authorizeInsert">Whether to perform authorization check for Insert operation</param>
        /// <returns>Saved ItemDTO with blob properties populated</returns>
        public async virtual Task<ItemDTO> SaveItemAndReturnDTO(ItemDTO saveDTO, bool authorizeUpdate, bool authorizeInsert)
        {
            return await _deps.Context.WithTransactionAsync(async () =>
            {
                var poco = await SaveItem(saveDTO, authorizeUpdate, authorizeInsert);

                var dto = poco.Adapt<ItemDTO>(Mapper.ItemToDTOConfig());



                return dto;
            });
        }

        /// <summary>
        /// Core save method that handles both insert and update operations for Item.
        /// Validates the DTO, maps to entity, handles many-to-one relationships, and manages blob deletion.
        /// </summary>
        /// <param name="dto">The DTO containing entity data to save</param>
        /// <param name="authorizeUpdate">Whether to perform authorization check for Update operation</param>
        /// <param name="authorizeInsert">Whether to perform authorization check for Insert operation</param>
        /// <returns>Saved Item entity</returns>
        public async virtual Task<Item> SaveItem(ItemDTO dto, bool authorizeUpdate, bool authorizeInsert)
        {
            ItemDTOValidationRules validationRules = new ItemDTOValidationRules();
            validationRules.ValidateAndThrow(dto);

            Item poco = null;
            await _deps.Context.WithTransactionAsync(async () =>
            {
                await OnBeforeItemIsMapped(dto);
                DbSet<Item> dbSet = _deps.Context.DbSet<Item>();

                if (dto.Id > 0)
                {
                    if (authorizeUpdate)
                    {
                        await _deps.AuthorizationService.AuthorizeItemUpdateAndThrow(dto);
                    }

                    poco = await GetInstanceAsync<Item, long>(dto.Id, dto.Version);
                    await OnBeforeItemUpdate(poco, dto);
                    dto.Adapt(poco, Mapper.ItemDTOToEntityConfig());
                    dbSet.Update(poco);
                }
                else
                {
                    if (authorizeInsert)
                    {
                        await _deps.AuthorizationService.AuthorizeItemInsertAndThrow(dto);
                    }

                    poco = dto.Adapt<Item>(Mapper.ItemDTOToEntityConfig());
                    await OnBeforeItemInsert(poco, dto);
                    await dbSet.AddAsync(poco);
                }



                await _deps.Context.SaveChangesAsync();






            });

            return poco;
        }

        /// <summary>
        /// Lifecycle hook called before the ItemDTO is mapped to the entity.
        /// Override this method to add custom validation or modify the DTO before mapping.
        /// This method runs inside a database transaction.
        /// </summary>
        /// <param name="itemDTO">The DTO about to be mapped</param>
        protected virtual async Task OnBeforeItemIsMapped(ItemDTO itemDTO) { }

        /// <summary>
        /// Lifecycle hook called before updating an existing Item entity.
        /// Override this method to add custom business logic during updates.
        /// This method runs inside a database transaction.
        /// </summary>
        /// <param name="item">The existing entity being updated</param>
        /// <param name="itemDTO">The DTO containing new data</param>
        protected virtual async Task OnBeforeItemUpdate(Item item, ItemDTO itemDTO) { }

        /// <summary>
        /// Lifecycle hook called before inserting a new Item entity.
        /// Override this method to add custom business logic during inserts.
        /// This method runs inside a database transaction.
        /// </summary>
        /// <param name="item">The new entity being inserted</param>
        /// <param name="itemDTO">The DTO containing the data</param>
        protected virtual async Task OnBeforeItemInsert(Item item, ItemDTO itemDTO) { }





        #endregion

        #region Delete

        /// <summary>
        /// Per-id variant of the pre-delete hook. By default forwards to
        /// <see cref="OnBeforeItemListDelete"/> with a one-element list, so override
        /// only the list hook unless single-id and batch flows genuinely diverge.
        /// </summary>
        /// <param name="id">The ID of the entity being deleted</param>
        public virtual Task OnBeforeItemDelete(long id) =>
            OnBeforeItemListDelete(id.StructToList());

        /// <summary>
        /// Per-id variant of the post-delete hook. By default forwards to
        /// <see cref="OnAfterItemListDelete"/> with a one-element list, so override
        /// only the list hook unless single-id and batch flows genuinely diverge.
        /// </summary>
        /// <param name="id">The ID of the entity that was deleted</param>
        public virtual Task OnAfterItemDelete(long id) =>
            OnAfterItemListDelete(id.StructToList());

        /// <summary>
        /// Deletes a single Item entity with cascade delete handling for dependent entities.
        /// </summary>
        /// <param name="id">The ID of the entity to delete</param>
        public async virtual Task DeleteItem(long id)
        {
            await _deps.Context.WithTransactionAsync(async () =>
            {
                await OnBeforeItemDelete(id);

                // Persist writes the hook staged (e.g. IOutbox.Enqueue) as part of this
                // transaction; the next step (untracked cascade delete, or the commit) won't
                // flush them and WithTransactionAsync's clean-tracker guard would throw.
                if (_deps.Context.ChangeTracker.HasChanges())
                    await _deps.Context.SaveChangesAsync();

                List<long> listForDelete_1 = id.StructToList();



                await DeleteEntityAsync<Item, long>(id);

                await OnAfterItemDelete(id);

                // Persist writes the hook staged (e.g. IOutbox.Enqueue) as part of this
                // transaction; the next step (untracked cascade delete, or the commit) won't
                // flush them and WithTransactionAsync's clean-tracker guard would throw.
                if (_deps.Context.ChangeTracker.HasChanges())
                    await _deps.Context.SaveChangesAsync();
            });
        }

        /// <summary>
        /// Lifecycle hook called before deleting a list of Item entities.
        /// Override this to add custom validation or business logic before batch deletion.
        /// </summary>
        /// <param name="listForDelete">The list of entity IDs being deleted</param>
        public virtual async Task OnBeforeItemListDelete(List<long> listForDelete) { }

        /// <summary>
        /// Lifecycle hook called after deleting a list of Item entities (cascades included),
        /// still inside the delete transaction — queries observe the post-delete state, and anything
        /// written here commits or rolls back atomically with the delete.
        /// Override this to recompute denormalized aggregates or stage post-delete work.
        /// </summary>
        /// <param name="deletedIds">The list of entity IDs that were deleted</param>
        /// <example>
        /// public override async Task OnAfterItemListDelete(List&lt;long&gt; deletedIds)
        /// {
        ///     await RecalculateAggregatesAsync(); // reads the post-delete state
        /// }
        /// </example>
        public virtual async Task OnAfterItemListDelete(List<long> deletedIds) { }

        /// <summary>
        /// Deletes multiple Item entities with cascade delete handling for dependent entities.
        /// </summary>
        /// <param name="listForDelete_1">The list of entity IDs to delete</param>
        public async virtual Task DeleteItemList(List<long> listForDelete_1)
        {
            await _deps.Context.WithTransactionAsync(async () =>
            {
                await OnBeforeItemListDelete(listForDelete_1);

                // Persist writes the hook staged (e.g. IOutbox.Enqueue) as part of this
                // transaction; the next step (untracked cascade delete, or the commit) won't
                // flush them and WithTransactionAsync's clean-tracker guard would throw.
                if (_deps.Context.ChangeTracker.HasChanges())
                    await _deps.Context.SaveChangesAsync();



                await DeleteEntitiesAsync<Item, long>(listForDelete_1);

                await OnAfterItemListDelete(listForDelete_1);

                // Persist writes the hook staged (e.g. IOutbox.Enqueue) as part of this
                // transaction; the next step (untracked cascade delete, or the commit) won't
                // flush them and WithTransactionAsync's clean-tracker guard would throw.
                if (_deps.Context.ChangeTracker.HasChanges())
                    await _deps.Context.SaveChangesAsync();
            });
        }

        #endregion

        #region One To Many

        /// <summary>
        /// Retrieves all ItemWarehouse DTOs for a Item, including default records for Warehouse entities without existing junction records.
        /// </summary>
        /// <param name="id">The ID of the Item entity</param>
        /// <returns>List of ItemWarehouseDTO for all Warehouse entities</returns>
        public async virtual Task<List<ItemWarehouseDTO>> GetItemWarehousesForItem(long id)
        {
            return await _deps.Context.WithTransactionAsync(async () =>
            {
                var allOtherSideEntries = await _deps.Context.DbSet<Warehouse>()
                    .AsNoTracking()
                    .OrderBy(x => x.Id)
                    .Select(x => new { x.Id, DisplayName = x.Name })
                    .ToListAsync();

                var existingRecords = await _deps.Context.DbSet<ItemWarehouse>()
                    .AsNoTracking()
                    .Where(x => x.ItemId == id)
                    .ProjectToType<ItemWarehouseDTO>(Mapper.ItemWarehouseProjectToConfig())
                    .ToListAsync();

                var result = new List<ItemWarehouseDTO>();

                foreach (var otherSideEntry in allOtherSideEntries)
                {
                    var existing = existingRecords.FirstOrDefault(x => x.WarehouseId == otherSideEntry.Id);
                    result.Add(existing ?? new ItemWarehouseDTO { WarehouseId = otherSideEntry.Id, WarehouseDisplayName = otherSideEntry.DisplayName });
                }

                return result;
            });
        }

        /// <summary>
        /// Updates all ItemWarehouse records for a Item by deleting existing records and inserting new ones.
        /// Rows whose additional columns are all null are skipped — the ComplexManyToManyList form posts a placeholder
        /// row for every Warehouse without a record, and leaving a row blank (or blanking an existing one) means "no record".
        /// </summary>
        /// <param name="id">The ID of the Item entity</param>
        /// <param name="dtos">List of ItemWarehouseDTO to save</param>
        public async virtual Task UpdateItemWarehousesForItem(long id, List<ItemWarehouseDTO> dtos)
        {
            await _deps.Context.WithTransactionAsync(async () =>
            {
                await _deps.Context.DbSet<ItemWarehouse>()
                    .Where(x => x.ItemId == id)
                    .ExecuteDeleteAsync();

                var validationRules = new ItemWarehouseDTOValidationRules();

                foreach (var dto in dtos)
                {
                    if (dto.Stock == null)
                        continue; // Placeholder row (Get/GetDefault emit one per Warehouse without a record) — no data means no record.

                    validationRules.ValidateAndThrow(dto);

                    if (dto.WarehouseId == null)
                        throw new SpiderlyValidationException(new Dictionary<string, string[]> { ["WarehouseId"] = new[] { "WarehouseId is required." } });

                    var poco = new ItemWarehouse();
                    poco.Stock = dto.Stock.Value;

                    var entry = await _deps.Context.DbSet<ItemWarehouse>().AddAsync(poco);

                    entry.Property("ItemId").CurrentValue = id;
                    entry.Property("WarehouseId").CurrentValue = dto.WarehouseId;
                }
            });
        }

        /// <summary>
        /// Returns default junction DTOs for all Warehouse entities (without existing records).
        /// Used when creating a new Item to pre-populate the ComplexManyToManyList form.
        /// </summary>
        /// <returns>List of ItemWarehouseDTO with WarehouseId and WarehouseDisplayName populated</returns>
        public async virtual Task<List<ItemWarehouseDTO>> GetDefaultItemWarehousesForItem()
        {
            return await _deps.Context.WithTransactionAsync(async () =>
            {
                return await _deps.Context.DbSet<Warehouse>()
                    .AsNoTracking()
                    .OrderBy(x => x.Id)
                    .Select(x => new ItemWarehouseDTO
                    {
                        WarehouseId = x.Id,
                        WarehouseDisplayName = x.Name,
                    })
                    .ToListAsync();
            });
        }

        #endregion

    }
}