using Microsoft.CodeAnalysis;
using Spiderly.SourceGenerators.Net;
using Spiderly.SourceGenerators.Tests.Infrastructure;

namespace Spiderly.SourceGenerators.Tests.Generators;

/// <summary>
/// Every generated C# file must declare its own nullable context explicitly, keyed off the consumer
/// compilation's <c>NullableContextOptions</c>: <c>#nullable disable</c> for oblivious consumers
/// (today's output, made explicit) and <c>#nullable enable</c> once the consumer turns NRT on — so a
/// consumer flipping <c>&lt;Nullable&gt;enable&lt;/Nullable&gt;</c> never drowns in CS8618/CS8625
/// warnings raised inside files it cannot edit. The header also carries <c>&lt;auto-generated/&gt;</c>
/// so style analyzers skip generated code. ControllerGenerator is exercised by the e2e fixture apps
/// instead — it emits nothing under this harness (no <c>.WebAPI</c> calling path).
/// </summary>
public class GeneratedCSharpNullablePragmaTests
{
    private const string Source = """
        using System.Collections.Generic;

        namespace TestApp.Business.Entities
        {
            [SpiderlyEntity]
            public class Category : BusinessObject<long>
            {
                [DisplayName]
                public string Name { get; set; }

                public virtual List<Product> Products { get; } = new();
            }

            [SpiderlyEntity]
            public class Product : BusinessObject<long>
            {
                [DisplayName]
                public string Title { get; set; }

                public string Description { get; set; }

                [WithMany(nameof(Category.Products))]
                public virtual Category Category { get; set; }
            }
        }

        namespace TestApp.Business.DataMappers
        {
            [SpiderlyDataMapper]
            public partial class Mapper { }
        }
        """;

    public static TheoryData<Type, NullableContextOptions> Cases()
    {
        Type[] generators =
        [
            typeof(EntitiesToDTOGenerator),
            typeof(MapperGenerator),
            typeof(ServicesGenerator),
            typeof(FluentValidationGenerator),
            typeof(PaginatedResultGenerator),
            typeof(AuthorizationServicesGenerator),
            typeof(ExcelPropertiesGenerator),
            typeof(PermissionCodesGenerator),
        ];

        TheoryData<Type, NullableContextOptions> data = new();
        foreach (Type generator in generators)
        {
            data.Add(generator, NullableContextOptions.Disable);
            data.Add(generator, NullableContextOptions.Enable);
        }
        return data;
    }

    [Theory]
    [MemberData(nameof(Cases))]
    public void EveryGeneratedCSharpFile_DeclaresItsNullableContext(Type generatorType, NullableContextOptions nullable)
    {
        var runResult = RunGenerator(generatorType, nullable);
        var sources = runResult.Results.Single().GeneratedSources;

        Assert.NotEmpty(sources);

        string expectedPragma = nullable == NullableContextOptions.Enable ? "#nullable enable" : "#nullable disable";
        foreach (var generated in sources)
        {
            string text = generated.SourceText.ToString();
            Assert.StartsWith("// <auto-generated/>", text);
            Assert.Contains(expectedPragma, text.Substring(0, text.IndexOf('\n', text.IndexOf('\n') + 1) + 1));
        }
    }

    private static GeneratorDriverRunResult RunGenerator(Type generatorType, NullableContextOptions nullable)
    {
        return generatorType switch
        {
            var t when t == typeof(EntitiesToDTOGenerator) => GeneratorTestHarness.Run<EntitiesToDTOGenerator>(Source, nullable).GetRunResult(),
            var t when t == typeof(MapperGenerator) => GeneratorTestHarness.Run<MapperGenerator>(Source, nullable).GetRunResult(),
            var t when t == typeof(ServicesGenerator) => GeneratorTestHarness.Run<ServicesGenerator>(Source, nullable).GetRunResult(),
            var t when t == typeof(FluentValidationGenerator) => GeneratorTestHarness.Run<FluentValidationGenerator>(Source, nullable).GetRunResult(),
            var t when t == typeof(PaginatedResultGenerator) => GeneratorTestHarness.Run<PaginatedResultGenerator>(Source, nullable).GetRunResult(),
            var t when t == typeof(AuthorizationServicesGenerator) => GeneratorTestHarness.Run<AuthorizationServicesGenerator>(Source, nullable).GetRunResult(),
            var t when t == typeof(ExcelPropertiesGenerator) => GeneratorTestHarness.Run<ExcelPropertiesGenerator>(Source, nullable).GetRunResult(),
            var t when t == typeof(PermissionCodesGenerator) => GeneratorTestHarness.Run<PermissionCodesGenerator>(Source, nullable).GetRunResult(),
            _ => throw new NotSupportedException(generatorType.Name)
        };
    }
}
