//HintName: LabelService.generated.cs
// <auto-generated/>
#nullable disable

using TestApp.Business.ValidationRules;
using TestApp.Business.DataMappers;
using TestApp.Business.DTO;
using TestApp.Business.Entities;
using TestApp.Business.Enums;
using TestApp.Business.ExcelProperties;
using TestApp.Business.Filtering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Localization;
using System.Data;
using FluentValidation;
using Spiderly.Security.Services;
using Spiderly.Security.Interfaces;
using Spiderly.Shared.Excel;
using Spiderly.Shared.Interfaces;
using Spiderly.Shared.Services;
using Spiderly.Shared.Classes;
using Spiderly.Shared.DTO;
using Spiderly.Shared.Extensions;
using Spiderly.Shared.Exceptions;
using Spiderly.Shared.Helpers;
using Mapster;
using Microsoft.AspNetCore.Http;

namespace TestApp.Business.Services
{
    /// <summary>
    /// Generated service for the Label entity. Override lifecycle hooks
    /// by creating a <c>LabelService</c> class that inherits from this class.
    /// </summary>
    public class LabelServiceGenerated : ServiceBase
    {
        protected readonly EntityServiceDependencies _deps;


        public LabelServiceGenerated(EntityServiceDependencies deps) : base(deps.Context, deps.Localizer)
        {
            _deps = deps;

        }

        #region Read

        /// <summary>
        /// Retrieves the complete MainUIFormDTO for Label, including the entity DTO and all related collections (one-to-many, many-to-many).
        /// </summary>
        /// <param name="id">The ID of the Label entity</param>
        /// <returns>LabelMainUIFormDTO containing the entity DTO and related data</returns>
        public async virtual Task<LabelMainUIFormDTO> GetLabelMainUIFormDTO(int id)
        {
            return await _deps.Context.WithTransactionAsync(async () =>
            {
                var result = new LabelMainUIFormDTO
                {
                    LabelDTO = await GetLabelDTO(id),
                };

                await OnAfterGetLabelMainUIFormDTO(result);

                return result;
            });
        }

        /// <summary>
        /// Lifecycle hook called after retrieving Label MainUIFormDTO.
        /// Override this method to enrich the MainUIFormDTO with additional data (e.g., computed fields, extra queries).
        /// This method runs inside a database transaction.
        /// </summary>
        /// <example>
        /// protected override async Task OnAfterGetLabelMainUIFormDTO(LabelMainUIFormDTO mainUIFormDTO)
        /// {
        ///     mainUIFormDTO.CustomProperty = await _deps.Context.DbSet&lt;OtherEntity&gt;().Where(x => x.LabelId == mainUIFormDTO.LabelDTO.Id).CountAsync();
        /// }
        /// </example>
        /// <param name="mainUIFormDTO">The MainUIFormDTO that was just constructed with entity and related data</param>
        protected virtual Task OnAfterGetLabelMainUIFormDTO(LabelMainUIFormDTO mainUIFormDTO) => Task.CompletedTask;

        /// <summary>
        /// Retrieves a single Label entity as a DTO with blob data populated.
        /// </summary>
        /// <param name="id">The ID of the Label entity</param>
        /// <returns>LabelDTO with all blob properties populated</returns>
        public async virtual Task<LabelDTO> GetLabelDTO(int id)
        {
            return await _deps.Context.WithTransactionAsync(async () =>
            {
                var dto = await _deps.Context.DbSet<Label>()
                    .AsNoTracking()
                    .Where(x => x.Id == id).ProjectToType<LabelDTO>(Mapper.LabelProjectToConfig())
                    .SingleOrDefaultAsync();

                if (dto == null)
                    throw new BusinessException(_deps.Localizer["EntityDoesNotExistInDatabase"]);



                return dto;
            });
        }

        /// <summary>
        /// Retrieves a paginated list of Label entities.
        /// </summary>
        /// <param name="filterDTO">Filter and pagination parameters</param>
        /// <param name="query">The base query to paginate</param>
        /// <returns>PaginatedResult containing the query and total record count</returns>
        public async virtual Task<PaginatedResult<Label>> GetPaginatedLabelResult(FilterDTO filterDTO, IQueryable<Label> query)
        {
            return await _deps.Context.WithTransactionAsync(async () =>
            {
                return await PaginatedResultGenerator.Build(query.AsNoTracking(), filterDTO);
            });
        }

        /// <summary>
        /// Retrieves a paginated list of Label DTOs with blob data populated.
        /// </summary>
        /// <param name="filterDTO">Filter and pagination parameters</param>
        /// <param name="query">The base query to paginate</param>
        /// <returns>PaginatedResultDTO containing LabelDTO list and total record count</returns>
        public async virtual Task<PaginatedResultDTO<LabelDTO>> GetPaginatedLabelList(FilterDTO filterDTO, IQueryable<Label> query)
        {
            PaginatedResult<Label> paginationResult = new();
            List<LabelDTO> dtoList = null!;

            await _deps.Context.WithTransactionAsync(async () =>
            {
                paginationResult = await GetPaginatedLabelResult(filterDTO, query);

                dtoList = await paginationResult.Query
                    .Skip(filterDTO.First)
                    .Take(filterDTO.Rows)
                    .ProjectToType<LabelDTO>(Mapper.LabelProjectToConfig())
                    .ToListAsync();


            });

            return new PaginatedResultDTO<LabelDTO> { Data = dtoList, TotalRecords = paginationResult.TotalRecords };
        }

        /// <summary>
        /// Exports a filtered list of Label entities to Excel format.
        /// </summary>
        /// <param name="filterDTO">Filter parameters for the export</param>
        /// <param name="query">The base query to export</param>
        /// <param name="cancellationToken">Cancellation token</param>
        /// <returns>Excel file as byte array</returns>
        public async virtual Task<byte[]> ExportLabelListToExcel(FilterDTO filterDTO, IQueryable<Label> query, CancellationToken cancellationToken = default)
        {
            IQueryable<LabelDTO> exportQuery = null!;

            await _deps.Context.WithTransactionAsync(async () =>
            {
                PaginatedResult<Label> paginationResult = await GetPaginatedLabelResult(filterDTO, query);
                int maxRows = _deps.ExcelSettings.ExcelExportMaxRows;
                exportQuery = paginationResult.Query
                    .OrderBy(x => x.Id)
                    .Take(maxRows)
                    .ProjectToType<LabelDTO>(Mapper.LabelExcelProjectToConfig());
            });

            string[] excelPropertiesToExclude = ExcelPropertiesToExclude.GetHeadersToExclude(new LabelDTO());
            return await _deps.ExcelService.FillReportTemplateAsync(
                exportQuery.AsAsyncEnumerable(),
                excelPropertiesToExclude,
                _deps.Localizer,
                cancellationToken);
        }

        /// <summary>
        /// Retrieves a list of Label entities without pagination.
        /// </summary>
        /// <param name="query">The query to execute</param>
        /// <returns>List of Label entities</returns>
        public async virtual Task<List<Label>> GetLabelList(IQueryable<Label> query)
        {
            return await _deps.Context.WithTransactionAsync(async () =>
            {
                var result = await query
                    .ToListAsync();

                return result;
            });
        }

        /// <summary>
        /// Retrieves a list of Label DTOs without pagination, with blob data populated.
        /// </summary>
        /// <param name="query">The query to execute</param>
        /// <returns>List of LabelDTO with blob properties populated</returns>
        public async virtual Task<List<LabelDTO>> GetLabelDTOList(IQueryable<Label> query)
        {
            return await _deps.Context.WithTransactionAsync(async () =>
            {
                var dtoList = await query
                    .AsNoTracking()
                    .ProjectToType<LabelDTO>(Mapper.LabelToDTOConfig())
                    .ToListAsync();



                return dtoList;
            });
        }



        #endregion

        #region Save

        /// <summary>
        /// Saves a Label entity and returns the complete MainUIFormDTO including all related collections.
        /// Handles insert/update logic, many-to-many relationships, and ordered one-to-many collections.
        /// </summary>
        /// <param name="saveBodyDTO">The SaveBodyDTO containing entity data and related selections</param>
        /// <param name="authorizeUpdate">Whether to perform authorization check for Update operation</param>
        /// <param name="authorizeInsert">Whether to perform authorization check for Insert operation</param>
        /// <returns>LabelMainUIFormDTO with saved data and updated collections</returns>
        public virtual async Task<LabelMainUIFormDTO> SaveLabelAndReturnMainUIFormDTO(LabelSaveBodyDTO saveBodyDTO, bool authorizeUpdate, bool authorizeInsert)
        {
            new LabelSaveBodyDTOValidationRules().ValidateAndThrow(saveBodyDTO);

            return await _deps.Context.WithTransactionAsync(async () =>
            {
                await OnBeforeSaveLabelAndReturnMainUIFormDTO(saveBodyDTO);

                var savedDTO = await SaveLabelAndReturnDTO(saveBodyDTO.LabelDTO!, authorizeUpdate, authorizeInsert);






                var result = new LabelMainUIFormDTO
                {
                    LabelDTO = savedDTO,



                };

                await OnAfterSaveLabelAndReturnMainUIFormDTO(saveBodyDTO, result);

                return result;
            });
        }




        /// <summary>
        /// Lifecycle hook called before saving Label with MainUIFormDTO.
        /// Override this method to add custom validation or modify the SaveBodyDTO.
        /// This method runs inside a database transaction.
        /// </summary>
        /// <param name="saveBodyDTO">The SaveBodyDTO containing entity and related data</param>
        protected virtual Task OnBeforeSaveLabelAndReturnMainUIFormDTO(LabelSaveBodyDTO saveBodyDTO) => Task.CompletedTask;

        /// <summary>
        /// Lifecycle hook called after saving Label and after updating related collections.
        /// Override this method to add custom business logic after the main entity is saved.
        /// This method runs inside a database transaction.
        /// </summary>
        /// <param name="saveBodyDTO">The original SaveBodyDTO</param>
        /// <param name="mainUIFormDTO">The save result and DTO sent to the UI</param>
        protected virtual Task OnAfterSaveLabelAndReturnMainUIFormDTO(LabelSaveBodyDTO saveBodyDTO, LabelMainUIFormDTO mainUIFormDTO) => Task.CompletedTask;

        /// <summary>
        /// Saves a Label entity and returns the DTO with blob data populated.
        /// </summary>
        /// <param name="saveDTO">The DTO containing entity data to save</param>
        /// <param name="authorizeUpdate">Whether to perform authorization check for Update operation</param>
        /// <param name="authorizeInsert">Whether to perform authorization check for Insert operation</param>
        /// <returns>Saved LabelDTO with blob properties populated</returns>
        public async virtual Task<LabelDTO> SaveLabelAndReturnDTO(LabelDTO saveDTO, bool authorizeUpdate, bool authorizeInsert)
        {
            return await _deps.Context.WithTransactionAsync(async () =>
            {
                var poco = await SaveLabel(saveDTO, authorizeUpdate, authorizeInsert);

                var dto = poco.Adapt<LabelDTO>(Mapper.LabelToDTOConfig());



                return dto;
            });
        }

        /// <summary>
        /// Core save method that handles both insert and update operations for Label.
        /// Validates the DTO, maps to entity, handles many-to-one relationships, and manages blob deletion.
        /// </summary>
        /// <param name="dto">The DTO containing entity data to save</param>
        /// <param name="authorizeUpdate">Whether to perform authorization check for Update operation</param>
        /// <param name="authorizeInsert">Whether to perform authorization check for Insert operation</param>
        /// <returns>Saved Label entity</returns>
        public async virtual Task<Label> SaveLabel(LabelDTO dto, bool authorizeUpdate, bool authorizeInsert)
        {
            LabelDTOValidationRules validationRules = new LabelDTOValidationRules();
            validationRules.ValidateAndThrow(dto);

            Label poco = null!;
            await _deps.Context.WithTransactionAsync(async () =>
            {
                await OnBeforeLabelIsMapped(dto);
                DbSet<Label> dbSet = _deps.Context.DbSet<Label>();

                if (dto.Id > 0)
                {
                    if (authorizeUpdate)
                    {
                        await _deps.AuthorizationService.AuthorizeLabelUpdateAndThrow(dto);
                    }

                    poco = await GetInstanceAsync<Label, int>(dto.Id, dto.Version);
                    await OnBeforeLabelUpdate(poco, dto);
                    dto.Adapt(poco, Mapper.LabelDTOToEntityConfig());
                    dbSet.Update(poco);
                }
                else
                {
                    if (authorizeInsert)
                    {
                        await _deps.AuthorizationService.AuthorizeLabelInsertAndThrow(dto);
                    }

                    poco = dto.Adapt<Label>(Mapper.LabelDTOToEntityConfig());
                    await OnBeforeLabelInsert(poco, dto);
                    await dbSet.AddAsync(poco);
                }



                await _deps.Context.SaveChangesAsync();






            });

            return poco;
        }

        /// <summary>
        /// Lifecycle hook called before the LabelDTO is mapped to the entity.
        /// Override this method to add custom validation or modify the DTO before mapping.
        /// This method runs inside a database transaction.
        /// </summary>
        /// <param name="labelDTO">The DTO about to be mapped</param>
        protected virtual Task OnBeforeLabelIsMapped(LabelDTO labelDTO) => Task.CompletedTask;

        /// <summary>
        /// Lifecycle hook called before updating an existing Label entity.
        /// Override this method to add custom business logic during updates.
        /// This method runs inside a database transaction.
        /// </summary>
        /// <param name="label">The existing entity being updated</param>
        /// <param name="labelDTO">The DTO containing new data</param>
        protected virtual Task OnBeforeLabelUpdate(Label label, LabelDTO labelDTO) => Task.CompletedTask;

        /// <summary>
        /// Lifecycle hook called before inserting a new Label entity.
        /// Override this method to add custom business logic during inserts.
        /// This method runs inside a database transaction.
        /// </summary>
        /// <param name="label">The new entity being inserted</param>
        /// <param name="labelDTO">The DTO containing the data</param>
        protected virtual Task OnBeforeLabelInsert(Label label, LabelDTO labelDTO) => Task.CompletedTask;





        #endregion

        #region Delete

        /// <summary>
        /// Per-id variant of the pre-delete hook. By default forwards to
        /// <see cref="OnBeforeLabelListDelete"/> with a one-element list, so override
        /// only the list hook unless single-id and batch flows genuinely diverge.
        /// </summary>
        /// <param name="id">The ID of the entity being deleted</param>
        public virtual Task OnBeforeLabelDelete(int id) =>
            OnBeforeLabelListDelete(id.StructToList());

        /// <summary>
        /// Per-id variant of the post-delete hook. By default forwards to
        /// <see cref="OnAfterLabelListDelete"/> with a one-element list, so override
        /// only the list hook unless single-id and batch flows genuinely diverge.
        /// </summary>
        /// <param name="id">The ID of the entity that was deleted</param>
        public virtual Task OnAfterLabelDelete(int id) =>
            OnAfterLabelListDelete(id.StructToList());

        /// <summary>
        /// Deletes a single Label entity with cascade delete handling for dependent entities.
        /// </summary>
        /// <param name="id">The ID of the entity to delete</param>
        public async virtual Task DeleteLabel(int id)
        {
            await _deps.Context.WithTransactionAsync(async () =>
            {
                await OnBeforeLabelDelete(id);

                // Persist writes the hook staged (e.g. IOutbox.Enqueue) as part of this
                // transaction; the next step (untracked cascade delete, or the commit) won't
                // flush them and WithTransactionAsync's clean-tracker guard would throw.
                if (_deps.Context.ChangeTracker.HasChanges())
                    await _deps.Context.SaveChangesAsync();

                List<int> listForDelete_1 = id.StructToList();



                await DeleteEntityAsync<Label, int>(id);

                await OnAfterLabelDelete(id);

                // Persist writes the hook staged (e.g. IOutbox.Enqueue) as part of this
                // transaction; the next step (untracked cascade delete, or the commit) won't
                // flush them and WithTransactionAsync's clean-tracker guard would throw.
                if (_deps.Context.ChangeTracker.HasChanges())
                    await _deps.Context.SaveChangesAsync();
            });
        }

        /// <summary>
        /// Lifecycle hook called before deleting a list of Label entities.
        /// Override this to add custom validation or business logic before batch deletion.
        /// </summary>
        /// <param name="listForDelete">The list of entity IDs being deleted</param>
        public virtual Task OnBeforeLabelListDelete(List<int> listForDelete) => Task.CompletedTask;

        /// <summary>
        /// Lifecycle hook called after deleting a list of Label entities (cascades included),
        /// still inside the delete transaction — queries observe the post-delete state, and anything
        /// written here commits or rolls back atomically with the delete.
        /// Override this to recompute denormalized aggregates or stage post-delete work.
        /// </summary>
        /// <param name="deletedIds">The list of entity IDs that were deleted</param>
        /// <example>
        /// public override async Task OnAfterLabelListDelete(List&lt;int&gt; deletedIds)
        /// {
        ///     await RecalculateAggregatesAsync(); // reads the post-delete state
        /// }
        /// </example>
        public virtual Task OnAfterLabelListDelete(List<int> deletedIds) => Task.CompletedTask;

        /// <summary>
        /// Deletes multiple Label entities with cascade delete handling for dependent entities.
        /// </summary>
        /// <param name="listForDelete_1">The list of entity IDs to delete</param>
        public async virtual Task DeleteLabelList(List<int> listForDelete_1)
        {
            await _deps.Context.WithTransactionAsync(async () =>
            {
                await OnBeforeLabelListDelete(listForDelete_1);

                // Persist writes the hook staged (e.g. IOutbox.Enqueue) as part of this
                // transaction; the next step (untracked cascade delete, or the commit) won't
                // flush them and WithTransactionAsync's clean-tracker guard would throw.
                if (_deps.Context.ChangeTracker.HasChanges())
                    await _deps.Context.SaveChangesAsync();



                await DeleteEntitiesAsync<Label, int>(listForDelete_1);

                await OnAfterLabelListDelete(listForDelete_1);

                // Persist writes the hook staged (e.g. IOutbox.Enqueue) as part of this
                // transaction; the next step (untracked cascade delete, or the commit) won't
                // flush them and WithTransactionAsync's clean-tracker guard would throw.
                if (_deps.Context.ChangeTracker.HasChanges())
                    await _deps.Context.SaveChangesAsync();
            });
        }

        #endregion

        #region One To Many

        /// <summary>
        /// Retrieves namebook DTOs for BoardLane entities in a many-to-many relationship with Label.
        /// </summary>
        /// <param name="id">The ID of the Label entity</param>
        /// <returns>List of NamebookDTO containing ID and DisplayName</returns>
        public async virtual Task<List<NamebookDTO<long>>> GetLanesNamebookListForLabel(int id)
        {
            return await _deps.Context.WithTransactionAsync(async () =>
            {
                return await _deps.Context.DbSet<BoardLane>()
                    .AsNoTracking()
                    .Where(x => x.Labels.Any(x => x.Id == id))
                    .Select(x => new NamebookDTO<long>
                    {
                        Id = x.Id,
                        DisplayName = x.Name,
                    })
                    .ToListAsync();
            });
        }

        /// <summary>
        /// Retrieves IDs of BoardLane entities in a many-to-many relationship with Label.
        /// </summary>
        /// <param name="id">The ID of the Label entity</param>
        /// <returns>List of entity IDs</returns>
        public async virtual Task<List<long>> GetLanesIdsForLabel(int id)
        {
            return await _deps.Context.WithTransactionAsync(async () =>
            {
                return await _deps.Context.DbSet<BoardLane>()
                    .AsNoTracking()
                    .Where(x => x.Labels.Any(x => x.Id == id))
                    .Select(x => x.Id)
                    .ToListAsync();
            });
        }

        /// <summary>
        /// Retrieves BoardLane entities in a many-to-many relationship with Label.
        /// </summary>
        /// <param name="id">The ID of the Label entity</param>
        /// <returns>List of BoardLane entities</returns>
        public async virtual Task<List<BoardLane>> GetLanesForLabel(int id)
        {
            return await _deps.Context.WithTransactionAsync(async () =>
            {
                return await _deps.Context.DbSet<BoardLane>()
                    .Where(x => x.Labels.Any(x => x.Id == id))
                    .ToListAsync();
            });
        }

        /// <summary>
        /// Updates the many-to-many relationship between Label and BoardLane entities.
        /// Adds new associations and removes unselected ones.
        /// </summary>
        /// <param name="id">The ID of the Label entity</param>
        /// <param name="selectedIds">List of selected BoardLane IDs</param>
        public async virtual Task UpdateLanesForLabel(int id, List<long> selectedIds)
        {
            if (selectedIds == null)
                return;

            List<long> selectedIdsHelper = selectedIds.ToList();

            await _deps.Context.WithTransactionAsync(async () =>
            {
                // FT: Not doing authorization here, because we can not figure out here if we are updating while inserting object (eg. User), or updating object, we will always get the id which is not 0 here.

                var entity = await GetInstanceAsync<Label, int>(id, null); // FT: Version will always be checked before or after this method

                foreach (BoardLane item in entity.Lanes.ToList())
                {
                    if (selectedIdsHelper.Contains(item.Id))
                        selectedIdsHelper.Remove(item.Id);
                    else
                        entity.Lanes.Remove(item);
                }

                var listToInsert = await _deps.Context.DbSet<BoardLane>().Where(x => selectedIdsHelper.Contains(x.Id)).ToListAsync();

                entity.Lanes.AddRange(listToInsert);
                await _deps.Context.SaveChangesAsync();
            });
        }

        /// <summary>
        /// Lazy loads selected IDs for many-to-many relationship with pagination support.
        /// IMPORTANT: The query must be ordered by the same field as the table data for correct results.
        /// </summary>
        /// <param name="filterDTO">Filter and pagination parameters</param>
        /// <param name="query">The base query (must be ordered)</param>
        /// <returns>LazyLoadSelectedIdsResultDTO containing selected IDs and total count</returns>
        public async virtual Task<LazyLoadSelectedIdsResultDTO<long>> LazyLoadSelectedLanesIdsForLabel(FilterDTO filterDTO, IQueryable<BoardLane> query)
        {
            LazyLoadSelectedIdsResultDTO<long> lazyLoadSelectedIdsResultDTO = new();

            query = query
                .Skip(filterDTO.First)
                .Take(filterDTO.Rows)
                .Where(x => x.Labels
                    .Any(x => x.Id == filterDTO.AdditionalFilterIdInt));

            await _deps.Context.WithTransactionAsync(async () =>
            {
                var boardLaneService = _deps.ServiceProvider.GetRequiredService<BoardLaneServiceGenerated>();
                var paginationResult = await boardLaneService.GetPaginatedBoardLaneResult(filterDTO, query);

                lazyLoadSelectedIdsResultDTO.SelectedIds = await paginationResult.Query
                    .Select(x => x.Id)
                    .ToListAsync();

                int count = await _deps.Context.DbSet<BoardLane>()
                    .Where(x => x.Labels
                        .Any(x => x.Id == filterDTO.AdditionalFilterIdInt))
                    .CountAsync();

                lazyLoadSelectedIdsResultDTO.TotalRecordsSelected = count;
            });

            return lazyLoadSelectedIdsResultDTO;
        }



        #endregion

    }
}