//HintName: BoardLaneService.generated.cs
// <auto-generated/>
#nullable disable

using TestApp.Business.ValidationRules;
using TestApp.Business.DataMappers;
using TestApp.Business.DTO;
using TestApp.Business.Entities;
using TestApp.Business.Enums;
using TestApp.Business.ExcelProperties;
using TestApp.Business.Filtering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Localization;
using System.Data;
using FluentValidation;
using Spiderly.Security.Services;
using Spiderly.Security.Interfaces;
using Spiderly.Shared.Excel;
using Spiderly.Shared.Interfaces;
using Spiderly.Shared.Services;
using Spiderly.Shared.Classes;
using Spiderly.Shared.DTO;
using Spiderly.Shared.Extensions;
using Spiderly.Shared.Exceptions;
using Spiderly.Shared.Helpers;
using Mapster;
using Microsoft.AspNetCore.Http;

namespace TestApp.Business.Services
{
    /// <summary>
    /// Generated service for the BoardLane entity. Override lifecycle hooks
    /// by creating a <c>BoardLaneService</c> class that inherits from this class.
    /// </summary>
    public class BoardLaneServiceGenerated : ServiceBase
    {
        protected readonly EntityServiceDependencies _deps;


        public BoardLaneServiceGenerated(EntityServiceDependencies deps) : base(deps.Context, deps.Localizer)
        {
            _deps = deps;

        }

        #region Read

        /// <summary>
        /// Retrieves the complete MainUIFormDTO for BoardLane, including the entity DTO and all related collections (one-to-many, many-to-many).
        /// </summary>
        /// <param name="id">The ID of the BoardLane entity</param>
        /// <returns>BoardLaneMainUIFormDTO containing the entity DTO and related data</returns>
        public async virtual Task<BoardLaneMainUIFormDTO> GetBoardLaneMainUIFormDTO(long id)
        {
            return await _deps.Context.WithTransactionAsync(async () =>
            {
                var result = new BoardLaneMainUIFormDTO
                {
                    BoardLaneDTO = await GetBoardLaneDTO(id),
                    LabelsIds = await GetLabelsIdsForBoardLane(id),
                    MembersNamebookDTOList = await GetMembersNamebookListForBoardLane(id),
                };

                await OnAfterGetBoardLaneMainUIFormDTO(result);

                return result;
            });
        }

        /// <summary>
        /// Lifecycle hook called after retrieving BoardLane MainUIFormDTO.
        /// Override this method to enrich the MainUIFormDTO with additional data (e.g., computed fields, extra queries).
        /// This method runs inside a database transaction.
        /// </summary>
        /// <example>
        /// protected override async Task OnAfterGetBoardLaneMainUIFormDTO(BoardLaneMainUIFormDTO mainUIFormDTO)
        /// {
        ///     mainUIFormDTO.CustomProperty = await _deps.Context.DbSet&lt;OtherEntity&gt;().Where(x => x.BoardLaneId == mainUIFormDTO.BoardLaneDTO.Id).CountAsync();
        /// }
        /// </example>
        /// <param name="mainUIFormDTO">The MainUIFormDTO that was just constructed with entity and related data</param>
        protected virtual Task OnAfterGetBoardLaneMainUIFormDTO(BoardLaneMainUIFormDTO mainUIFormDTO) => Task.CompletedTask;

        /// <summary>
        /// Retrieves a single BoardLane entity as a DTO with blob data populated.
        /// </summary>
        /// <param name="id">The ID of the BoardLane entity</param>
        /// <returns>BoardLaneDTO with all blob properties populated</returns>
        public async virtual Task<BoardLaneDTO> GetBoardLaneDTO(long id)
        {
            return await _deps.Context.WithTransactionAsync(async () =>
            {
                var dto = await _deps.Context.DbSet<BoardLane>()
                    .AsNoTracking()
                    .Where(x => x.Id == id).ProjectToType<BoardLaneDTO>(Mapper.BoardLaneProjectToConfig())
                    .SingleOrDefaultAsync();

                if (dto == null)
                    throw new BusinessException(_deps.Localizer["EntityDoesNotExistInDatabase"]);



                return dto;
            });
        }

        /// <summary>
        /// Retrieves a paginated list of BoardLane entities.
        /// </summary>
        /// <param name="filterDTO">Filter and pagination parameters</param>
        /// <param name="query">The base query to paginate</param>
        /// <returns>PaginatedResult containing the query and total record count</returns>
        public async virtual Task<PaginatedResult<BoardLane>> GetPaginatedBoardLaneResult(FilterDTO filterDTO, IQueryable<BoardLane> query)
        {
            return await _deps.Context.WithTransactionAsync(async () =>
            {
                return await PaginatedResultGenerator.Build(query.AsNoTracking(), filterDTO);
            });
        }

        /// <summary>
        /// Retrieves a paginated list of BoardLane DTOs with blob data populated.
        /// </summary>
        /// <param name="filterDTO">Filter and pagination parameters</param>
        /// <param name="query">The base query to paginate</param>
        /// <returns>PaginatedResultDTO containing BoardLaneDTO list and total record count</returns>
        public async virtual Task<PaginatedResultDTO<BoardLaneDTO>> GetPaginatedBoardLaneList(FilterDTO filterDTO, IQueryable<BoardLane> query)
        {
            PaginatedResult<BoardLane> paginationResult = new();
            List<BoardLaneDTO> dtoList = null!;

            await _deps.Context.WithTransactionAsync(async () =>
            {
                paginationResult = await GetPaginatedBoardLaneResult(filterDTO, query);

                dtoList = await paginationResult.Query
                    .Skip(filterDTO.First)
                    .Take(filterDTO.Rows)
                    .ProjectToType<BoardLaneDTO>(Mapper.BoardLaneProjectToConfig())
                    .ToListAsync();


            });

            return new PaginatedResultDTO<BoardLaneDTO> { Data = dtoList, TotalRecords = paginationResult.TotalRecords };
        }

        /// <summary>
        /// Exports a filtered list of BoardLane entities to Excel format.
        /// </summary>
        /// <param name="filterDTO">Filter parameters for the export</param>
        /// <param name="query">The base query to export</param>
        /// <param name="cancellationToken">Cancellation token</param>
        /// <returns>Excel file as byte array</returns>
        public async virtual Task<byte[]> ExportBoardLaneListToExcel(FilterDTO filterDTO, IQueryable<BoardLane> query, CancellationToken cancellationToken = default)
        {
            IQueryable<BoardLaneDTO> exportQuery = null!;

            await _deps.Context.WithTransactionAsync(async () =>
            {
                PaginatedResult<BoardLane> paginationResult = await GetPaginatedBoardLaneResult(filterDTO, query);
                int maxRows = _deps.ExcelSettings.ExcelExportMaxRows;
                exportQuery = paginationResult.Query
                    .OrderBy(x => x.Id)
                    .Take(maxRows)
                    .ProjectToType<BoardLaneDTO>(Mapper.BoardLaneExcelProjectToConfig());
            });

            string[] excelPropertiesToExclude = ExcelPropertiesToExclude.GetHeadersToExclude(new BoardLaneDTO());
            return await _deps.ExcelService.FillReportTemplateAsync(
                exportQuery.AsAsyncEnumerable(),
                excelPropertiesToExclude,
                _deps.Localizer,
                cancellationToken);
        }

        /// <summary>
        /// Retrieves a list of BoardLane entities without pagination.
        /// </summary>
        /// <param name="query">The query to execute</param>
        /// <returns>List of BoardLane entities</returns>
        public async virtual Task<List<BoardLane>> GetBoardLaneList(IQueryable<BoardLane> query)
        {
            return await _deps.Context.WithTransactionAsync(async () =>
            {
                var result = await query
                    .ToListAsync();

                return result;
            });
        }

        /// <summary>
        /// Retrieves a list of BoardLane DTOs without pagination, with blob data populated.
        /// </summary>
        /// <param name="query">The query to execute</param>
        /// <returns>List of BoardLaneDTO with blob properties populated</returns>
        public async virtual Task<List<BoardLaneDTO>> GetBoardLaneDTOList(IQueryable<BoardLane> query)
        {
            return await _deps.Context.WithTransactionAsync(async () =>
            {
                var dtoList = await query
                    .AsNoTracking()
                    .ProjectToType<BoardLaneDTO>(Mapper.BoardLaneToDTOConfig())
                    .ToListAsync();



                return dtoList;
            });
        }

        /// <summary>
        /// Retrieves autocomplete suggestions for the Board many-to-one relationship in BoardLane.
        /// </summary>
        /// <param name="limit">Maximum number of results to return</param>
        /// <param name="filter">Text filter for Name</param>
        /// <param name="query">Base query for Board entities</param>
        /// <returns>List of NamebookDTO containing ID and DisplayName</returns>
        public async virtual Task<List<NamebookDTO<long>>> GetBoardAutocompleteListForBoardLane(
            int limit,
            string filter,
            IQueryable<Board> query
        )
        {
            return await _deps.Context.WithTransactionAsync(async () =>
            {
                if (!string.IsNullOrEmpty(filter))
                    query = query.Where(x => x.Name!.ToLower().Contains(filter.ToLower()));

                var result = await query
                    .AsNoTracking()
                    .Take(limit)
                    .Select(x => new NamebookDTO<long>
                    {
                        Id = x.Id,
                        DisplayName = x.Name,
                    })
                    .ToListAsync();

                return result;
            });
        }
        /// <summary>
        /// Retrieves dropdown options for the Labels many-to-one relationship in BoardLane.
        /// </summary>
        /// <param name="query">Base query for Label entities</param>
        /// <returns>List of NamebookDTO containing ID and DisplayName</returns>
        public async virtual Task<List<NamebookDTO<int>>> GetLabelsDropdownListForBoardLane(
            IQueryable<Label> query
        )
        {
            return await _deps.Context.WithTransactionAsync(async () =>
            {
                var result = await query
                    .AsNoTracking()
                    .Select(x => new NamebookDTO<int>
                    {
                        Id = x.Id,
                        DisplayName = x.Name,
                    })
                    .ToListAsync();

                return result;
            });
        }
        /// <summary>
        /// Retrieves autocomplete suggestions for the Members many-to-one relationship in BoardLane.
        /// </summary>
        /// <param name="limit">Maximum number of results to return</param>
        /// <param name="filter">Text filter for Name</param>
        /// <param name="query">Base query for Member entities</param>
        /// <returns>List of NamebookDTO containing ID and DisplayName</returns>
        public async virtual Task<List<NamebookDTO<long>>> GetMembersAutocompleteListForBoardLane(
            int limit,
            string filter,
            IQueryable<Member> query
        )
        {
            return await _deps.Context.WithTransactionAsync(async () =>
            {
                if (!string.IsNullOrEmpty(filter))
                    query = query.Where(x => x.Name!.ToLower().Contains(filter.ToLower()));

                var result = await query
                    .AsNoTracking()
                    .Take(limit)
                    .Select(x => new NamebookDTO<long>
                    {
                        Id = x.Id,
                        DisplayName = x.Name,
                    })
                    .ToListAsync();

                return result;
            });
        }


        #endregion

        #region Save

        /// <summary>
        /// Saves a BoardLane entity and returns the complete MainUIFormDTO including all related collections.
        /// Handles insert/update logic, many-to-many relationships, and ordered one-to-many collections.
        /// </summary>
        /// <param name="saveBodyDTO">The SaveBodyDTO containing entity data and related selections</param>
        /// <param name="authorizeUpdate">Whether to perform authorization check for Update operation</param>
        /// <param name="authorizeInsert">Whether to perform authorization check for Insert operation</param>
        /// <returns>BoardLaneMainUIFormDTO with saved data and updated collections</returns>
        public virtual async Task<BoardLaneMainUIFormDTO> SaveBoardLaneAndReturnMainUIFormDTO(BoardLaneSaveBodyDTO saveBodyDTO, bool authorizeUpdate, bool authorizeInsert)
        {
            new BoardLaneSaveBodyDTOValidationRules().ValidateAndThrow(saveBodyDTO);

            return await _deps.Context.WithTransactionAsync(async () =>
            {
                await OnBeforeSaveBoardLaneAndReturnMainUIFormDTO(saveBodyDTO);

                var savedDTO = await SaveBoardLaneAndReturnDTO(saveBodyDTO.BoardLaneDTO!, authorizeUpdate, authorizeInsert);


                await UpdateLabelsForBoardLane(savedDTO.Id, saveBodyDTO.SelectedLabelsIds);
                await UpdateMembersForBoardLane(savedDTO.Id, saveBodyDTO.SelectedMembersNamebookDTOList.Select(x => x.Id).ToList());



                var result = new BoardLaneMainUIFormDTO
                {
                    BoardLaneDTO = savedDTO,

                    LabelsIds = saveBodyDTO.SelectedLabelsIds,
                    MembersNamebookDTOList = saveBodyDTO.SelectedMembersNamebookDTOList,

                };

                await OnAfterSaveBoardLaneAndReturnMainUIFormDTO(saveBodyDTO, result);

                return result;
            });
        }




        /// <summary>
        /// Lifecycle hook called before saving BoardLane with MainUIFormDTO.
        /// Override this method to add custom validation or modify the SaveBodyDTO.
        /// This method runs inside a database transaction.
        /// </summary>
        /// <param name="saveBodyDTO">The SaveBodyDTO containing entity and related data</param>
        protected virtual Task OnBeforeSaveBoardLaneAndReturnMainUIFormDTO(BoardLaneSaveBodyDTO saveBodyDTO) => Task.CompletedTask;

        /// <summary>
        /// Lifecycle hook called after saving BoardLane and after updating related collections.
        /// Override this method to add custom business logic after the main entity is saved.
        /// This method runs inside a database transaction.
        /// </summary>
        /// <param name="saveBodyDTO">The original SaveBodyDTO</param>
        /// <param name="mainUIFormDTO">The save result and DTO sent to the UI</param>
        protected virtual Task OnAfterSaveBoardLaneAndReturnMainUIFormDTO(BoardLaneSaveBodyDTO saveBodyDTO, BoardLaneMainUIFormDTO mainUIFormDTO) => Task.CompletedTask;

        /// <summary>
        /// Saves a BoardLane entity and returns the DTO with blob data populated.
        /// </summary>
        /// <param name="saveDTO">The DTO containing entity data to save</param>
        /// <param name="authorizeUpdate">Whether to perform authorization check for Update operation</param>
        /// <param name="authorizeInsert">Whether to perform authorization check for Insert operation</param>
        /// <returns>Saved BoardLaneDTO with blob properties populated</returns>
        public async virtual Task<BoardLaneDTO> SaveBoardLaneAndReturnDTO(BoardLaneDTO saveDTO, bool authorizeUpdate, bool authorizeInsert)
        {
            return await _deps.Context.WithTransactionAsync(async () =>
            {
                var poco = await SaveBoardLane(saveDTO, authorizeUpdate, authorizeInsert);

                var dto = poco.Adapt<BoardLaneDTO>(Mapper.BoardLaneToDTOConfig());



                return dto;
            });
        }

        /// <summary>
        /// Core save method that handles both insert and update operations for BoardLane.
        /// Validates the DTO, maps to entity, handles many-to-one relationships, and manages blob deletion.
        /// </summary>
        /// <param name="dto">The DTO containing entity data to save</param>
        /// <param name="authorizeUpdate">Whether to perform authorization check for Update operation</param>
        /// <param name="authorizeInsert">Whether to perform authorization check for Insert operation</param>
        /// <returns>Saved BoardLane entity</returns>
        public async virtual Task<BoardLane> SaveBoardLane(BoardLaneDTO dto, bool authorizeUpdate, bool authorizeInsert)
        {
            BoardLaneDTOValidationRules validationRules = new BoardLaneDTOValidationRules();
            validationRules.ValidateAndThrow(dto);

            BoardLane poco = null!;
            await _deps.Context.WithTransactionAsync(async () =>
            {
                await OnBeforeBoardLaneIsMapped(dto);
                DbSet<BoardLane> dbSet = _deps.Context.DbSet<BoardLane>();

                if (dto.Id > 0)
                {
                    if (authorizeUpdate)
                    {
                        await _deps.AuthorizationService.AuthorizeBoardLaneUpdateAndThrow(dto);
                    }

                    poco = await GetInstanceAsync<BoardLane, long>(dto.Id, dto.Version);
                    await OnBeforeBoardLaneUpdate(poco, dto);
                    dto.Adapt(poco, Mapper.BoardLaneDTOToEntityConfig());
                    dbSet.Update(poco);
                }
                else
                {
                    if (authorizeInsert)
                    {
                        await _deps.AuthorizationService.AuthorizeBoardLaneInsertAndThrow(dto);
                    }

                    poco = dto.Adapt<BoardLane>(Mapper.BoardLaneDTOToEntityConfig());
                    await OnBeforeBoardLaneInsert(poco, dto);
                    await dbSet.AddAsync(poco);
                }

                if (dto.BoardId > 0)
                {
                    poco.Board = await GetInstanceAsync<Board, long>(dto.BoardId!.Value, null);
                }
                else
                {
                    var _ = poco.Board; // HACK
                    poco.Board = null!;
                }

                await _deps.Context.SaveChangesAsync();






            });

            return poco;
        }

        /// <summary>
        /// Lifecycle hook called before the BoardLaneDTO is mapped to the entity.
        /// Override this method to add custom validation or modify the DTO before mapping.
        /// This method runs inside a database transaction.
        /// </summary>
        /// <param name="boardLaneDTO">The DTO about to be mapped</param>
        protected virtual Task OnBeforeBoardLaneIsMapped(BoardLaneDTO boardLaneDTO) => Task.CompletedTask;

        /// <summary>
        /// Lifecycle hook called before updating an existing BoardLane entity.
        /// Override this method to add custom business logic during updates.
        /// This method runs inside a database transaction.
        /// </summary>
        /// <param name="boardLane">The existing entity being updated</param>
        /// <param name="boardLaneDTO">The DTO containing new data</param>
        protected virtual Task OnBeforeBoardLaneUpdate(BoardLane boardLane, BoardLaneDTO boardLaneDTO) => Task.CompletedTask;

        /// <summary>
        /// Lifecycle hook called before inserting a new BoardLane entity.
        /// Override this method to add custom business logic during inserts.
        /// This method runs inside a database transaction.
        /// </summary>
        /// <param name="boardLane">The new entity being inserted</param>
        /// <param name="boardLaneDTO">The DTO containing the data</param>
        protected virtual Task OnBeforeBoardLaneInsert(BoardLane boardLane, BoardLaneDTO boardLaneDTO) => Task.CompletedTask;





        #endregion

        #region Delete

        /// <summary>
        /// Per-id variant of the pre-delete hook. By default forwards to
        /// <see cref="OnBeforeBoardLaneListDelete"/> with a one-element list, so override
        /// only the list hook unless single-id and batch flows genuinely diverge.
        /// </summary>
        /// <param name="id">The ID of the entity being deleted</param>
        public virtual Task OnBeforeBoardLaneDelete(long id) =>
            OnBeforeBoardLaneListDelete(id.StructToList());

        /// <summary>
        /// Per-id variant of the post-delete hook. By default forwards to
        /// <see cref="OnAfterBoardLaneListDelete"/> with a one-element list, so override
        /// only the list hook unless single-id and batch flows genuinely diverge.
        /// </summary>
        /// <param name="id">The ID of the entity that was deleted</param>
        public virtual Task OnAfterBoardLaneDelete(long id) =>
            OnAfterBoardLaneListDelete(id.StructToList());

        /// <summary>
        /// Deletes a single BoardLane entity with cascade delete handling for dependent entities.
        /// </summary>
        /// <param name="id">The ID of the entity to delete</param>
        public async virtual Task DeleteBoardLane(long id)
        {
            await _deps.Context.WithTransactionAsync(async () =>
            {
                await OnBeforeBoardLaneDelete(id);

                // Persist writes the hook staged (e.g. IOutbox.Enqueue) as part of this
                // transaction; the next step (untracked cascade delete, or the commit) won't
                // flush them and WithTransactionAsync's clean-tracker guard would throw.
                if (_deps.Context.ChangeTracker.HasChanges())
                    await _deps.Context.SaveChangesAsync();

                List<long> listForDelete_1 = id.StructToList();



                await DeleteEntityAsync<BoardLane, long>(id);

                await OnAfterBoardLaneDelete(id);

                // Persist writes the hook staged (e.g. IOutbox.Enqueue) as part of this
                // transaction; the next step (untracked cascade delete, or the commit) won't
                // flush them and WithTransactionAsync's clean-tracker guard would throw.
                if (_deps.Context.ChangeTracker.HasChanges())
                    await _deps.Context.SaveChangesAsync();
            });
        }

        /// <summary>
        /// Lifecycle hook called before deleting a list of BoardLane entities.
        /// Override this to add custom validation or business logic before batch deletion.
        /// </summary>
        /// <param name="listForDelete">The list of entity IDs being deleted</param>
        public virtual Task OnBeforeBoardLaneListDelete(List<long> listForDelete) => Task.CompletedTask;

        /// <summary>
        /// Lifecycle hook called after deleting a list of BoardLane entities (cascades included),
        /// still inside the delete transaction — queries observe the post-delete state, and anything
        /// written here commits or rolls back atomically with the delete.
        /// Override this to recompute denormalized aggregates or stage post-delete work.
        /// </summary>
        /// <param name="deletedIds">The list of entity IDs that were deleted</param>
        /// <example>
        /// public override async Task OnAfterBoardLaneListDelete(List&lt;long&gt; deletedIds)
        /// {
        ///     await RecalculateAggregatesAsync(); // reads the post-delete state
        /// }
        /// </example>
        public virtual Task OnAfterBoardLaneListDelete(List<long> deletedIds) => Task.CompletedTask;

        /// <summary>
        /// Deletes multiple BoardLane entities with cascade delete handling for dependent entities.
        /// </summary>
        /// <param name="listForDelete_1">The list of entity IDs to delete</param>
        public async virtual Task DeleteBoardLaneList(List<long> listForDelete_1)
        {
            await _deps.Context.WithTransactionAsync(async () =>
            {
                await OnBeforeBoardLaneListDelete(listForDelete_1);

                // Persist writes the hook staged (e.g. IOutbox.Enqueue) as part of this
                // transaction; the next step (untracked cascade delete, or the commit) won't
                // flush them and WithTransactionAsync's clean-tracker guard would throw.
                if (_deps.Context.ChangeTracker.HasChanges())
                    await _deps.Context.SaveChangesAsync();



                await DeleteEntitiesAsync<BoardLane, long>(listForDelete_1);

                await OnAfterBoardLaneListDelete(listForDelete_1);

                // Persist writes the hook staged (e.g. IOutbox.Enqueue) as part of this
                // transaction; the next step (untracked cascade delete, or the commit) won't
                // flush them and WithTransactionAsync's clean-tracker guard would throw.
                if (_deps.Context.ChangeTracker.HasChanges())
                    await _deps.Context.SaveChangesAsync();
            });
        }

        #endregion

        #region One To Many

        /// <summary>
        /// Retrieves namebook DTOs for Label entities in a many-to-many relationship with BoardLane.
        /// </summary>
        /// <param name="id">The ID of the BoardLane entity</param>
        /// <returns>List of NamebookDTO containing ID and DisplayName</returns>
        public async virtual Task<List<NamebookDTO<int>>> GetLabelsNamebookListForBoardLane(long id)
        {
            return await _deps.Context.WithTransactionAsync(async () =>
            {
                return await _deps.Context.DbSet<Label>()
                    .AsNoTracking()
                    .Where(x => x.Lanes.Any(x => x.Id == id))
                    .Select(x => new NamebookDTO<int>
                    {
                        Id = x.Id,
                        DisplayName = x.Name,
                    })
                    .ToListAsync();
            });
        }

        /// <summary>
        /// Retrieves IDs of Label entities in a many-to-many relationship with BoardLane.
        /// </summary>
        /// <param name="id">The ID of the BoardLane entity</param>
        /// <returns>List of entity IDs</returns>
        public async virtual Task<List<int>> GetLabelsIdsForBoardLane(long id)
        {
            return await _deps.Context.WithTransactionAsync(async () =>
            {
                return await _deps.Context.DbSet<Label>()
                    .AsNoTracking()
                    .Where(x => x.Lanes.Any(x => x.Id == id))
                    .Select(x => x.Id)
                    .ToListAsync();
            });
        }

        /// <summary>
        /// Retrieves Label entities in a many-to-many relationship with BoardLane.
        /// </summary>
        /// <param name="id">The ID of the BoardLane entity</param>
        /// <returns>List of Label entities</returns>
        public async virtual Task<List<Label>> GetLabelsForBoardLane(long id)
        {
            return await _deps.Context.WithTransactionAsync(async () =>
            {
                return await _deps.Context.DbSet<Label>()
                    .Where(x => x.Lanes.Any(x => x.Id == id))
                    .ToListAsync();
            });
        }

        /// <summary>
        /// Updates the many-to-many relationship between BoardLane and Label entities.
        /// Adds new associations and removes unselected ones.
        /// </summary>
        /// <param name="id">The ID of the BoardLane entity</param>
        /// <param name="selectedIds">List of selected Label IDs</param>
        public async virtual Task UpdateLabelsForBoardLane(long id, List<int> selectedIds)
        {
            if (selectedIds == null)
                return;

            List<int> selectedIdsHelper = selectedIds.ToList();

            await _deps.Context.WithTransactionAsync(async () =>
            {
                // FT: Not doing authorization here, because we can not figure out here if we are updating while inserting object (eg. User), or updating object, we will always get the id which is not 0 here.

                var entity = await GetInstanceAsync<BoardLane, long>(id, null); // FT: Version will always be checked before or after this method

                foreach (Label item in entity.Labels.ToList())
                {
                    if (selectedIdsHelper.Contains(item.Id))
                        selectedIdsHelper.Remove(item.Id);
                    else
                        entity.Labels.Remove(item);
                }

                var listToInsert = await _deps.Context.DbSet<Label>().Where(x => selectedIdsHelper.Contains(x.Id)).ToListAsync();

                entity.Labels.AddRange(listToInsert);
                await _deps.Context.SaveChangesAsync();
            });
        }

        /// <summary>
        /// Lazy loads selected IDs for many-to-many relationship with pagination support.
        /// IMPORTANT: The query must be ordered by the same field as the table data for correct results.
        /// </summary>
        /// <param name="filterDTO">Filter and pagination parameters</param>
        /// <param name="query">The base query (must be ordered)</param>
        /// <returns>LazyLoadSelectedIdsResultDTO containing selected IDs and total count</returns>
        public async virtual Task<LazyLoadSelectedIdsResultDTO<int>> LazyLoadSelectedLabelsIdsForBoardLane(FilterDTO filterDTO, IQueryable<Label> query)
        {
            LazyLoadSelectedIdsResultDTO<int> lazyLoadSelectedIdsResultDTO = new();

            query = query
                .Skip(filterDTO.First)
                .Take(filterDTO.Rows)
                .Where(x => x.Lanes
                    .Any(x => x.Id == filterDTO.AdditionalFilterIdLong));

            await _deps.Context.WithTransactionAsync(async () =>
            {
                var labelService = _deps.ServiceProvider.GetRequiredService<LabelServiceGenerated>();
                var paginationResult = await labelService.GetPaginatedLabelResult(filterDTO, query);

                lazyLoadSelectedIdsResultDTO.SelectedIds = await paginationResult.Query
                    .Select(x => x.Id)
                    .ToListAsync();

                int count = await _deps.Context.DbSet<Label>()
                    .Where(x => x.Lanes
                        .Any(x => x.Id == filterDTO.AdditionalFilterIdLong))
                    .CountAsync();

                lazyLoadSelectedIdsResultDTO.TotalRecordsSelected = count;
            });

            return lazyLoadSelectedIdsResultDTO;
        }



        /// <summary>
        /// Retrieves namebook DTOs for Member entities in a many-to-many relationship with BoardLane.
        /// </summary>
        /// <param name="id">The ID of the BoardLane entity</param>
        /// <returns>List of NamebookDTO containing ID and DisplayName</returns>
        public async virtual Task<List<NamebookDTO<long>>> GetMembersNamebookListForBoardLane(long id)
        {
            return await _deps.Context.WithTransactionAsync(async () =>
            {
                return await _deps.Context.DbSet<Member>()
                    .AsNoTracking()
                    .Where(x => x.Lanes.Any(x => x.Id == id))
                    .Select(x => new NamebookDTO<long>
                    {
                        Id = x.Id,
                        DisplayName = x.Name,
                    })
                    .ToListAsync();
            });
        }

        /// <summary>
        /// Retrieves IDs of Member entities in a many-to-many relationship with BoardLane.
        /// </summary>
        /// <param name="id">The ID of the BoardLane entity</param>
        /// <returns>List of entity IDs</returns>
        public async virtual Task<List<long>> GetMembersIdsForBoardLane(long id)
        {
            return await _deps.Context.WithTransactionAsync(async () =>
            {
                return await _deps.Context.DbSet<Member>()
                    .AsNoTracking()
                    .Where(x => x.Lanes.Any(x => x.Id == id))
                    .Select(x => x.Id)
                    .ToListAsync();
            });
        }

        /// <summary>
        /// Retrieves Member entities in a many-to-many relationship with BoardLane.
        /// </summary>
        /// <param name="id">The ID of the BoardLane entity</param>
        /// <returns>List of Member entities</returns>
        public async virtual Task<List<Member>> GetMembersForBoardLane(long id)
        {
            return await _deps.Context.WithTransactionAsync(async () =>
            {
                return await _deps.Context.DbSet<Member>()
                    .Where(x => x.Lanes.Any(x => x.Id == id))
                    .ToListAsync();
            });
        }

        /// <summary>
        /// Updates the many-to-many relationship between BoardLane and Member entities.
        /// Adds new associations and removes unselected ones.
        /// </summary>
        /// <param name="id">The ID of the BoardLane entity</param>
        /// <param name="selectedIds">List of selected Member IDs</param>
        public async virtual Task UpdateMembersForBoardLane(long id, List<long> selectedIds)
        {
            if (selectedIds == null)
                return;

            List<long> selectedIdsHelper = selectedIds.ToList();

            await _deps.Context.WithTransactionAsync(async () =>
            {
                // FT: Not doing authorization here, because we can not figure out here if we are updating while inserting object (eg. User), or updating object, we will always get the id which is not 0 here.

                var entity = await GetInstanceAsync<BoardLane, long>(id, null); // FT: Version will always be checked before or after this method

                foreach (Member item in entity.Members.ToList())
                {
                    if (selectedIdsHelper.Contains(item.Id))
                        selectedIdsHelper.Remove(item.Id);
                    else
                        entity.Members.Remove(item);
                }

                var listToInsert = await _deps.Context.DbSet<Member>().Where(x => selectedIdsHelper.Contains(x.Id)).ToListAsync();

                entity.Members.AddRange(listToInsert);
                await _deps.Context.SaveChangesAsync();
            });
        }

        /// <summary>
        /// Lazy loads selected IDs for many-to-many relationship with pagination support.
        /// IMPORTANT: The query must be ordered by the same field as the table data for correct results.
        /// </summary>
        /// <param name="filterDTO">Filter and pagination parameters</param>
        /// <param name="query">The base query (must be ordered)</param>
        /// <returns>LazyLoadSelectedIdsResultDTO containing selected IDs and total count</returns>
        public async virtual Task<LazyLoadSelectedIdsResultDTO<long>> LazyLoadSelectedMembersIdsForBoardLane(FilterDTO filterDTO, IQueryable<Member> query)
        {
            LazyLoadSelectedIdsResultDTO<long> lazyLoadSelectedIdsResultDTO = new();

            query = query
                .Skip(filterDTO.First)
                .Take(filterDTO.Rows)
                .Where(x => x.Lanes
                    .Any(x => x.Id == filterDTO.AdditionalFilterIdLong));

            await _deps.Context.WithTransactionAsync(async () =>
            {
                var memberService = _deps.ServiceProvider.GetRequiredService<MemberServiceGenerated>();
                var paginationResult = await memberService.GetPaginatedMemberResult(filterDTO, query);

                lazyLoadSelectedIdsResultDTO.SelectedIds = await paginationResult.Query
                    .Select(x => x.Id)
                    .ToListAsync();

                int count = await _deps.Context.DbSet<Member>()
                    .Where(x => x.Lanes
                        .Any(x => x.Id == filterDTO.AdditionalFilterIdLong))
                    .CountAsync();

                lazyLoadSelectedIdsResultDTO.TotalRecordsSelected = count;
            });

            return lazyLoadSelectedIdsResultDTO;
        }



        #endregion

    }
}