//HintName: BoardService.generated.cs
// <auto-generated/>
#nullable disable

using TestApp.Business.ValidationRules;
using TestApp.Business.DataMappers;
using TestApp.Business.DTO;
using TestApp.Business.Entities;
using TestApp.Business.Enums;
using TestApp.Business.ExcelProperties;
using TestApp.Business.Filtering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Localization;
using System.Data;
using FluentValidation;
using Spiderly.Security.Services;
using Spiderly.Security.Interfaces;
using Spiderly.Shared.Excel;
using Spiderly.Shared.Interfaces;
using Spiderly.Shared.Services;
using Spiderly.Shared.Classes;
using Spiderly.Shared.DTO;
using Spiderly.Shared.Extensions;
using Spiderly.Shared.Exceptions;
using Spiderly.Shared.Helpers;
using Mapster;
using Microsoft.AspNetCore.Http;

namespace TestApp.Business.Services
{
    /// <summary>
    /// Generated service for the Board entity. Override lifecycle hooks
    /// by creating a <c>BoardService</c> class that inherits from this class.
    /// </summary>
    public class BoardServiceGenerated : ServiceBase
    {
        protected readonly EntityServiceDependencies _deps;


        public BoardServiceGenerated(EntityServiceDependencies deps) : base(deps.Context, deps.Localizer)
        {
            _deps = deps;

        }

        #region Read

        /// <summary>
        /// Retrieves the complete MainUIFormDTO for Board, including the entity DTO and all related collections (one-to-many, many-to-many).
        /// </summary>
        /// <param name="id">The ID of the Board entity</param>
        /// <returns>BoardMainUIFormDTO containing the entity DTO and related data</returns>
        public async virtual Task<BoardMainUIFormDTO> GetBoardMainUIFormDTO(long id)
        {
            return await _deps.Context.WithTransactionAsync(async () =>
            {
                var result = new BoardMainUIFormDTO
                {
                    BoardDTO = await GetBoardDTO(id),
                    OrderedLanesMainUIFormDTO = await GetOrderedLanesForBoard(id),
                };

                await OnAfterGetBoardMainUIFormDTO(result);

                return result;
            });
        }

        /// <summary>
        /// Lifecycle hook called after retrieving Board MainUIFormDTO.
        /// Override this method to enrich the MainUIFormDTO with additional data (e.g., computed fields, extra queries).
        /// This method runs inside a database transaction.
        /// </summary>
        /// <example>
        /// protected override async Task OnAfterGetBoardMainUIFormDTO(BoardMainUIFormDTO mainUIFormDTO)
        /// {
        ///     mainUIFormDTO.CustomProperty = await _deps.Context.DbSet&lt;OtherEntity&gt;().Where(x => x.BoardId == mainUIFormDTO.BoardDTO.Id).CountAsync();
        /// }
        /// </example>
        /// <param name="mainUIFormDTO">The MainUIFormDTO that was just constructed with entity and related data</param>
        protected virtual Task OnAfterGetBoardMainUIFormDTO(BoardMainUIFormDTO mainUIFormDTO) => Task.CompletedTask;

        /// <summary>
        /// Retrieves a single Board entity as a DTO with blob data populated.
        /// </summary>
        /// <param name="id">The ID of the Board entity</param>
        /// <returns>BoardDTO with all blob properties populated</returns>
        public async virtual Task<BoardDTO> GetBoardDTO(long id)
        {
            return await _deps.Context.WithTransactionAsync(async () =>
            {
                var dto = await _deps.Context.DbSet<Board>()
                    .AsNoTracking()
                    .Where(x => x.Id == id).ProjectToType<BoardDTO>(Mapper.BoardProjectToConfig())
                    .SingleOrDefaultAsync();

                if (dto == null)
                    throw new BusinessException(_deps.Localizer["EntityDoesNotExistInDatabase"]);



                return dto;
            });
        }

        /// <summary>
        /// Retrieves a paginated list of Board entities.
        /// </summary>
        /// <param name="filterDTO">Filter and pagination parameters</param>
        /// <param name="query">The base query to paginate</param>
        /// <returns>PaginatedResult containing the query and total record count</returns>
        public async virtual Task<PaginatedResult<Board>> GetPaginatedBoardResult(FilterDTO filterDTO, IQueryable<Board> query)
        {
            return await _deps.Context.WithTransactionAsync(async () =>
            {
                return await PaginatedResultGenerator.Build(query.AsNoTracking(), filterDTO);
            });
        }

        /// <summary>
        /// Retrieves a paginated list of Board DTOs with blob data populated.
        /// </summary>
        /// <param name="filterDTO">Filter and pagination parameters</param>
        /// <param name="query">The base query to paginate</param>
        /// <returns>PaginatedResultDTO containing BoardDTO list and total record count</returns>
        public async virtual Task<PaginatedResultDTO<BoardDTO>> GetPaginatedBoardList(FilterDTO filterDTO, IQueryable<Board> query)
        {
            PaginatedResult<Board> paginationResult = new();
            List<BoardDTO> dtoList = null!;

            await _deps.Context.WithTransactionAsync(async () =>
            {
                paginationResult = await GetPaginatedBoardResult(filterDTO, query);

                dtoList = await paginationResult.Query
                    .Skip(filterDTO.First)
                    .Take(filterDTO.Rows)
                    .ProjectToType<BoardDTO>(Mapper.BoardProjectToConfig())
                    .ToListAsync();


            });

            return new PaginatedResultDTO<BoardDTO> { Data = dtoList, TotalRecords = paginationResult.TotalRecords };
        }

        /// <summary>
        /// Exports a filtered list of Board entities to Excel format.
        /// </summary>
        /// <param name="filterDTO">Filter parameters for the export</param>
        /// <param name="query">The base query to export</param>
        /// <param name="cancellationToken">Cancellation token</param>
        /// <returns>Excel file as byte array</returns>
        public async virtual Task<byte[]> ExportBoardListToExcel(FilterDTO filterDTO, IQueryable<Board> query, CancellationToken cancellationToken = default)
        {
            IQueryable<BoardDTO> exportQuery = null!;

            await _deps.Context.WithTransactionAsync(async () =>
            {
                PaginatedResult<Board> paginationResult = await GetPaginatedBoardResult(filterDTO, query);
                int maxRows = _deps.ExcelSettings.ExcelExportMaxRows;
                exportQuery = paginationResult.Query
                    .OrderBy(x => x.Id)
                    .Take(maxRows)
                    .ProjectToType<BoardDTO>(Mapper.BoardExcelProjectToConfig());
            });

            string[] excelPropertiesToExclude = ExcelPropertiesToExclude.GetHeadersToExclude(new BoardDTO());
            return await _deps.ExcelService.FillReportTemplateAsync(
                exportQuery.AsAsyncEnumerable(),
                excelPropertiesToExclude,
                _deps.Localizer,
                cancellationToken);
        }

        /// <summary>
        /// Retrieves a list of Board entities without pagination.
        /// </summary>
        /// <param name="query">The query to execute</param>
        /// <returns>List of Board entities</returns>
        public async virtual Task<List<Board>> GetBoardList(IQueryable<Board> query)
        {
            return await _deps.Context.WithTransactionAsync(async () =>
            {
                var result = await query
                    .ToListAsync();

                return result;
            });
        }

        /// <summary>
        /// Retrieves a list of Board DTOs without pagination, with blob data populated.
        /// </summary>
        /// <param name="query">The query to execute</param>
        /// <returns>List of BoardDTO with blob properties populated</returns>
        public async virtual Task<List<BoardDTO>> GetBoardDTOList(IQueryable<Board> query)
        {
            return await _deps.Context.WithTransactionAsync(async () =>
            {
                var dtoList = await query
                    .AsNoTracking()
                    .ProjectToType<BoardDTO>(Mapper.BoardToDTOConfig())
                    .ToListAsync();



                return dtoList;
            });
        }



        #endregion

        #region Save

        /// <summary>
        /// Saves a Board entity and returns the complete MainUIFormDTO including all related collections.
        /// Handles insert/update logic, many-to-many relationships, and ordered one-to-many collections.
        /// </summary>
        /// <param name="saveBodyDTO">The SaveBodyDTO containing entity data and related selections</param>
        /// <param name="authorizeUpdate">Whether to perform authorization check for Update operation</param>
        /// <param name="authorizeInsert">Whether to perform authorization check for Insert operation</param>
        /// <returns>BoardMainUIFormDTO with saved data and updated collections</returns>
        public virtual async Task<BoardMainUIFormDTO> SaveBoardAndReturnMainUIFormDTO(BoardSaveBodyDTO saveBodyDTO, bool authorizeUpdate, bool authorizeInsert)
        {
            new BoardSaveBodyDTOValidationRules().ValidateAndThrow(saveBodyDTO);

            return await _deps.Context.WithTransactionAsync(async () =>
            {
                await OnBeforeSaveBoardAndReturnMainUIFormDTO(saveBodyDTO);

                var savedDTO = await SaveBoardAndReturnDTO(saveBodyDTO.BoardDTO!, authorizeUpdate, authorizeInsert);

                var savedOrderedLanesMainUIFormDTO = await UpdateOrderedLanesForBoard(savedDTO.Id, saveBodyDTO.OrderedLanesSaveBodyDTO);




                var result = new BoardMainUIFormDTO
                {
                    BoardDTO = savedDTO,
                    OrderedLanesMainUIFormDTO = savedOrderedLanesMainUIFormDTO,


                };

                await OnAfterSaveBoardAndReturnMainUIFormDTO(saveBodyDTO, result);

                return result;
            });
        }

        /// <summary>
        /// Updates ordered child entities for a one-to-many relationship.
        /// Deletes items not in the list, then saves each kept item through the child's own
        /// SaveBoardLaneAndReturnMainUIFormDTO — so the child's related collections and
        /// save hooks behave identically whether it is saved standalone or inline through its parent —
        /// stamping OrderNumber from the list position.
        /// </summary>
        /// <param name="id">The ID of the parent Board entity</param>
        /// <param name="orderedItemsDTO">List of SaveBodyDTOs in the desired order</param>
        /// <returns>List of saved BoardLaneMainUIFormDTO in order</returns>
        public async virtual Task<List<BoardLaneMainUIFormDTO>> UpdateOrderedLanesForBoard(long id, List<BoardLaneSaveBodyDTO> orderedItemsDTO)
        {
            // A public entry point validates its own input, exactly as SaveBoardLane does on its
            // first line. This method is public virtual and reachable without the parent's SaveBodyDTO
            // validation ever running, and its nested BoardLaneDTO is dereferenced immediately
            // below — so without this a payload omitting one is an ArgumentNullException 500 instead of a 422
            // carrying fieldErrors. The .NotEmpty() rule on that nested DTO is what the `!` below rests on.
            BoardLaneSaveBodyDTOValidationRules orderedItemValidationRules = new BoardLaneSaveBodyDTOValidationRules();
            foreach (BoardLaneSaveBodyDTO orderedItemDTO in orderedItemsDTO)
                orderedItemValidationRules.ValidateAndThrow(orderedItemDTO);

            var orderedItemIds = orderedItemsDTO.Select(x => x.BoardLaneDTO!.Id).ToList();



            return await _deps.Context.WithTransactionAsync(async () =>
            {
                await _deps.Context.DbSet<BoardLane>().Where(x => x.BoardId == id && orderedItemIds.Contains(x.Id) == false).ExecuteDeleteAsync();

                var childService = _deps.ServiceProvider.GetRequiredService<BoardLaneServiceGenerated>();
                var savedOrderedItemsDTO = new List<BoardLaneMainUIFormDTO>();

                for (int i = 0; i < orderedItemsDTO.Count; i++)
                {
                    var saveBodyDTO = orderedItemsDTO[i];
                    var DTO = saveBodyDTO.BoardLaneDTO!;

                    DTO.BoardId = id;
                    DTO.OrderNumber = i + 1;

                    // Delegate to the child's standalone MainUIForm save so both save paths are the same
                    // code by construction: the child's collections (multi-control M2M selections, complex
                    // M2M lists, nested ordered children), its OnBefore/OnAfterSave hooks, and the
                    // response's id lists (the form repopulates from them) cannot drift between the
                    // standalone page and the inline-on-parent page.
                    savedOrderedItemsDTO.Add(await childService.SaveBoardLaneAndReturnMainUIFormDTO(saveBodyDTO, false, false));
                }

                return savedOrderedItemsDTO;
            });
        }


        /// <summary>
        /// Lifecycle hook called before saving Board with MainUIFormDTO.
        /// Override this method to add custom validation or modify the SaveBodyDTO.
        /// This method runs inside a database transaction.
        /// </summary>
        /// <param name="saveBodyDTO">The SaveBodyDTO containing entity and related data</param>
        protected virtual Task OnBeforeSaveBoardAndReturnMainUIFormDTO(BoardSaveBodyDTO saveBodyDTO) => Task.CompletedTask;

        /// <summary>
        /// Lifecycle hook called after saving Board and after updating related collections.
        /// Override this method to add custom business logic after the main entity is saved.
        /// This method runs inside a database transaction.
        /// </summary>
        /// <param name="saveBodyDTO">The original SaveBodyDTO</param>
        /// <param name="mainUIFormDTO">The save result and DTO sent to the UI</param>
        protected virtual Task OnAfterSaveBoardAndReturnMainUIFormDTO(BoardSaveBodyDTO saveBodyDTO, BoardMainUIFormDTO mainUIFormDTO) => Task.CompletedTask;

        /// <summary>
        /// Saves a Board entity and returns the DTO with blob data populated.
        /// </summary>
        /// <param name="saveDTO">The DTO containing entity data to save</param>
        /// <param name="authorizeUpdate">Whether to perform authorization check for Update operation</param>
        /// <param name="authorizeInsert">Whether to perform authorization check for Insert operation</param>
        /// <returns>Saved BoardDTO with blob properties populated</returns>
        public async virtual Task<BoardDTO> SaveBoardAndReturnDTO(BoardDTO saveDTO, bool authorizeUpdate, bool authorizeInsert)
        {
            return await _deps.Context.WithTransactionAsync(async () =>
            {
                var poco = await SaveBoard(saveDTO, authorizeUpdate, authorizeInsert);

                var dto = poco.Adapt<BoardDTO>(Mapper.BoardToDTOConfig());



                return dto;
            });
        }

        /// <summary>
        /// Core save method that handles both insert and update operations for Board.
        /// Validates the DTO, maps to entity, handles many-to-one relationships, and manages blob deletion.
        /// </summary>
        /// <param name="dto">The DTO containing entity data to save</param>
        /// <param name="authorizeUpdate">Whether to perform authorization check for Update operation</param>
        /// <param name="authorizeInsert">Whether to perform authorization check for Insert operation</param>
        /// <returns>Saved Board entity</returns>
        public async virtual Task<Board> SaveBoard(BoardDTO dto, bool authorizeUpdate, bool authorizeInsert)
        {
            BoardDTOValidationRules validationRules = new BoardDTOValidationRules();
            validationRules.ValidateAndThrow(dto);

            Board poco = null!;
            await _deps.Context.WithTransactionAsync(async () =>
            {
                await OnBeforeBoardIsMapped(dto);
                DbSet<Board> dbSet = _deps.Context.DbSet<Board>();

                if (dto.Id > 0)
                {
                    if (authorizeUpdate)
                    {
                        await _deps.AuthorizationService.AuthorizeBoardUpdateAndThrow(dto);
                    }

                    poco = await GetInstanceAsync<Board, long>(dto.Id, dto.Version);
                    await OnBeforeBoardUpdate(poco, dto);
                    dto.Adapt(poco, Mapper.BoardDTOToEntityConfig());
                    dbSet.Update(poco);
                }
                else
                {
                    if (authorizeInsert)
                    {
                        await _deps.AuthorizationService.AuthorizeBoardInsertAndThrow(dto);
                    }

                    poco = dto.Adapt<Board>(Mapper.BoardDTOToEntityConfig());
                    await OnBeforeBoardInsert(poco, dto);
                    await dbSet.AddAsync(poco);
                }



                await _deps.Context.SaveChangesAsync();






            });

            return poco;
        }

        /// <summary>
        /// Lifecycle hook called before the BoardDTO is mapped to the entity.
        /// Override this method to add custom validation or modify the DTO before mapping.
        /// This method runs inside a database transaction.
        /// </summary>
        /// <param name="boardDTO">The DTO about to be mapped</param>
        protected virtual Task OnBeforeBoardIsMapped(BoardDTO boardDTO) => Task.CompletedTask;

        /// <summary>
        /// Lifecycle hook called before updating an existing Board entity.
        /// Override this method to add custom business logic during updates.
        /// This method runs inside a database transaction.
        /// </summary>
        /// <param name="board">The existing entity being updated</param>
        /// <param name="boardDTO">The DTO containing new data</param>
        protected virtual Task OnBeforeBoardUpdate(Board board, BoardDTO boardDTO) => Task.CompletedTask;

        /// <summary>
        /// Lifecycle hook called before inserting a new Board entity.
        /// Override this method to add custom business logic during inserts.
        /// This method runs inside a database transaction.
        /// </summary>
        /// <param name="board">The new entity being inserted</param>
        /// <param name="boardDTO">The DTO containing the data</param>
        protected virtual Task OnBeforeBoardInsert(Board board, BoardDTO boardDTO) => Task.CompletedTask;





        #endregion

        #region Delete

        /// <summary>
        /// Per-id variant of the pre-delete hook. By default forwards to
        /// <see cref="OnBeforeBoardListDelete"/> with a one-element list, so override
        /// only the list hook unless single-id and batch flows genuinely diverge.
        /// </summary>
        /// <param name="id">The ID of the entity being deleted</param>
        public virtual Task OnBeforeBoardDelete(long id) =>
            OnBeforeBoardListDelete(id.StructToList());

        /// <summary>
        /// Per-id variant of the post-delete hook. By default forwards to
        /// <see cref="OnAfterBoardListDelete"/> with a one-element list, so override
        /// only the list hook unless single-id and batch flows genuinely diverge.
        /// </summary>
        /// <param name="id">The ID of the entity that was deleted</param>
        public virtual Task OnAfterBoardDelete(long id) =>
            OnAfterBoardListDelete(id.StructToList());

        /// <summary>
        /// Deletes a single Board entity with cascade delete handling for dependent entities.
        /// </summary>
        /// <param name="id">The ID of the entity to delete</param>
        public async virtual Task DeleteBoard(long id)
        {
            await _deps.Context.WithTransactionAsync(async () =>
            {
                await OnBeforeBoardDelete(id);

                // Persist writes the hook staged (e.g. IOutbox.Enqueue) as part of this
                // transaction; the next step (untracked cascade delete, or the commit) won't
                // flush them and WithTransactionAsync's clean-tracker guard would throw.
                if (_deps.Context.ChangeTracker.HasChanges())
                    await _deps.Context.SaveChangesAsync();

                List<long> listForDelete_1 = id.StructToList();

                var boardLaneListForDeleteBecauseBoard_2 = await _deps.Context.DbSet<BoardLane>()
                    .AsNoTracking()
                    .Where(x => listForDelete_1.Contains(x.BoardId))
                    .Select(x => x.Id)
                    .ToListAsync();

                await _deps.Context.DbSet<BoardLane>()
                    .Where(x => boardLaneListForDeleteBecauseBoard_2.Contains(x.Id))
                    .ExecuteDeleteAsync();

                await DeleteEntityAsync<Board, long>(id);

                await OnAfterBoardDelete(id);

                // Persist writes the hook staged (e.g. IOutbox.Enqueue) as part of this
                // transaction; the next step (untracked cascade delete, or the commit) won't
                // flush them and WithTransactionAsync's clean-tracker guard would throw.
                if (_deps.Context.ChangeTracker.HasChanges())
                    await _deps.Context.SaveChangesAsync();
            });
        }

        /// <summary>
        /// Lifecycle hook called before deleting a list of Board entities.
        /// Override this to add custom validation or business logic before batch deletion.
        /// </summary>
        /// <param name="listForDelete">The list of entity IDs being deleted</param>
        public virtual Task OnBeforeBoardListDelete(List<long> listForDelete) => Task.CompletedTask;

        /// <summary>
        /// Lifecycle hook called after deleting a list of Board entities (cascades included),
        /// still inside the delete transaction — queries observe the post-delete state, and anything
        /// written here commits or rolls back atomically with the delete.
        /// Override this to recompute denormalized aggregates or stage post-delete work.
        /// </summary>
        /// <param name="deletedIds">The list of entity IDs that were deleted</param>
        /// <example>
        /// public override async Task OnAfterBoardListDelete(List&lt;long&gt; deletedIds)
        /// {
        ///     await RecalculateAggregatesAsync(); // reads the post-delete state
        /// }
        /// </example>
        public virtual Task OnAfterBoardListDelete(List<long> deletedIds) => Task.CompletedTask;

        /// <summary>
        /// Deletes multiple Board entities with cascade delete handling for dependent entities.
        /// </summary>
        /// <param name="listForDelete_1">The list of entity IDs to delete</param>
        public async virtual Task DeleteBoardList(List<long> listForDelete_1)
        {
            await _deps.Context.WithTransactionAsync(async () =>
            {
                await OnBeforeBoardListDelete(listForDelete_1);

                // Persist writes the hook staged (e.g. IOutbox.Enqueue) as part of this
                // transaction; the next step (untracked cascade delete, or the commit) won't
                // flush them and WithTransactionAsync's clean-tracker guard would throw.
                if (_deps.Context.ChangeTracker.HasChanges())
                    await _deps.Context.SaveChangesAsync();

                var boardLaneListForDeleteBecauseBoard_2 = await _deps.Context.DbSet<BoardLane>()
                    .AsNoTracking()
                    .Where(x => listForDelete_1.Contains(x.BoardId))
                    .Select(x => x.Id)
                    .ToListAsync();

                await _deps.Context.DbSet<BoardLane>()
                    .Where(x => boardLaneListForDeleteBecauseBoard_2.Contains(x.Id))
                    .ExecuteDeleteAsync();

                await DeleteEntitiesAsync<Board, long>(listForDelete_1);

                await OnAfterBoardListDelete(listForDelete_1);

                // Persist writes the hook staged (e.g. IOutbox.Enqueue) as part of this
                // transaction; the next step (untracked cascade delete, or the commit) won't
                // flush them and WithTransactionAsync's clean-tracker guard would throw.
                if (_deps.Context.ChangeTracker.HasChanges())
                    await _deps.Context.SaveChangesAsync();
            });
        }

        #endregion

        #region One To Many

        /// <summary>
        /// Retrieves namebook DTOs for BoardLane entities related to a Board.
        /// </summary>
        /// <param name="id">The ID of the Board entity</param>
        /// <returns>List of NamebookDTO containing ID and DisplayName</returns>
        public async virtual Task<List<NamebookDTO<long>>> GetLanesNamebookListForBoard(long id)
        {
            return await _deps.Context.WithTransactionAsync(async () =>
            {
                return await _deps.Context.DbSet<BoardLane>()
                    .AsNoTracking()
                    .Where(x => x.BoardId == id)
                    .Select(x => new NamebookDTO<long>
                    {
                        Id = x.Id,
                        DisplayName = x.Name,
                    })
                    .ToListAsync();
            });
        }

        /// <summary>
        /// Retrieves all BoardLane entities related to a Board via the Lanes one-to-many relationship.
        /// </summary>
        /// <param name="id">The ID of the Board entity</param>
        /// <returns>List of BoardLane entities</returns>
        public async virtual Task<List<BoardLane>> GetLanesForBoard(long id)
        {
            return await _deps.Context.WithTransactionAsync(async () =>
            {
                return await _deps.Context.DbSet<BoardLane>()
                    .Where(x => x.BoardId == id)
                    .ToListAsync();
            });
        }

        /// <summary>
        /// Retrieves ordered child entities for a one-to-many relationship (requires [UIOrderedOneToMany] attribute).
        /// Returns complete MainUIFormDTOs ordered by OrderNumber.
        /// </summary>
        /// <param name="id">The ID of the Board entity</param>
        /// <returns>List of BoardLaneMainUIFormDTO ordered by OrderNumber</returns>
        public async virtual Task<List<BoardLaneMainUIFormDTO>> GetOrderedLanesForBoard(long id)
        {
            return await _deps.Context.WithTransactionAsync(async () =>
            {
                List<BoardLaneMainUIFormDTO> mainUIFormDTOList = new();

                var ids = await _deps.Context.DbSet<BoardLane>()
                    .AsNoTracking()
                    .Where(x => x.BoardId == id)
                    .OrderBy(x => x.OrderNumber)
                    .Select(x => x.Id)
                    .ToListAsync();

                var boardLaneService = _deps.ServiceProvider.GetRequiredService<BoardLaneServiceGenerated>();
                foreach (var id in ids)
                    mainUIFormDTOList.Add(await boardLaneService.GetBoardLaneMainUIFormDTO(id));

                return mainUIFormDTOList;
            });
        }

        #endregion

    }
}