//HintName: TagService.generated.cs
// <auto-generated/>
#nullable disable

using TestApp.Business.ValidationRules;
using TestApp.Business.DataMappers;
using TestApp.Business.DTO;
using TestApp.Business.Entities;
using TestApp.Business.Enums;
using TestApp.Business.ExcelProperties;
using TestApp.Business.Filtering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Localization;
using System.Data;
using FluentValidation;
using Spiderly.Security.Services;
using Spiderly.Security.Interfaces;
using Spiderly.Shared.Excel;
using Spiderly.Shared.Interfaces;
using Spiderly.Shared.Services;
using Spiderly.Shared.Classes;
using Spiderly.Shared.DTO;
using Spiderly.Shared.Extensions;
using Spiderly.Shared.Exceptions;
using Spiderly.Shared.Helpers;
using Mapster;
using Microsoft.AspNetCore.Http;

namespace TestApp.Business.Services
{
    /// <summary>
    /// Generated service for the Tag entity. Override lifecycle hooks
    /// by creating a <c>TagService</c> class that inherits from this class.
    /// </summary>
    public class TagServiceGenerated : ServiceBase
    {
        protected readonly EntityServiceDependencies _deps;


        public TagServiceGenerated(EntityServiceDependencies deps) : base(deps.Context, deps.Localizer)
        {
            _deps = deps;

        }

        #region Read

        /// <summary>
        /// Retrieves the complete MainUIFormDTO for Tag, including the entity DTO and all related collections (one-to-many, many-to-many).
        /// </summary>
        /// <param name="id">The ID of the Tag entity</param>
        /// <returns>TagMainUIFormDTO containing the entity DTO and related data</returns>
        public async virtual Task<TagMainUIFormDTO> GetTagMainUIFormDTO(long id)
        {
            return await _deps.Context.WithTransactionAsync(async () =>
            {
                var result = new TagMainUIFormDTO
                {
                    TagDTO = await GetTagDTO(id),
                };

                await OnAfterGetTagMainUIFormDTO(result);

                return result;
            });
        }

        /// <summary>
        /// Lifecycle hook called after retrieving Tag MainUIFormDTO.
        /// Override this method to enrich the MainUIFormDTO with additional data (e.g., computed fields, extra queries).
        /// This method runs inside a database transaction.
        /// </summary>
        /// <example>
        /// protected override async Task OnAfterGetTagMainUIFormDTO(TagMainUIFormDTO mainUIFormDTO)
        /// {
        ///     mainUIFormDTO.CustomProperty = await _deps.Context.DbSet&lt;OtherEntity&gt;().Where(x => x.TagId == mainUIFormDTO.TagDTO.Id).CountAsync();
        /// }
        /// </example>
        /// <param name="mainUIFormDTO">The MainUIFormDTO that was just constructed with entity and related data</param>
        protected virtual Task OnAfterGetTagMainUIFormDTO(TagMainUIFormDTO mainUIFormDTO) => Task.CompletedTask;

        /// <summary>
        /// Retrieves a single Tag entity as a DTO with blob data populated.
        /// </summary>
        /// <param name="id">The ID of the Tag entity</param>
        /// <returns>TagDTO with all blob properties populated</returns>
        public async virtual Task<TagDTO> GetTagDTO(long id)
        {
            return await _deps.Context.WithTransactionAsync(async () =>
            {
                var dto = await _deps.Context.DbSet<Tag>()
                    .AsNoTracking()
                    .Where(x => x.Id == id).ProjectToType<TagDTO>(Mapper.TagProjectToConfig())
                    .SingleOrDefaultAsync();

                if (dto == null)
                    throw new BusinessException(_deps.Localizer["EntityDoesNotExistInDatabase"]);



                return dto;
            });
        }

        /// <summary>
        /// Retrieves a paginated list of Tag entities.
        /// </summary>
        /// <param name="filterDTO">Filter and pagination parameters</param>
        /// <param name="query">The base query to paginate</param>
        /// <returns>PaginatedResult containing the query and total record count</returns>
        public async virtual Task<PaginatedResult<Tag>> GetPaginatedTagResult(FilterDTO filterDTO, IQueryable<Tag> query)
        {
            return await _deps.Context.WithTransactionAsync(async () =>
            {
                return await PaginatedResultGenerator.Build(query.AsNoTracking(), filterDTO);
            });
        }

        /// <summary>
        /// Retrieves a paginated list of Tag DTOs with blob data populated.
        /// </summary>
        /// <param name="filterDTO">Filter and pagination parameters</param>
        /// <param name="query">The base query to paginate</param>
        /// <returns>PaginatedResultDTO containing TagDTO list and total record count</returns>
        public async virtual Task<PaginatedResultDTO<TagDTO>> GetPaginatedTagList(FilterDTO filterDTO, IQueryable<Tag> query)
        {
            PaginatedResult<Tag> paginationResult = new();
            List<TagDTO> dtoList = null!;

            await _deps.Context.WithTransactionAsync(async () =>
            {
                paginationResult = await GetPaginatedTagResult(filterDTO, query);

                dtoList = await paginationResult.Query
                    .Skip(filterDTO.First)
                    .Take(filterDTO.Rows)
                    .ProjectToType<TagDTO>(Mapper.TagProjectToConfig())
                    .ToListAsync();


            });

            return new PaginatedResultDTO<TagDTO> { Data = dtoList, TotalRecords = paginationResult.TotalRecords };
        }

        /// <summary>
        /// Exports a filtered list of Tag entities to Excel format.
        /// </summary>
        /// <param name="filterDTO">Filter parameters for the export</param>
        /// <param name="query">The base query to export</param>
        /// <param name="cancellationToken">Cancellation token</param>
        /// <returns>Excel file as byte array</returns>
        public async virtual Task<byte[]> ExportTagListToExcel(FilterDTO filterDTO, IQueryable<Tag> query, CancellationToken cancellationToken = default)
        {
            IQueryable<TagDTO> exportQuery = null!;

            await _deps.Context.WithTransactionAsync(async () =>
            {
                PaginatedResult<Tag> paginationResult = await GetPaginatedTagResult(filterDTO, query);
                int maxRows = _deps.ExcelSettings.ExcelExportMaxRows;
                exportQuery = paginationResult.Query
                    .OrderBy(x => x.Id)
                    .Take(maxRows)
                    .ProjectToType<TagDTO>(Mapper.TagExcelProjectToConfig());
            });

            string[] excelPropertiesToExclude = ExcelPropertiesToExclude.GetHeadersToExclude(new TagDTO());
            return await _deps.ExcelService.FillReportTemplateAsync(
                exportQuery.AsAsyncEnumerable(),
                excelPropertiesToExclude,
                _deps.Localizer,
                cancellationToken);
        }

        /// <summary>
        /// Retrieves a list of Tag entities without pagination.
        /// </summary>
        /// <param name="query">The query to execute</param>
        /// <returns>List of Tag entities</returns>
        public async virtual Task<List<Tag>> GetTagList(IQueryable<Tag> query)
        {
            return await _deps.Context.WithTransactionAsync(async () =>
            {
                var result = await query
                    .ToListAsync();

                return result;
            });
        }

        /// <summary>
        /// Retrieves a list of Tag DTOs without pagination, with blob data populated.
        /// </summary>
        /// <param name="query">The query to execute</param>
        /// <returns>List of TagDTO with blob properties populated</returns>
        public async virtual Task<List<TagDTO>> GetTagDTOList(IQueryable<Tag> query)
        {
            return await _deps.Context.WithTransactionAsync(async () =>
            {
                var dtoList = await query
                    .AsNoTracking()
                    .ProjectToType<TagDTO>(Mapper.TagToDTOConfig())
                    .ToListAsync();



                return dtoList;
            });
        }



        #endregion

        #region Save

        /// <summary>
        /// Saves a Tag entity and returns the complete MainUIFormDTO including all related collections.
        /// Handles insert/update logic, many-to-many relationships, and ordered one-to-many collections.
        /// </summary>
        /// <param name="saveBodyDTO">The SaveBodyDTO containing entity data and related selections</param>
        /// <param name="authorizeUpdate">Whether to perform authorization check for Update operation</param>
        /// <param name="authorizeInsert">Whether to perform authorization check for Insert operation</param>
        /// <returns>TagMainUIFormDTO with saved data and updated collections</returns>
        public virtual async Task<TagMainUIFormDTO> SaveTagAndReturnMainUIFormDTO(TagSaveBodyDTO saveBodyDTO, bool authorizeUpdate, bool authorizeInsert)
        {
            new TagSaveBodyDTOValidationRules().ValidateAndThrow(saveBodyDTO);

            return await _deps.Context.WithTransactionAsync(async () =>
            {
                await OnBeforeSaveTagAndReturnMainUIFormDTO(saveBodyDTO);

                var savedDTO = await SaveTagAndReturnDTO(saveBodyDTO.TagDTO!, authorizeUpdate, authorizeInsert);






                var result = new TagMainUIFormDTO
                {
                    TagDTO = savedDTO,



                };

                await OnAfterSaveTagAndReturnMainUIFormDTO(saveBodyDTO, result);

                return result;
            });
        }




        /// <summary>
        /// Lifecycle hook called before saving Tag with MainUIFormDTO.
        /// Override this method to add custom validation or modify the SaveBodyDTO.
        /// This method runs inside a database transaction.
        /// </summary>
        /// <param name="saveBodyDTO">The SaveBodyDTO containing entity and related data</param>
        protected virtual Task OnBeforeSaveTagAndReturnMainUIFormDTO(TagSaveBodyDTO saveBodyDTO) => Task.CompletedTask;

        /// <summary>
        /// Lifecycle hook called after saving Tag and after updating related collections.
        /// Override this method to add custom business logic after the main entity is saved.
        /// This method runs inside a database transaction.
        /// </summary>
        /// <param name="saveBodyDTO">The original SaveBodyDTO</param>
        /// <param name="mainUIFormDTO">The save result and DTO sent to the UI</param>
        protected virtual Task OnAfterSaveTagAndReturnMainUIFormDTO(TagSaveBodyDTO saveBodyDTO, TagMainUIFormDTO mainUIFormDTO) => Task.CompletedTask;

        /// <summary>
        /// Saves a Tag entity and returns the DTO with blob data populated.
        /// </summary>
        /// <param name="saveDTO">The DTO containing entity data to save</param>
        /// <param name="authorizeUpdate">Whether to perform authorization check for Update operation</param>
        /// <param name="authorizeInsert">Whether to perform authorization check for Insert operation</param>
        /// <returns>Saved TagDTO with blob properties populated</returns>
        public async virtual Task<TagDTO> SaveTagAndReturnDTO(TagDTO saveDTO, bool authorizeUpdate, bool authorizeInsert)
        {
            return await _deps.Context.WithTransactionAsync(async () =>
            {
                var poco = await SaveTag(saveDTO, authorizeUpdate, authorizeInsert);

                var dto = poco.Adapt<TagDTO>(Mapper.TagToDTOConfig());



                return dto;
            });
        }

        /// <summary>
        /// Core save method that handles both insert and update operations for Tag.
        /// Validates the DTO, maps to entity, handles many-to-one relationships, and manages blob deletion.
        /// </summary>
        /// <param name="dto">The DTO containing entity data to save</param>
        /// <param name="authorizeUpdate">Whether to perform authorization check for Update operation</param>
        /// <param name="authorizeInsert">Whether to perform authorization check for Insert operation</param>
        /// <returns>Saved Tag entity</returns>
        public async virtual Task<Tag> SaveTag(TagDTO dto, bool authorizeUpdate, bool authorizeInsert)
        {
            TagDTOValidationRules validationRules = new TagDTOValidationRules();
            validationRules.ValidateAndThrow(dto);

            Tag poco = null!;
            await _deps.Context.WithTransactionAsync(async () =>
            {
                await OnBeforeTagIsMapped(dto);
                DbSet<Tag> dbSet = _deps.Context.DbSet<Tag>();

                if (dto.Id > 0)
                {
                    if (authorizeUpdate)
                    {
                        await _deps.AuthorizationService.AuthorizeTagUpdateAndThrow(dto);
                    }

                    poco = await GetInstanceAsync<Tag, long>(dto.Id, dto.Version);
                    await OnBeforeTagUpdate(poco, dto);
                    dto.Adapt(poco, Mapper.TagDTOToEntityConfig());
                    dbSet.Update(poco);
                }
                else
                {
                    if (authorizeInsert)
                    {
                        await _deps.AuthorizationService.AuthorizeTagInsertAndThrow(dto);
                    }

                    poco = dto.Adapt<Tag>(Mapper.TagDTOToEntityConfig());
                    await OnBeforeTagInsert(poco, dto);
                    await dbSet.AddAsync(poco);
                }



                await _deps.Context.SaveChangesAsync();






            });

            return poco;
        }

        /// <summary>
        /// Lifecycle hook called before the TagDTO is mapped to the entity.
        /// Override this method to add custom validation or modify the DTO before mapping.
        /// This method runs inside a database transaction.
        /// </summary>
        /// <param name="tagDTO">The DTO about to be mapped</param>
        protected virtual Task OnBeforeTagIsMapped(TagDTO tagDTO) => Task.CompletedTask;

        /// <summary>
        /// Lifecycle hook called before updating an existing Tag entity.
        /// Override this method to add custom business logic during updates.
        /// This method runs inside a database transaction.
        /// </summary>
        /// <param name="tag">The existing entity being updated</param>
        /// <param name="tagDTO">The DTO containing new data</param>
        protected virtual Task OnBeforeTagUpdate(Tag tag, TagDTO tagDTO) => Task.CompletedTask;

        /// <summary>
        /// Lifecycle hook called before inserting a new Tag entity.
        /// Override this method to add custom business logic during inserts.
        /// This method runs inside a database transaction.
        /// </summary>
        /// <param name="tag">The new entity being inserted</param>
        /// <param name="tagDTO">The DTO containing the data</param>
        protected virtual Task OnBeforeTagInsert(Tag tag, TagDTO tagDTO) => Task.CompletedTask;





        #endregion

        #region Delete

        /// <summary>
        /// Per-id variant of the pre-delete hook. By default forwards to
        /// <see cref="OnBeforeTagListDelete"/> with a one-element list, so override
        /// only the list hook unless single-id and batch flows genuinely diverge.
        /// </summary>
        /// <param name="id">The ID of the entity being deleted</param>
        public virtual Task OnBeforeTagDelete(long id) =>
            OnBeforeTagListDelete(id.StructToList());

        /// <summary>
        /// Per-id variant of the post-delete hook. By default forwards to
        /// <see cref="OnAfterTagListDelete"/> with a one-element list, so override
        /// only the list hook unless single-id and batch flows genuinely diverge.
        /// </summary>
        /// <param name="id">The ID of the entity that was deleted</param>
        public virtual Task OnAfterTagDelete(long id) =>
            OnAfterTagListDelete(id.StructToList());

        /// <summary>
        /// Deletes a single Tag entity with cascade delete handling for dependent entities.
        /// </summary>
        /// <param name="id">The ID of the entity to delete</param>
        public async virtual Task DeleteTag(long id)
        {
            await _deps.Context.WithTransactionAsync(async () =>
            {
                await OnBeforeTagDelete(id);

                // Persist writes the hook staged (e.g. IOutbox.Enqueue) as part of this
                // transaction; the next step (untracked cascade delete, or the commit) won't
                // flush them and WithTransactionAsync's clean-tracker guard would throw.
                if (_deps.Context.ChangeTracker.HasChanges())
                    await _deps.Context.SaveChangesAsync();

                List<long> listForDelete_1 = id.StructToList();



                await DeleteEntityAsync<Tag, long>(id);

                await OnAfterTagDelete(id);

                // Persist writes the hook staged (e.g. IOutbox.Enqueue) as part of this
                // transaction; the next step (untracked cascade delete, or the commit) won't
                // flush them and WithTransactionAsync's clean-tracker guard would throw.
                if (_deps.Context.ChangeTracker.HasChanges())
                    await _deps.Context.SaveChangesAsync();
            });
        }

        /// <summary>
        /// Lifecycle hook called before deleting a list of Tag entities.
        /// Override this to add custom validation or business logic before batch deletion.
        /// </summary>
        /// <param name="listForDelete">The list of entity IDs being deleted</param>
        public virtual Task OnBeforeTagListDelete(List<long> listForDelete) => Task.CompletedTask;

        /// <summary>
        /// Lifecycle hook called after deleting a list of Tag entities (cascades included),
        /// still inside the delete transaction — queries observe the post-delete state, and anything
        /// written here commits or rolls back atomically with the delete.
        /// Override this to recompute denormalized aggregates or stage post-delete work.
        /// </summary>
        /// <param name="deletedIds">The list of entity IDs that were deleted</param>
        /// <example>
        /// public override async Task OnAfterTagListDelete(List&lt;long&gt; deletedIds)
        /// {
        ///     await RecalculateAggregatesAsync(); // reads the post-delete state
        /// }
        /// </example>
        public virtual Task OnAfterTagListDelete(List<long> deletedIds) => Task.CompletedTask;

        /// <summary>
        /// Deletes multiple Tag entities with cascade delete handling for dependent entities.
        /// </summary>
        /// <param name="listForDelete_1">The list of entity IDs to delete</param>
        public async virtual Task DeleteTagList(List<long> listForDelete_1)
        {
            await _deps.Context.WithTransactionAsync(async () =>
            {
                await OnBeforeTagListDelete(listForDelete_1);

                // Persist writes the hook staged (e.g. IOutbox.Enqueue) as part of this
                // transaction; the next step (untracked cascade delete, or the commit) won't
                // flush them and WithTransactionAsync's clean-tracker guard would throw.
                if (_deps.Context.ChangeTracker.HasChanges())
                    await _deps.Context.SaveChangesAsync();



                await DeleteEntitiesAsync<Tag, long>(listForDelete_1);

                await OnAfterTagListDelete(listForDelete_1);

                // Persist writes the hook staged (e.g. IOutbox.Enqueue) as part of this
                // transaction; the next step (untracked cascade delete, or the commit) won't
                // flush them and WithTransactionAsync's clean-tracker guard would throw.
                if (_deps.Context.ChangeTracker.HasChanges())
                    await _deps.Context.SaveChangesAsync();
            });
        }

        #endregion

        #region One To Many



        #endregion

    }
}