// <auto-generated>
//     GENERATED by Spiderly.ZooGenerator — do not hand-edit.
//     Regenerate: tools/regen-metadata.sh (CI and the pre-commit hook fail on drift).
// </auto-generated>
//
// The "type zoo": one entity property per supported shape axis — every scalar in
// SpiderlyTypeRef.ScalarKindByName and a [SpiderlyEnum] enum, in non-nullable and nullable form —
// so the generated C# and Angular TS for every shape is compiled by the real toolchain in the e2e
// job. Derived from the same axis data the production dispatch reads: adding an axis member grows
// this fixture automatically. Relational and blob shapes are covered by the hand-written fixture
// entities (Project, ProjectTask, Product, ...), which carry the semantics a data walk can't invent.
//
// ZooShape lives in the app's default (nullable-oblivious) context; ZooShapeNullable sits under a
// file-level '#nullable enable' and carries the reference-type shapes in NRT-annotated form
// ('string?'), so both source contexts the generators must handle are compiled end-to-end.

using System.ComponentModel.DataAnnotations;
using Spiderly.Shared.Attributes;
using Spiderly.Shared.Attributes.Entity;
using Spiderly.Shared.BaseEntities;
using __APP_NAME__.Business.Enums;

namespace __APP_NAME__.Business.Enums
{
    [SpiderlyEnum]
    public enum ZooCodes
    {
        Alpha = 1,
        Beta = 2,
    }
}

namespace __APP_NAME__.Business.Entities
{
    [SpiderlyEntity]
    [DoNotAuthorize]
    public class ZooShape : BusinessObject<int>
    {
        [DisplayName]
        [Required]
        [StringLength(100, MinimumLength = 1)]
        public string Name { get; set; } = null!;

        public ZooCodes CodesValue { get; set; }

        public ZooCodes? CodesNullableValue { get; set; }

        public DateOnly DateOnlyValue { get; set; }

        public DateOnly? DateOnlyNullableValue { get; set; }

        public DateTime DateTimeValue { get; set; }

        public DateTime? DateTimeNullableValue { get; set; }

        public TimeOnly TimeOnlyValue { get; set; }

        public TimeOnly? TimeOnlyNullableValue { get; set; }

        public bool BoolValue { get; set; }

        public bool? BoolNullableValue { get; set; }

        public byte ByteValue { get; set; }

        public byte? ByteNullableValue { get; set; }

        public decimal DecimalValue { get; set; }

        public decimal? DecimalNullableValue { get; set; }

        public double DoubleValue { get; set; }

        public double? DoubleNullableValue { get; set; }

        public float FloatValue { get; set; }

        public float? FloatNullableValue { get; set; }

        public int IntValue { get; set; }

        public int? IntNullableValue { get; set; }

        public long LongValue { get; set; }

        public long? LongNullableValue { get; set; }

        [StringLength(100)]
        public string? StringValue { get; set; }

        [Required]
        public ZooCodes CodesRequiredValue { get; set; }

        [Required]
        public DateOnly DateOnlyRequiredValue { get; set; }

        [Required]
        public DateTime DateTimeRequiredValue { get; set; }

        [Required]
        public TimeOnly TimeOnlyRequiredValue { get; set; }

        [Required]
        public bool BoolRequiredValue { get; set; }

        [Required]
        public byte ByteRequiredValue { get; set; }

        [Required]
        public decimal DecimalRequiredValue { get; set; }

        [Required]
        public double DoubleRequiredValue { get; set; }

        [Required]
        public float FloatRequiredValue { get; set; }

        [Required]
        public int IntRequiredValue { get; set; }

        [Required]
        public long LongRequiredValue { get; set; }

        [Required]
        [StringLength(100, MinimumLength = 1)]
        public string StringRequiredValue { get; set; } = null!;
    }

#nullable enable

    [SpiderlyEntity]
    [DoNotAuthorize]
    public class ZooShapeNullable : BusinessObject<int>
    {
        [DisplayName]
        [Required]
        [StringLength(100, MinimumLength = 1)]
        public string Name { get; set; } = null!;

        [StringLength(100)]
        public string? StringNullableValue { get; set; }
    }
}
