using System.Text;
using Spiderly.SourceGenerators.Models;

namespace Spiderly.ZooGenerator;

/// <summary>
/// Single source for the "type zoo" e2e fixture: one entity property per supported shape axis —
/// every scalar in <see cref="SpiderlyTypeRef.ScalarKindByName"/> plus a <c>[SpiderlyEnum]</c>
/// enum, each in non-nullable and nullable form. <see cref="Generate"/> renders the fixture
/// entity file the e2e app compiles end-to-end (C#, EF migration, and the generated Angular TS);
/// <see cref="ShapeProperties"/> exposes the same model so unit tests can push the identical
/// property set through the generators' emission seams without duplicating the axis walk.
/// <para>
/// Motivating escape: a nullable enum property emitted <c>prop?: MyEnum?;</c> — invalid
/// TypeScript (TS17019) — and no hand-written fixture entity had one, so it shipped in two
/// releases before a consumer created the first nullable enum. The zoo makes "no fixture had
/// one" structurally impossible for the shape axes: a new axis member grows this fixture (and
/// the e2e's compile coverage) automatically.
/// </para>
/// </summary>
public static class ZooFixtureSource
{
    /// <summary>Enum type name declared by the fixture; also the [SpiderlyEnum] registry entry for tests.</summary>
    public const string EnumTypeName = "ZooCodes";

    /// <summary>
    /// The full shape axis as (C# type, property name) pairs, in the exact order
    /// <see cref="Generate"/> renders them. Nullable variants are generated for value types only —
    /// <c>string?</c> is a reference-type annotation that needs an NRT context the fixture apps
    /// don't enable.
    /// </summary>
    public static IReadOnlyList<(string Type, string Name)> ShapeProperties
    {
        get
        {
            List<(string, string)> properties = new()
            {
                (EnumTypeName, "CodesValue"),
                ($"{EnumTypeName}?", "CodesNullableValue"),
            };

            foreach (string scalar in SpiderlyTypeRef.ScalarKindByName.Keys.OrderBy(x => x, StringComparer.Ordinal))
            {
                string pascal = char.ToUpperInvariant(scalar[0]) + scalar.Substring(1);
                properties.Add((scalar, $"{pascal}Value"));

                if (scalar != "string")
                    properties.Add(($"{scalar}?", $"{pascal}NullableValue"));
            }

            return properties;
        }
    }

    /// <summary>
    /// Renders the complete ZooShapes.cs fixture file (with the e2e __APP_NAME__ placeholder).
    /// LF-normalized regardless of platform/checkout so the drift guards compare byte-identical
    /// output everywhere (same determinism contract as the metadata pipeline).
    /// </summary>
    public static string Generate()
    {
        StringBuilder body = new();

        foreach ((string type, string name) in ShapeProperties)
        {
            body.AppendLine();

            if (type == "string")
                body.AppendLine("        [StringLength(100)]");

            body.AppendLine($"        public {type} {name} {{ get; set; }}");
        }

        return $$"""
// <auto-generated>
//     GENERATED by Spiderly.ZooGenerator — do not hand-edit.
//     Regenerate: tools/regen-metadata.sh (CI and the pre-commit hook fail on drift).
// </auto-generated>
//
// The "type zoo": one entity property per supported shape axis — every scalar in
// SpiderlyTypeRef.ScalarKindByName and a [SpiderlyEnum] enum, in non-nullable and nullable form —
// so the generated C# and Angular TS for every shape is compiled by the real toolchain in the e2e
// job. Derived from the same axis data the production dispatch reads: adding an axis member grows
// this fixture automatically. Relational and blob shapes are covered by the hand-written fixture
// entities (Project, ProjectTask, Product, ...), which carry the semantics a data walk can't invent.

using System.ComponentModel.DataAnnotations;
using Spiderly.Shared.Attributes;
using Spiderly.Shared.Attributes.Entity;
using Spiderly.Shared.BaseEntities;
using __APP_NAME__.Business.Enums;

namespace __APP_NAME__.Business.Enums
{
    [SpiderlyEnum]
    public enum {{EnumTypeName}}
    {
        Alpha = 1,
        Beta = 2,
    }
}

namespace __APP_NAME__.Business.Entities
{
    [SpiderlyEntity]
    [DoNotAuthorize]
    public class ZooShape : BusinessObject<int>
    {
        [DisplayName]
        [Required]
        [StringLength(100, MinimumLength = 1)]
        public string Name { get; set; }
{{body.ToString().TrimEnd('\n', '\r')}}
    }
}
""".Replace("\r\n", "\n") + "\n";
    }
}
