#!/bin/bash
set -euo pipefail

APP_NAME="${1:?Usage: setup.sh <AppName> <AppFolder>}"
APP_FOLDER="${2:?Usage: setup.sh <AppName> <AppFolder>}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

ENTITIES_DIR="$APP_FOLDER/Backend/$APP_NAME.Business/Entities"
INFRA_DIR="$APP_FOLDER/Backend/$APP_NAME.Infrastructure"
LOCAL_SETTINGS="$APP_FOLDER/Backend/$APP_NAME.WebAPI/appsettings.Development.local.json"
E2E_DIR="$APP_FOLDER/Frontend/e2e"
APP_PAGES_DIR="$APP_FOLDER/Frontend/src/app/pages"

echo "=== Spiderly E2E Fixtures Setup ==="
echo "App name: $APP_NAME"
echo "App folder: $APP_FOLDER"

# --- Copy entity files ---
echo "Copying entity files..."
cp "$SCRIPT_DIR/backend/entities/Product.cs" "$ENTITIES_DIR/Product.cs"
cp "$SCRIPT_DIR/backend/entities/User.cs" "$ENTITIES_DIR/User.cs"
cp "$SCRIPT_DIR/backend/entities/TaskCategory.cs" "$ENTITIES_DIR/TaskCategory.cs"
cp "$SCRIPT_DIR/backend/entities/Project.cs" "$ENTITIES_DIR/Project.cs"
cp "$SCRIPT_DIR/backend/entities/ProjectMember.cs" "$ENTITIES_DIR/ProjectMember.cs"
cp "$SCRIPT_DIR/backend/entities/ProjectTask.cs" "$ENTITIES_DIR/ProjectTask.cs"
cp "$SCRIPT_DIR/backend/entities/ProjectTaskWatcher.cs" "$ENTITIES_DIR/ProjectTaskWatcher.cs"
cp "$SCRIPT_DIR/backend/entities/TaskComment.cs" "$ENTITIES_DIR/TaskComment.cs"
cp "$SCRIPT_DIR/backend/entities/ProjectCharter.cs" "$ENTITIES_DIR/ProjectCharter.cs"
cp "$SCRIPT_DIR/backend/entities/TaskAttachment.cs" "$ENTITIES_DIR/TaskAttachment.cs"
# ZooShapes.cs is GENERATED by Spiderly.ZooGenerator (via tools/regen-metadata.sh) — one property
# per supported shape axis, so every shape compiles end-to-end in this suite. Never hand-edit.
cp "$SCRIPT_DIR/backend/entities/ZooShapes.cs" "$ENTITIES_DIR/ZooShapes.cs"

# --- Copy ApplicationDbContext seed overlay ---
# We only override the demo seed data (a partial-class file), never the generated DbContext
# plumbing (constructor / OnModelCreating). This keeps the fixture immune to framework signature
# changes that previously broke the build via a stale full-file copy.
echo "Copying ApplicationDbContext seed overlay..."
cp "$SCRIPT_DIR/backend/infrastructure/ApplicationDbContext.SeedData.cs" "$INFRA_DIR/${APP_NAME}ApplicationDbContext.SeedData.cs"

# --- Replace __APP_NAME__ placeholder in copied .cs files ---
echo "Replacing __APP_NAME__ with $APP_NAME in copied files..."
find "$ENTITIES_DIR" "$INFRA_DIR" -name "*.cs" -exec sed -i "s/__APP_NAME__/$APP_NAME/g" {} +

# --- Copy E2E test helpers ---
echo "Copying E2E test helpers..."
mkdir -p "$E2E_DIR/helpers"
cp "$SCRIPT_DIR/frontend/tests/e2e/helpers/"*.ts "$E2E_DIR/helpers/"

# --- Copy E2E test specs ---
echo "Copying E2E test specs..."
mkdir -p "$E2E_DIR/specs"
cp "$SCRIPT_DIR/frontend/tests/e2e/specs/"*.spec.ts "$E2E_DIR/specs/"

# --- Copy page objects (overwrites base-page.ts) ---
echo "Copying page objects..."
mkdir -p "$E2E_DIR/page-objects"
cp "$SCRIPT_DIR/frontend/tests/e2e/page-objects/"*.ts "$E2E_DIR/page-objects/"

# --- Copy E2E binary fixtures ---
echo "Copying E2E fixtures..."
mkdir -p "$E2E_DIR/fixtures"
cp -r "$SCRIPT_DIR/frontend/tests/e2e/fixtures/." "$E2E_DIR/fixtures/"

# --- Copy Angular list component overrides ---
# Spiderly-cli generates minimal list components (Id column only). Tests that need
# varied filter types replace the generated file with a richer version.
echo "Copying Angular list component overrides..."
cp "$SCRIPT_DIR/frontend/app/product/product-list.component.ts" "$APP_PAGES_DIR/product/product-list.component.ts"

# --- Raise the global rate limit for the whole E2E run ---
# The suite hits the backend from ONE IP and a green run already sits at ~235 of the default
# 240 requests / 60s (Settings.RequestsLimitNumber), so Playwright's 2 retries -- which replay a
# failing test's 40-product seeding -- turn into 429s that fail UNRELATED tests downstream. That
# is what buried the real failure in CI run 33279746074: a boolean-filter regression came back as
# a cascade-delete test failing on a 429. The limiter itself is covered by Spiderly.Shared.Tests
# (GlobalRateLimitPartitionerTests, ApiKeyRateLimitPartitionTests, TrustedCallerRateLimitIntegrationTests),
# so raising it for the app under test costs no coverage. 6000 is TrustedRequestsLimitNumber's
# order of magnitude -- the same shape of caller: our own traffic, generous but finite.
# spiderly init writes this file and Program.cs loads it (launchSettings pins Development), and
# this runs before the backend build, so the patched copy is what ends up in bin/.
echo "Raising the API rate limit for the E2E run..."
tmp_settings="$(mktemp)"
jq '.AppSettings["Spiderly.Shared"].RequestsLimitNumber = 6000' "$LOCAL_SETTINGS" > "$tmp_settings"
mv "$tmp_settings" "$LOCAL_SETTINGS"

echo "=== Fixtures setup complete ==="
