//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soft.Generator.Shared.Terms
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedTerms
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedTerms()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Soft.Generator.Shared.Terms.SharedTerms", typeof(SharedTerms).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This record has been modified or deleted by another user..
        /// </summary>
        public static string ConcurrencyException
        {
            get
            {
                return ResourceManager.GetString("ConcurrencyException", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The record you&apos;re looking for doesn&apos;t exist in database..
        /// </summary>
        public static string EntityDoesNotExistInDatabase
        {
            get
            {
                return ResourceManager.GetString("EntityDoesNotExistInDatabase", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your deletion request couldn&apos;t be completed as the entity doesn&apos;t exist in our database. Maybe it&apos;s already deleted..
        /// </summary>
        public static string EntityDoesNotExistInDatabaseForDeleteRequest
        {
            get
            {
                return ResourceManager.GetString("EntityDoesNotExistInDatabaseForDeleteRequest", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An error occurred in the system, our team has been informed and will fix it as soon as possible. Thank you for your patience. Error code:.
        /// </summary>
        public static string GlobalError
        {
            get
            {
                return ResourceManager.GetString("GlobalError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to sifra.
        /// </summary>
        public static string Password
        {
            get
            {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
    }
}