//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soft.Generator.Shared.Terms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedTerms {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedTerms() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Soft.Generator.Shared.Terms.SharedTerms", typeof(SharedTerms).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An account with the entered email address does not exist. Please check the email address or create a new account..
        /// </summary>
        public static string AuthenticationEmailDoesNotExistException {
            get {
                return ResourceManager.GetString("AuthenticationEmailDoesNotExistException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password. Please try again or reset your password if you&apos;ve forgotten it..
        /// </summary>
        public static string AuthenticationIncorectPasswordException {
            get {
                return ResourceManager.GetString("AuthenticationIncorectPasswordException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This record has been modified or deleted by another user..
        /// </summary>
        public static string ConcurrencyException {
            get {
                return ResourceManager.GetString("ConcurrencyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is disabled, please contact the administrator..
        /// </summary>
        public static string DisabledAccountException {
            get {
                return ResourceManager.GetString("DisabledAccountException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account verification.
        /// </summary>
        public static string EmailAccountVerificationTitle {
            get {
                return ResourceManager.GetString("EmailAccountVerificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record you&apos;re looking for doesn&apos;t exist in database..
        /// </summary>
        public static string EntityDoesNotExistInDatabase {
            get {
                return ResourceManager.GetString("EntityDoesNotExistInDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your deletion request couldn&apos;t be completed as the entity doesn&apos;t exist in our database. Maybe it&apos;s already deleted..
        /// </summary>
        public static string EntityDoesNotExistInDatabaseForDeleteRequest {
            get {
                return ResourceManager.GetString("EntityDoesNotExistInDatabaseForDeleteRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session has expired, please login again..
        /// </summary>
        public static string ExpiredRefreshTokenException {
            get {
                return ResourceManager.GetString("ExpiredRefreshTokenException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your verification code has expired. Please request a new code to continue..
        /// </summary>
        public static string ExpiredVerificationCodeException {
            get {
                return ResourceManager.GetString("ExpiredVerificationCodeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred in the system, our team has been informed and will fix it as soon as possible. Thank you for your patience. Error code:.
        /// </summary>
        public static string GlobalError {
            get {
                return ResourceManager.GetString("GlobalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use the most recent verification code, as multiple codes were sent..
        /// </summary>
        public static string LatestVerificationCodeException {
            get {
                return ResourceManager.GetString("LatestVerificationCodeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string NotificationExcel {
            get {
                return ResourceManager.GetString("NotificationExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account already exists with third-party (eg. Google) authentication. If you want to set up a password as well, please use the &apos;Forgot password?&apos; option to reset it or log in to your profile and add a password..
        /// </summary>
        public static string OnlyThirdPartyAccountButTriedToLoginException {
            get {
                return ResourceManager.GetString("OnlyThirdPartyAccountButTriedToLoginException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An account with the entered email address does not exist. Please check the email address or create a new account..
        /// </summary>
        public static string ResetPasswordEmailDoesNotExistException {
            get {
                return ResourceManager.GetString("ResetPasswordEmailDoesNotExistException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string RoleExcel {
            get {
                return ResourceManager.GetString("RoleExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An account with this email address already exists..
        /// </summary>
        public static string SameEmailAlreadyExistsException {
            get {
                return ResourceManager.GetString("SameEmailAlreadyExistsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t use the application with two different IP addresses at the same time, please login again..
        /// </summary>
        public static string TwoDifferentIpAddressesRefreshException {
            get {
                return ResourceManager.GetString("TwoDifferentIpAddressesRefreshException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have the necessary rights to perform the operation..
        /// </summary>
        public static string UnauthorizedAccessExceptionMessage {
            get {
                return ResourceManager.GetString("UnauthorizedAccessExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string UserExcel {
            get {
                return ResourceManager.GetString("UserExcel", resourceCulture);
            }
        }
    }
}
