<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Version>19.7.6</Version>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <NoWarn>NU1701;1591</NoWarn>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageIcon>spiderly-logo.png</PackageIcon>
    <Authors>Filip Trivan</Authors>
    <Description>Spiderly.Shared package provides shared features that can be used by all other Spiderly packages.</Description>
    <PackageTags>spiderly;spiderly-shared;code-generation;crud-generator</PackageTags>
    <Company>Spiderly</Company>
    <ProjectUrl>https://www.spiderly.dev</ProjectUrl>
    <RepositoryUrl>https://github.com/filiptrivan/spiderly</RepositoryUrl>
	<GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Entities\**" />
    <EmbeddedResource Remove="Entities\**" />
    <None Remove="Entities\**" />
    <None Include="README.md" Pack="true" PackagePath="\" />
    <None Include="spiderly-logo.png" Pack="true" PackagePath="\" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Emailing\Templates\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" Version="4.0.11.3" />
    <PackageReference Include="Hangfire.Core" Version="1.8.*" />
    <PackageReference Include="CaseConverter" Version="2.0.1" />
    <PackageReference Include="CloudinaryDotNet" Version="1.27.8" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
<PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.14" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.22.2" />
    <PackageReference Include="Microsoft.Extensions.Azure" Version="1.7.6" />
    <PackageReference Include="FluentValidation" Version="11.9.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.1" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="9.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
<PackageReference Include="MiniExcel" Version="1.42.0" />
    <PackageReference Include="Mime-Detective" Version="25.8.1" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>